if(NOT DEFINED AIDA_C03_DIGEST_FILE OR NOT DEFINED AIDA_C03_HEADER_FILE)
    message(WARNING "AiDA C03 digest header materialization requires input and output paths")
endif()
if(NOT EXISTS "${AIDA_C03_DIGEST_FILE}" OR IS_DIRECTORY "${AIDA_C03_DIGEST_FILE}")
    message(WARNING "AiDA C03 safe-headless manifest digest is missing")
endif()
file(READ "${AIDA_C03_DIGEST_FILE}" _aida_c03_digest LIMIT 256)
string(STRIP "${_aida_c03_digest}" _aida_c03_digest)
string(LENGTH "${_aida_c03_digest}" _aida_c03_digest_length)
if(NOT _aida_c03_digest_length EQUAL 64 OR NOT _aida_c03_digest MATCHES "^[0-9a-f]+$")
    message(WARNING "AiDA C03 safe-headless manifest digest is malformed")
endif()
get_filename_component(_aida_c03_header_directory "${AIDA_C03_HEADER_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${_aida_c03_header_directory}")
set(_aida_c03_header_temporary "${AIDA_C03_HEADER_FILE}.tmp")
file(WRITE "${_aida_c03_header_temporary}"
    "#pragma once\n#define AIDA_C03_SAFE_HEADLESS_MANIFEST_SHA256 \"${_aida_c03_digest}\"\n")
configure_file("${_aida_c03_header_temporary}" "${AIDA_C03_HEADER_FILE}" COPYONLY)
file(REMOVE "${_aida_c03_header_temporary}")
