#!/usr/bin/env python3
"""
Build-time WB-AES lookup table generator.

Consumes a 32-byte build seed, derives an AES-128 key via HKDF-SHA256,
generates white-box AES T-boxes (10 rounds x 16 positions x 256 entries)
and MB-tables (9 rounds x 16 positions x 256 uint32_t entries) with
per-table XOR obfuscation keys, computes a test vector, a SHA-256 table
integrity hash, a verification key (for fallback mode), and a build ID.

The AES S-Box is computed internally and NEVER appears in the emitted
header. A signature scan verifies the S-Box sequence is absent from all
generated bytes before writing the output file.

Usage:
    python generate_wbaes_tables.py --seed <hex> --output <path> [--build-id <string>]
"""

import argparse
import hashlib
import hmac
import struct
import sys
from dataclasses import dataclass, field


# ---------------------------------------------------------------------------
# AES primitives (computed at build time, never emitted to the header)
# ---------------------------------------------------------------------------

def gf_mul(a: int, b: int) -> int:
    p = 0
    for _ in range(8):
        if b & 1:
            p ^= a
        hi = a & 0x80
        a = (a << 1) & 0xFF
        if hi:
            a ^= 0x1B
        b >>= 1
    return p


def gf_inv(a: int) -> int:
    if a == 0:
        return 0
    for b in range(1, 256):
        if gf_mul(a, b) == 1:
            return b
    return 0


def compute_sbox() -> list:
    sbox = [0] * 256
    for i in range(256):
        inv = gf_inv(i)
        result = 0
        for bit_pos in range(8):
            bit = (
                ((inv >> bit_pos) & 1)
                ^ ((inv >> ((bit_pos + 4) % 8)) & 1)
                ^ ((inv >> ((bit_pos + 5) % 8)) & 1)
                ^ ((inv >> ((bit_pos + 6) % 8)) & 1)
                ^ ((inv >> ((bit_pos + 7) % 8)) & 1)
                ^ ((0x63 >> bit_pos) & 1)
            )
            result |= bit << bit_pos
        sbox[i] = result
    return sbox


def compute_rcon() -> list:
    rcon = [0] * 11
    for i in range(11):
        if i == 0:
            rcon[i] = 0
        else:
            r = 1
            for _ in range(1, i):
                hi = r & 0x80
                r = (r << 1) & 0xFF
                if hi:
                    r ^= 0x1B
            rcon[i] = r
    return rcon


def sub_word(w: int, sbox: list) -> int:
    return (
        (sbox[(w >> 24) & 0xFF] << 24)
        | (sbox[(w >> 16) & 0xFF] << 16)
        | (sbox[(w >> 8) & 0xFF] << 8)
        | sbox[w & 0xFF]
    )


def rot_word(w: int) -> int:
    return ((w << 8) | (w >> 24)) & 0xFFFFFFFF


def key_expansion_128(key: bytes, sbox: list, rcon: list) -> list:
    rk = [0] * 44
    for i in range(4):
        rk[i] = struct.unpack('>I', key[4 * i:4 * i + 4])[0]
    for i in range(4, 44):
        t = rk[i - 1]
        if i % 4 == 0:
            t = sub_word(rot_word(t), sbox) ^ (rcon[i // 4] << 24)
        rk[i] = rk[i - 4] ^ t
    return rk


def round_keys_to_bytes(rk: list) -> list:
    kb = [0] * (16 * 11)
    for r in range(11):
        for c in range(4):
            w = rk[r * 4 + c]
            kb[r * 16 + c * 4 + 0] = (w >> 24) & 0xFF
            kb[r * 16 + c * 4 + 1] = (w >> 16) & 0xFF
            kb[r * 16 + c * 4 + 2] = (w >> 8) & 0xFF
            kb[r * 16 + c * 4 + 3] = w & 0xFF
    return kb


def gf_mul2(a: int) -> int:
    return ((a << 1) ^ (((a >> 7) & 1) * 0x1B)) & 0xFF


def gf_mul3(a: int) -> int:
    return gf_mul2(a) ^ a


def mc_word_for_row(v: int, row: int) -> int:
    b2 = gf_mul2(v)
    b3 = gf_mul3(v)
    if row == 0:
        r0, r1, r2, r3 = b2, v, v, b3
    elif row == 1:
        r0, r1, r2, r3 = b3, b2, v, v
    elif row == 2:
        r0, r1, r2, r3 = v, b3, b2, v
    else:
        r0, r1, r2, r3 = v, v, b3, b2
    return (r0 << 24) | (r1 << 16) | (r2 << 8) | r3


def sr_source_col(target_col: int, row: int) -> int:
    return (target_col + row) & 3


def sr_source_index(target_col: int, row: int) -> int:
    return sr_source_col(target_col, row) * 4 + row


# ---------------------------------------------------------------------------
# HKDF-SHA256 (RFC 5869)
# ---------------------------------------------------------------------------

def hkdf_extract(salt: bytes, ikm: bytes) -> bytes:
    if not salt:
        salt = b'\x00' * 32
    return hmac.new(salt, ikm, hashlib.sha256).digest()


def hkdf_expand(prk: bytes, info: bytes, length: int) -> bytes:
    hash_len = 32
    n = (length + hash_len - 1) // hash_len
    okm = b''
    t = b''
    for i in range(1, n + 1):
        t = hmac.new(prk, t + info + bytes([i]), hashlib.sha256).digest()
        okm += t
    return okm[:length]


def hkdf(ikm: bytes, salt: bytes = b'', info: bytes = b'', length: int = 32) -> bytes:
    prk = hkdf_extract(salt, ikm)
    return hkdf_expand(prk, info, length)


# ---------------------------------------------------------------------------
# Build-seeded PRNG (deterministic, HMAC-SHA256 counter mode)
# ---------------------------------------------------------------------------

class BuildPRNG:
    def __init__(self, seed: bytes):
        self._key = hmac.new(
            seed, b'WBAES-PRNG-KEY-V3', hashlib.sha256
        ).digest()
        self._counter = 0

    def emit(self, n: int) -> bytes:
        result = bytearray()
        while len(result) < n:
            block = hmac.new(
                self._key,
                struct.pack('<Q', self._counter),
                hashlib.sha256,
            ).digest()
            result.extend(block)
            self._counter += 1
        return bytes(result[:n])

    def next_byte(self) -> int:
        return self.emit(1)[0]

    def next_bytes(self, n: int) -> bytes:
        return self.emit(n)


# ---------------------------------------------------------------------------
# Table container
# ---------------------------------------------------------------------------

@dataclass
class WBTables:
    t_boxes: list = field(default_factory=lambda: [[[0] * 256 for _ in range(16)] for _ in range(10)])
    mb_tables: list = field(default_factory=lambda: [[[0] * 256 for _ in range(16)] for _ in range(9)])
    ext_in: bytearray = field(default_factory=lambda: bytearray(16))
    ext_out: bytearray = field(default_factory=lambda: bytearray(16))
    table_id: bytearray = field(default_factory=lambda: bytearray(16))
    t_xor_keys: list = field(default_factory=lambda: [[[0] * 32 for _ in range(16)] for _ in range(10)])
    mb_xor_keys: list = field(default_factory=lambda: [[[0] * 32 for _ in range(16)] for _ in range(9)])


@dataclass
class WBTablesMasked:
    t_boxes_s1: list = field(default_factory=lambda: [[[0] * 256 for _ in range(16)] for _ in range(10)])
    t_boxes_s2: list = field(default_factory=lambda: [[[0] * 256 for _ in range(16)] for _ in range(10)])
    mb_tables_s1: list = field(default_factory=lambda: [[[0] * 256 for _ in range(16)] for _ in range(9)])
    mb_tables_s2: list = field(default_factory=lambda: [[[0] * 256 for _ in range(16)] for _ in range(9)])
    ext_in: bytearray = field(default_factory=lambda: bytearray(16))
    ext_out: bytearray = field(default_factory=lambda: bytearray(16))
    table_id: bytearray = field(default_factory=lambda: bytearray(16))
    input_masks: list = field(default_factory=lambda: [[0] * 16 for _ in range(10)])
    output_masks: list = field(default_factory=lambda: [[0] * 16 for _ in range(10)])
    t_xor_keys_s1: list = field(default_factory=lambda: [[[0] * 32 for _ in range(16)] for _ in range(10)])
    t_xor_keys_s2: list = field(default_factory=lambda: [[[0] * 32 for _ in range(16)] for _ in range(10)])
    mb_xor_keys_s1: list = field(default_factory=lambda: [[[0] * 32 for _ in range(16)] for _ in range(9)])
    mb_xor_keys_s2: list = field(default_factory=lambda: [[[0] * 32 for _ in range(16)] for _ in range(9)])


k_col_order_py = [[0, 1, 2, 3] for _ in range(9)]


# ---------------------------------------------------------------------------
# Table generation
# ---------------------------------------------------------------------------

def generate_tables(seed: bytes) -> WBTables:
    sbox = compute_sbox()
    rcon = compute_rcon()

    aes_key = hkdf(seed, info=b'WBAES-KEY-V3', length=16)
    rk = key_expansion_128(aes_key, sbox, rcon)
    key_bytes = round_keys_to_bytes(rk)

    prng = BuildPRNG(seed)

    tbl = WBTables()
    tbl.ext_in = bytearray(prng.next_bytes(16))
    tbl.ext_out = bytearray(prng.next_bytes(16))
    tbl.table_id = bytearray(prng.next_bytes(16))

    for r in range(10):
        for pos in range(16):
            tbl.t_xor_keys[r][pos] = list(prng.next_bytes(32))
    for r in range(9):
        for pos in range(16):
            tbl.mb_xor_keys[r][pos] = list(prng.next_bytes(32))

    for r in range(10):
        for c in range(4):
            for i in range(4):
                src_idx = sr_source_index(c, i)
                pos = c * 4 + i

                input_enc = tbl.ext_in[src_idx] if r == 0 else 0
                rk_byte = key_bytes[r * 16 + src_idx]

                out_enc = 0
                if r == 9:
                    out_enc = key_bytes[10 * 16 + pos] ^ tbl.ext_out[pos]

                xor_byte = tbl.t_xor_keys[r][pos][0]

                for b in range(256):
                    sbox_val = sbox[b ^ input_enc ^ rk_byte]
                    t_val = sbox_val ^ out_enc
                    tbl.t_boxes[r][pos][b] = (t_val ^ xor_byte) & 0xFF

                if r < 9:
                    mb_xor_bytes = bytes(tbl.mb_xor_keys[r][pos][:4])
                    mb_xor_uint = struct.unpack('<I', mb_xor_bytes)[0]

                    for b in range(256):
                        sbox_val = sbox[b ^ input_enc ^ rk_byte]
                        mc_word = mc_word_for_row(sbox_val, i)
                        encoded = (mc_word ^ mb_xor_uint) & 0xFFFFFFFF
                        tbl.mb_tables[r][pos][b] = encoded

    return tbl


def generate_masked_tables(tbl: WBTables, seed: bytes) -> WBTablesMasked:
    sbox = compute_sbox()
    rcon = compute_rcon()
    aes_key = hkdf(seed, info=b'WBAES-KEY-V3', length=16)
    rk = key_expansion_128(aes_key, sbox, rcon)
    key_bytes = round_keys_to_bytes(rk)

    prng = BuildPRNG(seed + b'MASKED-SHARE-V1')

    masked = WBTablesMasked()
    masked.ext_in = bytearray(tbl.ext_in)
    masked.table_id = bytearray(tbl.table_id)

    for r in range(10):
        for pos in range(16):
            masked.input_masks[r][pos] = prng.next_byte()
            masked.output_masks[r][pos] = prng.next_byte()

    for r in range(10):
        for pos in range(16):
            masked.t_xor_keys_s1[r][pos] = list(prng.next_bytes(32))
            masked.t_xor_keys_s2[r][pos] = list(prng.next_bytes(32))
    for r in range(9):
        for pos in range(16):
            masked.mb_xor_keys_s1[r][pos] = list(prng.next_bytes(32))
            masked.mb_xor_keys_s2[r][pos] = list(prng.next_bytes(32))

    for pos in range(16):
        masked.ext_out[pos] = tbl.ext_out[pos] ^ masked.output_masks[9][pos]

    for r in range(10):
        for c in range(4):
            for i in range(4):
                src_idx = sr_source_index(c, i)
                pos = c * 4 + i

                input_enc = tbl.ext_in[src_idx] if r == 0 else 0
                rk_byte = key_bytes[r * 16 + src_idx]

                if r == 9:
                    out_enc = key_bytes[10 * 16 + pos]
                else:
                    out_enc = 0

                m_in = masked.input_masks[r][src_idx]
                m_out = masked.output_masks[r][pos]
                xor_s1 = masked.t_xor_keys_s1[r][pos][0]
                xor_s2 = masked.t_xor_keys_s2[r][pos][0]

                for b in range(256):
                    real_input = b ^ m_in
                    t_orig_masked = (sbox[real_input ^ input_enc ^ rk_byte] ^ out_enc) & 0xFF
                    r_byte = prng.next_byte()

                    t_s1 = (t_orig_masked ^ r_byte) & 0xFF
                    t_s2 = (r_byte ^ m_out) & 0xFF

                    masked.t_boxes_s1[r][pos][b] = (t_s1 ^ xor_s1) & 0xFF
                    masked.t_boxes_s2[r][pos][b] = (t_s2 ^ xor_s2) & 0xFF

    for r in range(9):
        for c in range(4):
            for i in range(4):
                src_idx = sr_source_index(c, i)
                pos = c * 4 + i

                input_enc = tbl.ext_in[src_idx] if r == 0 else 0
                rk_byte = key_bytes[r * 16 + src_idx]

                m_in = masked.input_masks[r][src_idx]
                mb_xor_s1_bytes = bytes(masked.mb_xor_keys_s1[r][pos][:4])
                mb_xor_s1_uint = struct.unpack('<I', mb_xor_s1_bytes)[0]
                mb_xor_s2_bytes = bytes(masked.mb_xor_keys_s2[r][pos][:4])
                mb_xor_s2_uint = struct.unpack('<I', mb_xor_s2_bytes)[0]

                for b in range(256):
                    real_input = b ^ m_in
                    sbox_val = sbox[real_input ^ input_enc ^ rk_byte]
                    mb_orig = mc_word_for_row(sbox_val, i)
                    r_word = struct.unpack('<I', prng.next_bytes(4))[0]

                    mb_s1 = (mb_orig ^ r_word) & 0xFFFFFFFF
                    mb_s2 = r_word

                    masked.mb_tables_s1[r][pos][b] = (mb_s1 ^ mb_xor_s1_uint) & 0xFFFFFFFF
                    masked.mb_tables_s2[r][pos][b] = (mb_s2 ^ mb_xor_s2_uint) & 0xFFFFFFFF

    return masked


# ---------------------------------------------------------------------------
# Encryption simulation (must match C++ encrypt_block exactly)
# ---------------------------------------------------------------------------

def encrypt_block(tbl: WBTables, plaintext: bytes) -> bytes:
    state = [plaintext[i] ^ tbl.ext_in[i] for i in range(16)]

    for r in range(9):
        next_state = [0] * 16
        for c in range(4):
            col = 0
            for i in range(4):
                src_idx = sr_source_index(c, i)
                pos = c * 4 + i
                stored = tbl.mb_tables[r][pos][state[src_idx]]
                mb_xor_bytes = bytes(tbl.mb_xor_keys[r][pos][:4])
                mb_xor_uint = struct.unpack('<I', mb_xor_bytes)[0]
                col ^= stored ^ mb_xor_uint
            next_state[c * 4 + 0] = (col >> 24) & 0xFF
            next_state[c * 4 + 1] = (col >> 16) & 0xFF
            next_state[c * 4 + 2] = (col >> 8) & 0xFF
            next_state[c * 4 + 3] = col & 0xFF
        state = next_state

    output = [0] * 16
    for c in range(4):
        for i in range(4):
            src_idx = sr_source_index(c, i)
            pos = c * 4 + i
            stored = tbl.t_boxes[9][pos][state[src_idx]]
            xor_byte = tbl.t_xor_keys[9][pos][0]
            output[pos] = (stored ^ xor_byte) & 0xFF

    return bytes(output)


def encrypt_block_masked(tbl: WBTablesMasked, plaintext: bytes) -> bytes:
    state = [plaintext[i] ^ tbl.ext_in[i] for i in range(16)]

    for r in range(9):
        next_state = [0] * 16
        for col_idx in range(4):
            c = k_col_order_py[r][col_idx]
            col = 0
            for i in range(4):
                src_idx = sr_source_index(c, i)
                pos = c * 4 + i
                masked_idx = (state[src_idx] ^ tbl.input_masks[r][src_idx]) & 0xFF

                stored_s1 = tbl.mb_tables_s1[r][pos][masked_idx]
                mb_xor_s1 = struct.unpack('<I', bytes(tbl.mb_xor_keys_s1[r][pos][:4]))[0]
                mb_s1 = stored_s1 ^ mb_xor_s1

                stored_s2 = tbl.mb_tables_s2[r][pos][masked_idx]
                mb_xor_s2 = struct.unpack('<I', bytes(tbl.mb_xor_keys_s2[r][pos][:4]))[0]
                mb_s2 = stored_s2 ^ mb_xor_s2

                col ^= mb_s1 ^ mb_s2

            next_state[c * 4 + 0] = (col >> 24) & 0xFF
            next_state[c * 4 + 1] = (col >> 16) & 0xFF
            next_state[c * 4 + 2] = (col >> 8) & 0xFF
            next_state[c * 4 + 3] = col & 0xFF
        state = next_state

    output = [0] * 16
    for c in range(4):
        for i in range(4):
            src_idx = sr_source_index(c, i)
            pos = c * 4 + i
            masked_idx = (state[src_idx] ^ tbl.input_masks[9][src_idx]) & 0xFF

            s1_val = tbl.t_boxes_s1[9][pos][masked_idx] ^ tbl.t_xor_keys_s1[9][pos][0]
            s2_val = tbl.t_boxes_s2[9][pos][masked_idx] ^ tbl.t_xor_keys_s2[9][pos][0]
            output[pos] = (s1_val ^ s2_val ^ tbl.ext_out[pos]) & 0xFF

    return bytes(output)


# ---------------------------------------------------------------------------
# Verification: scan for AES S-Box signature
# ---------------------------------------------------------------------------

SBOX_SIGNATURE = bytes(compute_sbox())


def verify_no_sbox_signature(tbl: WBTables) -> None:
    all_bytes = bytearray()

    for r in range(10):
        for pos in range(16):
            all_bytes.extend(bytes(tbl.t_boxes[r][pos]))
    for r in range(9):
        for pos in range(16):
            for b in range(256):
                all_bytes.extend(struct.pack('<I', tbl.mb_tables[r][pos][b]))
    all_bytes.extend(tbl.ext_in)
    all_bytes.extend(tbl.ext_out)
    all_bytes.extend(tbl.table_id)
    for r in range(10):
        for pos in range(16):
            all_bytes.extend(bytes(tbl.t_xor_keys[r][pos]))
    for r in range(9):
        for pos in range(16):
            all_bytes.extend(bytes(tbl.mb_xor_keys[r][pos]))

    flat = bytes(all_bytes)

    for offset in range(len(flat) - len(SBOX_SIGNATURE) + 1):
        if flat[offset:offset + len(SBOX_SIGNATURE)] == SBOX_SIGNATURE:
            raise AssertionError(
                f"AES S-Box signature found at byte offset {offset} "
                f"in generated table data"
            )

    sbox_prefix = SBOX_SIGNATURE[:16]
    for offset in range(len(flat) - len(sbox_prefix) + 1):
        if flat[offset:offset + len(sbox_prefix)] == sbox_prefix:
            if flat[offset:offset + len(SBOX_SIGNATURE)] == SBOX_SIGNATURE:
                raise AssertionError(
                    f"AES S-Box signature found at byte offset {offset}"
                )


def verify_masked_tables(tbl: WBTables, masked: WBTablesMasked, seed: bytes) -> None:
    sbox = compute_sbox()
    rcon = compute_rcon()
    aes_key = hkdf(seed, info=b'WBAES-KEY-V3', length=16)
    rk = key_expansion_128(aes_key, sbox, rcon)
    key_bytes = round_keys_to_bytes(rk)

    for r in range(10):
        for c in range(4):
            for i in range(4):
                src_idx = sr_source_index(c, i)
                pos = c * 4 + i

                input_enc = tbl.ext_in[src_idx] if r == 0 else 0
                rk_byte = key_bytes[r * 16 + src_idx]

                if r == 9:
                    out_enc = key_bytes[10 * 16 + pos]
                else:
                    out_enc = 0

                m_in = masked.input_masks[r][src_idx]
                m_out = masked.output_masks[r][pos]
                xor_s1 = masked.t_xor_keys_s1[r][pos][0]
                xor_s2 = masked.t_xor_keys_s2[r][pos][0]

                for b in range(256):
                    t_s1_decoded = masked.t_boxes_s1[r][pos][b] ^ xor_s1
                    t_s2_decoded = masked.t_boxes_s2[r][pos][b] ^ xor_s2
                    combined = (t_s1_decoded ^ t_s2_decoded) & 0xFF

                    real_input = b ^ m_in
                    expected = (sbox[real_input ^ input_enc ^ rk_byte] ^ out_enc ^ m_out) & 0xFF

                    if combined != expected:
                        raise AssertionError(
                            f"T-box masked mismatch at round {r} pos {pos} b {b}: "
                            f"got {combined:#x} expected {expected:#x}"
                        )

    for r in range(9):
        for c in range(4):
            for i in range(4):
                src_idx = sr_source_index(c, i)
                pos = c * 4 + i

                input_enc = tbl.ext_in[src_idx] if r == 0 else 0
                rk_byte = key_bytes[r * 16 + src_idx]

                m_in = masked.input_masks[r][src_idx]
                mb_xor_s1_uint = struct.unpack('<I', bytes(masked.mb_xor_keys_s1[r][pos][:4]))[0]
                mb_xor_s2_uint = struct.unpack('<I', bytes(masked.mb_xor_keys_s2[r][pos][:4]))[0]

                for b in range(256):
                    mb_s1_decoded = masked.mb_tables_s1[r][pos][b] ^ mb_xor_s1_uint
                    mb_s2_decoded = masked.mb_tables_s2[r][pos][b] ^ mb_xor_s2_uint
                    combined = (mb_s1_decoded ^ mb_s2_decoded) & 0xFFFFFFFF

                    real_input = b ^ m_in
                    sbox_val = sbox[real_input ^ input_enc ^ rk_byte]
                    expected = mc_word_for_row(sbox_val, i)

                    if combined != expected:
                        raise AssertionError(
                            f"MB-table masked mismatch at round {r} pos {pos} b {b}: "
                            f"got {combined:#010x} expected {expected:#010x}"
                        )

    test_vectors = [
        bytes(16),
        bytes(range(16)),
        bytes([0xFF] * 16),
        bytes([0xAA, 0x55] * 8),
    ]
    for tv_idx, pt in enumerate(test_vectors):
        unmasked_ct = encrypt_block(tbl, pt)
        masked_ct = encrypt_block_masked(masked, pt)
        if unmasked_ct != masked_ct:
            raise AssertionError(
                f"Masked encryption mismatch (vector {tv_idx}):\n"
                f"  plaintext:  {pt.hex()}\n"
                f"  unmasked:   {unmasked_ct.hex()}\n"
                f"  masked:     {masked_ct.hex()}"
            )


# ---------------------------------------------------------------------------
# Table serialization and hash
# ---------------------------------------------------------------------------

def serialize_tables(tbl: WBTables) -> bytes:
    data = bytearray()

    for r in range(10):
        for pos in range(16):
            data.extend(bytes(tbl.t_boxes[r][pos]))

    for r in range(9):
        for pos in range(16):
            for b in range(256):
                data.extend(struct.pack('<I', tbl.mb_tables[r][pos][b]))

    data.extend(tbl.ext_in)
    data.extend(tbl.ext_out)
    data.extend(tbl.table_id)

    for r in range(10):
        for pos in range(16):
            data.extend(bytes(tbl.t_xor_keys[r][pos]))

    for r in range(9):
        for pos in range(16):
            data.extend(bytes(tbl.mb_xor_keys[r][pos]))

    return bytes(data)


def table_hash(tbl: WBTables) -> bytes:
    return hashlib.sha256(serialize_tables(tbl)).digest()


def serialize_masked_tables(masked: WBTablesMasked) -> bytes:
    data = bytearray()

    for r in range(10):
        for pos in range(16):
            data.extend(bytes(masked.t_boxes_s1[r][pos]))
    for r in range(10):
        for pos in range(16):
            data.extend(bytes(masked.t_boxes_s2[r][pos]))
    for r in range(9):
        for pos in range(16):
            for b in range(256):
                data.extend(struct.pack('<I', masked.mb_tables_s1[r][pos][b]))
    for r in range(9):
        for pos in range(16):
            for b in range(256):
                data.extend(struct.pack('<I', masked.mb_tables_s2[r][pos][b]))
    data.extend(masked.ext_in)
    data.extend(masked.ext_out)
    data.extend(masked.table_id)
    for r in range(10):
        data.extend(bytes(masked.input_masks[r]))
    for r in range(10):
        data.extend(bytes(masked.output_masks[r]))
    for r in range(10):
        for pos in range(16):
            data.extend(bytes(masked.t_xor_keys_s1[r][pos]))
    for r in range(10):
        for pos in range(16):
            data.extend(bytes(masked.t_xor_keys_s2[r][pos]))
    for r in range(9):
        for pos in range(16):
            data.extend(bytes(masked.mb_xor_keys_s1[r][pos]))
    for r in range(9):
        for pos in range(16):
            data.extend(bytes(masked.mb_xor_keys_s2[r][pos]))

    return bytes(data)


# ---------------------------------------------------------------------------
# Verification key derivation (for fallback mode)
# ---------------------------------------------------------------------------

def derive_verification_key(seed: bytes) -> bytes:
    return hkdf(seed, info=b'WBVERKEY-V3', length=16)


def derive_build_id(seed: bytes, build_id_str: str) -> bytes:
    h = hashlib.sha256()
    h.update(seed)
    h.update(b'WBBUILDID-V3')
    h.update(build_id_str.encode('utf-8'))
    return h.digest()[:16]


# ---------------------------------------------------------------------------
# C++ header emission
# ---------------------------------------------------------------------------

def fmt_bytes(data, per_line=16, indent='    '):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        hex_vals = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'{indent}{hex_vals},')
    return '\n'.join(lines)


def fmt_uint32_array(values, per_line=4, indent='            '):
    lines = []
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        hex_vals = ', '.join(f'0x{v:08x}u' for v in chunk)
        lines.append(f'{indent}{hex_vals},')
    return '\n'.join(lines)


def emit_header(
    tbl: WBTables,
    test_vector: bytes,
    hash_val: bytes,
    ver_obf: bytes,
    ver_xor: bytes,
    build_id: bytes,
    build_id_str: str,
) -> str:
    out = []
    out.append('#pragma once')
    out.append('')
    out.append(f'// Auto-generated by generate_wbaes_tables.py')
    out.append(f'// Build ID: {build_id_str}')
    out.append(f'// DO NOT EDIT MANUALLY')
    out.append('')
    out.append('static const white_box_table_t kWbaesTables = {')
    out.append('    {')
    for r in range(10):
        out.append(f'        {{ // t_boxes round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            row_data = bytes(tbl.t_boxes[r][pos])
            out.append(fmt_bytes(row_data, per_line=16, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')
    out.append('    {')
    for r in range(9):
        out.append(f'        {{ // mb_tables round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            vals = tbl.mb_tables[r][pos]
            out.append(fmt_uint32_array(vals, per_line=4, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')
    out.append(f'    {{ // ext_in')
    out.append(fmt_bytes(tbl.ext_in, per_line=16, indent='        '))
    out.append('    },')
    out.append(f'    {{ // ext_out')
    out.append(fmt_bytes(tbl.ext_out, per_line=16, indent='        '))
    out.append('    },')
    out.append(f'    {{ // table_id')
    out.append(fmt_bytes(tbl.table_id, per_line=16, indent='        '))
    out.append('    },')
    out.append('    {')
    for r in range(10):
        out.append(f'        {{ // t_xor_keys round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            xor_data = bytes(tbl.t_xor_keys[r][pos])
            out.append(fmt_bytes(xor_data, per_line=16, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')
    out.append('    {')
    for r in range(9):
        out.append(f'        {{ // mb_xor_keys round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            xor_data = bytes(tbl.mb_xor_keys[r][pos])
            out.append(fmt_bytes(xor_data, per_line=16, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')
    out.append('};')
    out.append('')
    out.append('static constexpr uint8_t kWbaesTestVector[32] = {')
    out.append(fmt_bytes(test_vector, per_line=16, indent='    '))
    out.append('};')
    out.append('')
    out.append('static constexpr uint8_t kWbaesTableHash[32] = {')
    out.append(fmt_bytes(hash_val, per_line=16, indent='    '))
    out.append('};')
    out.append('')

    out.append('static constexpr uint8_t kWbaesVerificationKeyObf[16] = {')
    out.append(fmt_bytes(ver_obf, per_line=16, indent='    '))
    out.append('};')
    out.append('')
    out.append('static constexpr uint8_t kWbaesVerificationKeyXor[16] = {')
    out.append(fmt_bytes(ver_xor, per_line=16, indent='    '))
    out.append('};')
    out.append('')
    out.append('static constexpr uint8_t kWbaesBuildId[16] = {')
    out.append(fmt_bytes(build_id, per_line=16, indent='    '))
    out.append('};')
    out.append('')

    return '\n'.join(out)


def emit_masked_tables(masked: WBTablesMasked) -> str:
    out = []
    out.append('static const white_box_table_masked_t kWbaesTablesMasked = {')

    out.append('    {')
    for r in range(10):
        out.append(f'        {{ // t_boxes_s1 round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            out.append(fmt_bytes(bytes(masked.t_boxes_s1[r][pos]), per_line=16, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')

    out.append('    {')
    for r in range(10):
        out.append(f'        {{ // t_boxes_s2 round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            out.append(fmt_bytes(bytes(masked.t_boxes_s2[r][pos]), per_line=16, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')

    out.append('    {')
    for r in range(9):
        out.append(f'        {{ // mb_tables_s1 round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            out.append(fmt_uint32_array(masked.mb_tables_s1[r][pos], per_line=4, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')

    out.append('    {')
    for r in range(9):
        out.append(f'        {{ // mb_tables_s2 round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            out.append(fmt_uint32_array(masked.mb_tables_s2[r][pos], per_line=4, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')

    out.append('    { // ext_in')
    out.append(fmt_bytes(masked.ext_in, per_line=16, indent='        '))
    out.append('    },')

    out.append('    { // ext_out')
    out.append(fmt_bytes(masked.ext_out, per_line=16, indent='        '))
    out.append('    },')

    out.append('    { // table_id')
    out.append(fmt_bytes(masked.table_id, per_line=16, indent='        '))
    out.append('    },')

    out.append('    { // input_masks')
    for r in range(10):
        out.append(f'        {{ // round {r}')
        out.append(fmt_bytes(bytes(masked.input_masks[r]), per_line=16, indent='            '))
        out.append('        },')
    out.append('    },')

    out.append('    { // output_masks')
    for r in range(10):
        out.append(f'        {{ // round {r}')
        out.append(fmt_bytes(bytes(masked.output_masks[r]), per_line=16, indent='            '))
        out.append('        },')
    out.append('    },')

    out.append('    {')
    for r in range(10):
        out.append(f'        {{ // t_xor_keys_s1 round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            out.append(fmt_bytes(bytes(masked.t_xor_keys_s1[r][pos]), per_line=16, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')

    out.append('    {')
    for r in range(10):
        out.append(f'        {{ // t_xor_keys_s2 round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            out.append(fmt_bytes(bytes(masked.t_xor_keys_s2[r][pos]), per_line=16, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')

    out.append('    {')
    for r in range(9):
        out.append(f'        {{ // mb_xor_keys_s1 round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            out.append(fmt_bytes(bytes(masked.mb_xor_keys_s1[r][pos]), per_line=16, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')

    out.append('    {')
    for r in range(9):
        out.append(f'        {{ // mb_xor_keys_s2 round {r}')
        for pos in range(16):
            out.append(f'            {{ // pos {pos}')
            out.append(fmt_bytes(bytes(masked.mb_xor_keys_s2[r][pos]), per_line=16, indent='                '))
            out.append('            },')
        out.append('        },')
    out.append('    },')

    out.append('};')
    out.append('')

    return '\n'.join(out)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='Generate WB-AES lookup tables at build time'
    )
    parser.add_argument(
        '--seed',
        required=True,
        help='Build seed as a hex string (64 hex chars = 32 bytes)',
    )
    parser.add_argument(
        '--output',
        required=True,
        help='Output file path for the generated C++ header',
    )
    parser.add_argument(
        '--build-id',
        default='',
        help='Build identifier string embedded in the header',
    )
    args = parser.parse_args()

    seed = bytes.fromhex(args.seed)
    if len(seed) != 32:
        sys.stderr.write(
            f'Error: seed must be exactly 32 bytes (64 hex chars), got {len(seed)} bytes\n'
        )
        sys.exit(1)

    tbl = generate_tables(seed)

    verify_no_sbox_signature(tbl)

    test_plaintext = bytes(16)
    test_ciphertext = encrypt_block(tbl, test_plaintext)
    test_vector = test_plaintext + test_ciphertext

    hash_val = table_hash(tbl)

    ver_key = derive_verification_key(seed)
    ver_xor = hkdf(seed, info=b'WBVERKEYXOR-V3', length=16)
    ver_obf = bytes(a ^ b for a, b in zip(ver_key, ver_xor))
    build_id = derive_build_id(seed, args.build_id)

    masked_tbl = generate_masked_tables(tbl, seed)
    verify_masked_tables(tbl, masked_tbl, seed)

    header = emit_header(tbl, test_vector, hash_val, ver_obf, ver_xor, build_id, args.build_id)
    header += '\n' + emit_masked_tables(masked_tbl)

    with open(args.output, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header)

    masked_size = len(serialize_masked_tables(masked_tbl))
    sys.stderr.write(
        f'Generated {args.output}\n'
        f'  Tables: {len(serialize_tables(tbl))} bytes\n'
        f'  Masked tables: {masked_size} bytes\n'
        f'  Test vector: {test_ciphertext.hex()}\n'
        f'  Table hash: {hash_val.hex()}\n'
        f'  Build ID: {build_id.hex()}\n'
        f'  S-Box signature scan: PASS\n'
        f'  Masked table verification: PASS\n'
    )


if __name__ == '__main__':
    main()
