#pragma once

#include <cstdint>
#include <cstring>
#include <optional>
#include <string>
#include <string_view>

namespace aida::analysis::api_prototypes {

struct api_prototype_entry_t {
    const char* module;
    const char* name;
    const char* signature;
    bool is_noreturn;
    bool is_crt;
};

inline constexpr api_prototype_entry_t k_entries[] = {
    { "kernel32.dll", "GetLastError", "DWORD __stdcall GetLastError(void)", false, false },
    { "kernel32.dll", "SetLastError", "void __stdcall SetLastError(DWORD dwErrCode)", false, false },
    { "kernel32.dll", "CloseHandle", "BOOL __stdcall CloseHandle(HANDLE hObject)", false, false },
    { "kernel32.dll", "CreateFileW", "HANDLE __stdcall CreateFileW(LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPVOID lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile)", false, false },
    { "kernel32.dll", "CreateFileA", "HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPVOID lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile)", false, false },
    { "kernel32.dll", "ReadFile", "BOOL __stdcall ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPVOID lpOverlapped)", false, false },
    { "kernel32.dll", "WriteFile", "BOOL __stdcall WriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPVOID lpOverlapped)", false, false },
    { "kernel32.dll", "DeleteFileW", "BOOL __stdcall DeleteFileW(LPCWSTR lpFileName)", false, false },
    { "kernel32.dll", "DeleteFileA", "BOOL __stdcall DeleteFileA(LPCSTR lpFileName)", false, false },
    { "kernel32.dll", "CreateDirectoryW", "BOOL __stdcall CreateDirectoryW(LPCWSTR lpPathName, LPVOID lpSecurityAttributes)", false, false },
    { "kernel32.dll", "RemoveDirectoryW", "BOOL __stdcall RemoveDirectoryW(LPCWSTR lpPathName)", false, false },
    { "kernel32.dll", "GetFileAttributesW", "DWORD __stdcall GetFileAttributesW(LPCWSTR lpFileName)", false, false },
    { "kernel32.dll", "GetFileAttributesA", "DWORD __stdcall GetFileAttributesA(LPCSTR lpFileName)", false, false },
    { "kernel32.dll", "SetFileAttributesW", "BOOL __stdcall SetFileAttributesW(LPCWSTR lpFileName, DWORD dwFileAttributes)", false, false },
    { "kernel32.dll", "GetFileSizeEx", "BOOL __stdcall GetFileSizeEx(HANDLE hFile, LPVOID lpFileSize)", false, false },
    { "kernel32.dll", "GetFileSize", "DWORD __stdcall GetFileSize(HANDLE hFile, LPDWORD lpFileSizeHigh)", false, false },
    { "kernel32.dll", "SetFilePointer", "DWORD __stdcall SetFilePointer(HANDLE hFile, LONG lDistanceToMove, LPVOID lpDistanceToMoveHigh, DWORD dwMoveMethod)", false, false },
    { "kernel32.dll", "SetFilePointerEx", "BOOL __stdcall SetFilePointerEx(HANDLE hFile, LONGLONG liDistanceToMove, LPVOID lpNewFilePointer, DWORD dwMoveMethod)", false, false },
    { "kernel32.dll", "SetEndOfFile", "BOOL __stdcall SetEndOfFile(HANDLE hFile)", false, false },
    { "kernel32.dll", "FlushFileBuffers", "BOOL __stdcall FlushFileBuffers(HANDLE hFile)", false, false },
    { "kernel32.dll", "GetTempPathW", "DWORD __stdcall GetTempPathW(DWORD nBufferLength, LPWSTR lpBuffer)", false, false },
    { "kernel32.dll", "GetTempFileNameW", "UINT __stdcall GetTempFileNameW(LPCWSTR lpPathName, LPCWSTR lpPrefixString, UINT uUnique, LPWSTR lpTempFileName)", false, false },
    { "kernel32.dll", "CreateFileMappingW", "HANDLE __stdcall CreateFileMappingW(HANDLE hFile, LPVOID lpFileMappingAttributes, DWORD flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPCWSTR lpName)", false, false },
    { "kernel32.dll", "OpenFileMappingW", "HANDLE __stdcall OpenFileMappingW(DWORD dwDesiredAccess, BOOL bInheritHandle, LPCWSTR lpName)", false, false },
    { "kernel32.dll", "MapViewOfFile", "LPVOID __stdcall MapViewOfFile(HANDLE hFileMappingObject, DWORD dwDesiredAccess, DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow, SIZE_T dwNumberOfBytesToMap)", false, false },
    { "kernel32.dll", "UnmapViewOfFile", "BOOL __stdcall UnmapViewOfFile(LPCVOID lpBaseAddress)", false, false },
    { "kernel32.dll", "VirtualAlloc", "LPVOID __stdcall VirtualAlloc(LPVOID lpAddress, SIZE_T dwSize, DWORD flAllocationType, DWORD flProtect)", false, false },
    { "kernel32.dll", "VirtualFree", "BOOL __stdcall VirtualFree(LPVOID lpAddress, SIZE_T dwSize, DWORD dwFreeType)", false, false },
    { "kernel32.dll", "VirtualProtect", "BOOL __stdcall VirtualProtect(LPVOID lpAddress, SIZE_T dwSize, DWORD flNewProtect, LPDWORD lpflOldProtect)", false, false },
    { "kernel32.dll", "VirtualQuery", "SIZE_T __stdcall VirtualQuery(LPCVOID lpAddress, LPVOID lpBuffer, SIZE_T dwLength)", false, false },
    { "kernel32.dll", "VirtualAllocEx", "LPVOID __stdcall VirtualAllocEx(HANDLE hProcess, LPVOID lpAddress, SIZE_T dwSize, DWORD flAllocationType, DWORD flProtect)", false, false },
    { "kernel32.dll", "VirtualFreeEx", "BOOL __stdcall VirtualFreeEx(HANDLE hProcess, LPVOID lpAddress, SIZE_T dwSize, DWORD dwFreeType)", false, false },
    { "kernel32.dll", "VirtualProtectEx", "BOOL __stdcall VirtualProtectEx(HANDLE hProcess, LPVOID lpAddress, SIZE_T dwSize, DWORD flNewProtect, LPDWORD lpflOldProtect)", false, false },
    { "kernel32.dll", "VirtualQueryEx", "SIZE_T __stdcall VirtualQueryEx(HANDLE hProcess, LPCVOID lpAddress, LPVOID lpBuffer, SIZE_T dwLength)", false, false },
    { "kernel32.dll", "ReadProcessMemory", "BOOL __stdcall ReadProcessMemory(HANDLE hProcess, LPCVOID lpBaseAddress, LPVOID lpBuffer, SIZE_T nSize, LPVOID lpNumberOfBytesRead)", false, false },
    { "kernel32.dll", "WriteProcessMemory", "BOOL __stdcall WriteProcessMemory(HANDLE hProcess, LPVOID lpBaseAddress, LPCVOID lpBuffer, SIZE_T nSize, LPVOID lpNumberOfBytesWritten)", false, false },
    { "kernel32.dll", "HeapAlloc", "LPVOID __stdcall HeapAlloc(HANDLE hHeap, DWORD dwFlags, SIZE_T dwBytes)", false, false },
    { "kernel32.dll", "HeapFree", "BOOL __stdcall HeapFree(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem)", false, false },
    { "kernel32.dll", "HeapReAlloc", "LPVOID __stdcall HeapReAlloc(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem, SIZE_T dwBytes)", false, false },
    { "kernel32.dll", "HeapSize", "SIZE_T __stdcall HeapSize(HANDLE hHeap, DWORD dwFlags, LPCVOID lpMem)", false, false },
    { "kernel32.dll", "HeapCreate", "HANDLE __stdcall HeapCreate(DWORD flOptions, SIZE_T dwInitialSize, SIZE_T dwMaximumSize)", false, false },
    { "kernel32.dll", "HeapDestroy", "BOOL __stdcall HeapDestroy(HANDLE hHeap)", false, false },
    { "kernel32.dll", "GetProcessHeap", "HANDLE __stdcall GetProcessHeap(void)", false, false },
    { "kernel32.dll", "LocalAlloc", "LPVOID __stdcall LocalAlloc(UINT uFlags, SIZE_T uBytes)", false, false },
    { "kernel32.dll", "LocalFree", "LPVOID __stdcall LocalFree(LPVOID hMem)", false, false },
    { "kernel32.dll", "GlobalAlloc", "LPVOID __stdcall GlobalAlloc(UINT uFlags, SIZE_T dwBytes)", false, false },
    { "kernel32.dll", "GlobalFree", "LPVOID __stdcall GlobalFree(LPVOID hMem)", false, false },
    { "kernel32.dll", "GetModuleHandleW", "HMODULE __stdcall GetModuleHandleW(LPCWSTR lpModuleName)", false, false },
    { "kernel32.dll", "GetModuleHandleA", "HMODULE __stdcall GetModuleHandleA(LPCSTR lpModuleName)", false, false },
    { "kernel32.dll", "GetModuleHandleExW", "BOOL __stdcall GetModuleHandleExW(DWORD dwFlags, LPCWSTR lpModuleName, LPVOID phModule)", false, false },
    { "kernel32.dll", "GetModuleFileNameW", "DWORD __stdcall GetModuleFileNameW(HMODULE hModule, LPWSTR lpFilename, DWORD nSize)", false, false },
    { "kernel32.dll", "GetModuleFileNameA", "DWORD __stdcall GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename, DWORD nSize)", false, false },
    { "kernel32.dll", "LoadLibraryW", "HMODULE __stdcall LoadLibraryW(LPCWSTR lpLibFileName)", false, false },
    { "kernel32.dll", "LoadLibraryA", "HMODULE __stdcall LoadLibraryA(LPCSTR lpLibFileName)", false, false },
    { "kernel32.dll", "LoadLibraryExW", "HMODULE __stdcall LoadLibraryExW(LPCWSTR lpLibFileName, HANDLE hFile, DWORD dwFlags)", false, false },
    { "kernel32.dll", "FreeLibrary", "BOOL __stdcall FreeLibrary(HMODULE hLibModule)", false, false },
    { "kernel32.dll", "GetProcAddress", "LPVOID __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName)", false, false },
    { "kernel32.dll", "GetCurrentProcess", "HANDLE __stdcall GetCurrentProcess(void)", false, false },
    { "kernel32.dll", "GetCurrentProcessId", "DWORD __stdcall GetCurrentProcessId(void)", false, false },
    { "kernel32.dll", "GetCurrentThread", "HANDLE __stdcall GetCurrentThread(void)", false, false },
    { "kernel32.dll", "GetCurrentThreadId", "DWORD __stdcall GetCurrentThreadId(void)", false, false },
    { "kernel32.dll", "OpenProcess", "HANDLE __stdcall OpenProcess(DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwProcessId)", false, false },
    { "kernel32.dll", "OpenThread", "HANDLE __stdcall OpenThread(DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwThreadId)", false, false },
    { "kernel32.dll", "TerminateProcess", "BOOL __stdcall TerminateProcess(HANDLE hProcess, UINT uExitCode)", true, false },
    { "kernel32.dll", "ExitProcess", "void __stdcall ExitProcess(UINT uExitCode)", true, false },
    { "kernel32.dll", "CreateProcessW", "BOOL __stdcall CreateProcessW(LPCWSTR lpApplicationName, LPWSTR lpCommandLine, LPVOID lpProcessAttributes, LPVOID lpThreadAttributes, BOOL bInheritHandles, DWORD dwCreationFlags, LPVOID lpEnvironment, LPCWSTR lpCurrentDirectory, LPVOID lpStartupInfo, LPVOID lpProcessInformation)", false, false },
    { "kernel32.dll", "CreateProcessA", "BOOL __stdcall CreateProcessA(LPCSTR lpApplicationName, LPSTR lpCommandLine, LPVOID lpProcessAttributes, LPVOID lpThreadAttributes, BOOL bInheritHandles, DWORD dwCreationFlags, LPVOID lpEnvironment, LPCSTR lpCurrentDirectory, LPVOID lpStartupInfo, LPVOID lpProcessInformation)", false, false },
    { "kernel32.dll", "WaitForSingleObject", "DWORD __stdcall WaitForSingleObject(HANDLE hHandle, DWORD dwMilliseconds)", false, false },
    { "kernel32.dll", "WaitForSingleObjectEx", "DWORD __stdcall WaitForSingleObjectEx(HANDLE hHandle, DWORD dwMilliseconds, BOOL bAlertable)", false, false },
    { "kernel32.dll", "WaitForMultipleObjects", "DWORD __stdcall WaitForMultipleObjects(DWORD nCount, LPVOID lpHandles, BOOL bWaitAll, DWORD dwMilliseconds)", false, false },
    { "kernel32.dll", "WaitForMultipleObjectsEx", "DWORD __stdcall WaitForMultipleObjectsEx(DWORD nCount, LPVOID lpHandles, BOOL bWaitAll, DWORD dwMilliseconds, BOOL bAlertable)", false, false },
    { "kernel32.dll", "CreateEventW", "HANDLE __stdcall CreateEventW(LPVOID lpEventAttributes, BOOL bManualReset, BOOL bInitialState, LPCWSTR lpName)", false, false },
    { "kernel32.dll", "CreateEventA", "HANDLE __stdcall CreateEventA(LPVOID lpEventAttributes, BOOL bManualReset, BOOL bInitialState, LPCSTR lpName)", false, false },
    { "kernel32.dll", "OpenEventW", "HANDLE __stdcall OpenEventW(DWORD dwDesiredAccess, BOOL bInheritHandle, LPCWSTR lpName)", false, false },
    { "kernel32.dll", "SetEvent", "BOOL __stdcall SetEvent(HANDLE hEvent)", false, false },
    { "kernel32.dll", "ResetEvent", "BOOL __stdcall ResetEvent(HANDLE hEvent)", false, false },
    { "kernel32.dll", "CreateMutexW", "HANDLE __stdcall CreateMutexW(LPVOID lpMutexAttributes, BOOL bInitialOwner, LPCWSTR lpName)", false, false },
    { "kernel32.dll", "CreateMutexA", "HANDLE __stdcall CreateMutexA(LPVOID lpMutexAttributes, BOOL bInitialOwner, LPCSTR lpName)", false, false },
    { "kernel32.dll", "OpenMutexW", "HANDLE __stdcall OpenMutexW(DWORD dwDesiredAccess, BOOL bInheritHandle, LPCWSTR lpName)", false, false },
    { "kernel32.dll", "ReleaseMutex", "BOOL __stdcall ReleaseMutex(HANDLE hMutex)", false, false },
    { "kernel32.dll", "CreateSemaphoreW", "HANDLE __stdcall CreateSemaphoreW(LPVOID lpSemaphoreAttributes, LONG lInitialCount, LONG lMaximumCount, LPCWSTR lpName)", false, false },
    { "kernel32.dll", "ReleaseSemaphore", "BOOL __stdcall ReleaseSemaphore(HANDLE hSemaphore, LONG lReleaseCount, LPVOID lpPreviousCount)", false, false },
    { "kernel32.dll", "CreateThread", "HANDLE __stdcall CreateThread(LPVOID lpThreadAttributes, SIZE_T dwStackSize, LPVOID lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags, LPDWORD lpThreadId)", false, false },
    { "kernel32.dll", "CreateRemoteThread", "HANDLE __stdcall CreateRemoteThread(HANDLE hProcess, LPVOID lpThreadAttributes, SIZE_T dwStackSize, LPVOID lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags, LPDWORD lpThreadId)", false, false },
    { "kernel32.dll", "ExitThread", "void __stdcall ExitThread(DWORD dwExitCode)", true, false },
    { "kernel32.dll", "GetExitCodeThread", "BOOL __stdcall GetExitCodeThread(HANDLE hThread, LPDWORD lpExitCode)", false, false },
    { "kernel32.dll", "Sleep", "void __stdcall Sleep(DWORD dwMilliseconds)", false, false },
    { "kernel32.dll", "SleepEx", "DWORD __stdcall SleepEx(DWORD dwMilliseconds, BOOL bAlertable)", false, false },
    { "kernel32.dll", "SwitchToThread", "BOOL __stdcall SwitchToThread(void)", false, false },
    { "kernel32.dll", "InitializeCriticalSection", "void __stdcall InitializeCriticalSection(LPVOID lpCriticalSection)", false, false },
    { "kernel32.dll", "InitializeCriticalSectionEx", "void __stdcall InitializeCriticalSectionEx(LPVOID lpCriticalSection, DWORD dwSpinCount, DWORD Flags)", false, false },
    { "kernel32.dll", "InitializeCriticalSectionAndSpinCount", "BOOL __stdcall InitializeCriticalSectionAndSpinCount(LPVOID lpCriticalSection, DWORD dwSpinCount)", false, false },
    { "kernel32.dll", "DeleteCriticalSection", "void __stdcall DeleteCriticalSection(LPVOID lpCriticalSection)", false, false },
    { "kernel32.dll", "EnterCriticalSection", "void __stdcall EnterCriticalSection(LPVOID lpCriticalSection)", false, false },
    { "kernel32.dll", "LeaveCriticalSection", "void __stdcall LeaveCriticalSection(LPVOID lpCriticalSection)", false, false },
    { "kernel32.dll", "TryEnterCriticalSection", "BOOL __stdcall TryEnterCriticalSection(LPVOID lpCriticalSection)", false, false },
    { "kernel32.dll", "InitializeSRWLock", "void __stdcall InitializeSRWLock(LPVOID SRWLock)", false, false },
    { "kernel32.dll", "AcquireSRWLockExclusive", "void __stdcall AcquireSRWLockExclusive(LPVOID SRWLock)", false, false },
    { "kernel32.dll", "AcquireSRWLockShared", "void __stdcall AcquireSRWLockShared(LPVOID SRWLock)", false, false },
    { "kernel32.dll", "ReleaseSRWLockExclusive", "void __stdcall ReleaseSRWLockExclusive(LPVOID SRWLock)", false, false },
    { "kernel32.dll", "ReleaseSRWLockShared", "void __stdcall ReleaseSRWLockShared(LPVOID SRWLock)", false, false },
    { "kernel32.dll", "TryAcquireSRWLockExclusive", "BOOLEAN __stdcall TryAcquireSRWLockExclusive(LPVOID SRWLock)", false, false },
    { "kernel32.dll", "TryAcquireSRWLockShared", "BOOLEAN __stdcall TryAcquireSRWLockShared(LPVOID SRWLock)", false, false },
    { "kernel32.dll", "InitializeConditionVariable", "void __stdcall InitializeConditionVariable(LPVOID ConditionVariable)", false, false },
    { "kernel32.dll", "SleepConditionVariableCS", "BOOL __stdcall SleepConditionVariableCS(LPVOID ConditionVariable, LPVOID CriticalSection, DWORD dwMilliseconds)", false, false },
    { "kernel32.dll", "SleepConditionVariableSRW", "BOOL __stdcall SleepConditionVariableSRW(LPVOID ConditionVariable, LPVOID SRWLock, DWORD dwMilliseconds, ULONG Flags)", false, false },
    { "kernel32.dll", "WakeConditionVariable", "void __stdcall WakeConditionVariable(LPVOID ConditionVariable)", false, false },
    { "kernel32.dll", "WakeAllConditionVariable", "void __stdcall WakeAllConditionVariable(LPVOID ConditionVariable)", false, false },
    { "kernel32.dll", "InterlockedIncrement", "LONG __stdcall InterlockedIncrement(LPVOID Addend)", false, false },
    { "kernel32.dll", "InterlockedDecrement", "LONG __stdcall InterlockedDecrement(LPVOID Addend)", false, false },
    { "kernel32.dll", "InterlockedExchange", "LONG __stdcall InterlockedExchange(LPVOID Target, LONG Value)", false, false },
    { "kernel32.dll", "InterlockedExchangeAdd", "LONG __stdcall InterlockedExchangeAdd(LPVOID Addend, LONG Value)", false, false },
    { "kernel32.dll", "InterlockedCompareExchange", "LONG __stdcall InterlockedCompareExchange(LPVOID Destination, LONG Exchange, LONG Comparand)", false, false },
    { "kernel32.dll", "QueryPerformanceCounter", "BOOL __stdcall QueryPerformanceCounter(LPVOID lpPerformanceCount)", false, false },
    { "kernel32.dll", "QueryPerformanceFrequency", "BOOL __stdcall QueryPerformanceFrequency(LPVOID lpFrequency)", false, false },
    { "kernel32.dll", "GetTickCount", "DWORD __stdcall GetTickCount(void)", false, false },
    { "kernel32.dll", "GetTickCount64", "ULONGLONG __stdcall GetTickCount64(void)", false, false },
    { "kernel32.dll", "GetSystemTimeAsFileTime", "void __stdcall GetSystemTimeAsFileTime(LPVOID lpSystemTimeAsFileTime)", false, false },
    { "kernel32.dll", "FileTimeToSystemTime", "BOOL __stdcall FileTimeToSystemTime(LPVOID lpFileTime, LPVOID lpSystemTime)", false, false },
    { "kernel32.dll", "SystemTimeToFileTime", "BOOL __stdcall SystemTimeToFileTime(LPVOID lpSystemTime, LPVOID lpFileTime)", false, false },
    { "kernel32.dll", "GetSystemTime", "void __stdcall GetSystemTime(LPVOID lpSystemTime)", false, false },
    { "kernel32.dll", "GetLocalTime", "void __stdcall GetLocalTime(LPVOID lpSystemTime)", false, false },
    { "kernel32.dll", "GetSystemInfo", "void __stdcall GetSystemInfo(LPVOID lpSystemInfo)", false, false },
    { "kernel32.dll", "GetNativeSystemInfo", "void __stdcall GetNativeSystemInfo(LPVOID lpSystemInfo)", false, false },
    { "kernel32.dll", "IsProcessorFeaturePresent", "BOOL __stdcall IsProcessorFeaturePresent(DWORD ProcessorFeature)", false, false },
    { "kernel32.dll", "GetVersionExW", "BOOL __stdcall GetVersionExW(LPVOID lpVersionInformation)", false, false },
    { "kernel32.dll", "GetComputerNameW", "BOOL __stdcall GetComputerNameW(LPWSTR lpBuffer, LPDWORD nSize)", false, false },
    { "kernel32.dll", "ExpandEnvironmentStringsW", "DWORD __stdcall ExpandEnvironmentStringsW(LPCWSTR lpSrc, LPWSTR lpDst, DWORD nSize)", false, false },
    { "kernel32.dll", "GetEnvironmentVariableW", "DWORD __stdcall GetEnvironmentVariableW(LPCWSTR lpName, LPWSTR lpBuffer, DWORD nSize)", false, false },
    { "kernel32.dll", "SetEnvironmentVariableW", "BOOL __stdcall SetEnvironmentVariableW(LPCWSTR lpName, LPCWSTR lpValue)", false, false },
    { "kernel32.dll", "GetCommandLineW", "LPWSTR __stdcall GetCommandLineW(void)", false, false },
    { "kernel32.dll", "GetCommandLineA", "LPSTR __stdcall GetCommandLineA(void)", false, false },
    { "kernel32.dll", "GetStdHandle", "HANDLE __stdcall GetStdHandle(DWORD nStdHandle)", false, false },
    { "kernel32.dll", "SetStdHandle", "BOOL __stdcall SetStdHandle(DWORD nStdHandle, HANDLE hHandle)", false, false },
    { "kernel32.dll", "WriteConsoleW", "BOOL __stdcall WriteConsoleW(HANDLE hConsoleOutput, LPCVOID lpBuffer, DWORD nNumberOfCharsToWrite, LPDWORD lpNumberOfCharsWritten, LPVOID lpReserved)", false, false },
    { "kernel32.dll", "ReadConsoleW", "BOOL __stdcall ReadConsoleW(HANDLE hConsoleInput, LPVOID lpBuffer, DWORD nNumberOfCharsToRead, LPDWORD lpNumberOfCharsRead, LPVOID pInputControl)", false, false },
    { "kernel32.dll", "SetConsoleTitleW", "BOOL __stdcall SetConsoleTitleW(LPCWSTR lpConsoleTitle)", false, false },
    { "kernel32.dll", "AllocConsole", "BOOL __stdcall AllocConsole(void)", false, false },
    { "kernel32.dll", "FreeConsole", "BOOL __stdcall FreeConsole(void)", false, false },
    { "kernel32.dll", "FormatMessageW", "DWORD __stdcall FormatMessageW(DWORD dwFlags, LPCVOID lpSource, DWORD dwMessageId, DWORD dwLanguageId, LPWSTR lpBuffer, DWORD nSize, LPVOID Arguments)", false, false },
    { "kernel32.dll", "FormatMessageA", "DWORD __stdcall FormatMessageA(DWORD dwFlags, LPCVOID lpSource, DWORD dwMessageId, DWORD dwLanguageId, LPSTR lpBuffer, DWORD nSize, LPVOID Arguments)", false, false },
    { "kernel32.dll", "MultiByteToWideChar", "int __stdcall MultiByteToWideChar(UINT CodePage, DWORD dwFlags, LPCSTR lpMultiByteStr, int cbMultiByte, LPWSTR lpWideCharStr, int cchWideChar)", false, false },
    { "kernel32.dll", "WideCharToMultiByte", "int __stdcall WideCharToMultiByte(UINT CodePage, DWORD dwFlags, LPCWSTR lpWideCharStr, int cchWideChar, LPSTR lpMultiByteStr, int cbMultiByte, LPCSTR lpDefaultChar, LPVOID lpUsedDefaultChar)", false, false },
    { "kernel32.dll", "lstrcmpW", "int __stdcall lstrcmpW(LPCWSTR lpString1, LPCWSTR lpString2)", false, false },
    { "kernel32.dll", "lstrcmpA", "int __stdcall lstrcmpA(LPCSTR lpString1, LPCSTR lpString2)", false, false },
    { "kernel32.dll", "lstrcmpiW", "int __stdcall lstrcmpiW(LPCWSTR lpString1, LPCWSTR lpString2)", false, false },
    { "kernel32.dll", "lstrcmpiA", "int __stdcall lstrcmpiA(LPCSTR lpString1, LPCSTR lpString2)", false, false },
    { "kernel32.dll", "lstrlenW", "int __stdcall lstrlenW(LPCWSTR lpString)", false, false },
    { "kernel32.dll", "lstrlenA", "int __stdcall lstrlenA(LPCSTR lpString)", false, false },
    { "kernel32.dll", "lstrcpyW", "LPWSTR __stdcall lstrcpyW(LPWSTR lpString1, LPCWSTR lpString2)", false, false },
    { "kernel32.dll", "lstrcpyA", "LPSTR __stdcall lstrcpyA(LPSTR lpString1, LPCSTR lpString2)", false, false },
    { "kernel32.dll", "lstrcpynW", "LPWSTR __stdcall lstrcpynW(LPWSTR lpString1, LPCWSTR lpString2, int iMaxLength)", false, false },
    { "kernel32.dll", "lstrcatW", "LPWSTR __stdcall lstrcatW(LPWSTR lpString1, LPCWSTR lpString2)", false, false },
    { "kernel32.dll", "lstrcatA", "LPSTR __stdcall lstrcatA(LPSTR lpString1, LPCSTR lpString2)", false, false },
    { "kernel32.dll", "CompareStringW", "int __stdcall CompareStringW(DWORD Locale, DWORD dwCmpFlags, LPCWSTR lpString1, int cchCount1, LPCWSTR lpString2, int cchCount2)", false, false },
    { "kernel32.dll", "GetLocaleInfoW", "int __stdcall GetLocaleInfoW(DWORD Locale, DWORD LCType, LPWSTR lpLCData, int cchData)", false, false },
    { "kernel32.dll", "IsDebuggerPresent", "BOOL __stdcall IsDebuggerPresent(void)", false, false },
    { "kernel32.dll", "DebugBreak", "void __stdcall DebugBreak(void)", false, false },
    { "kernel32.dll", "OutputDebugStringW", "void __stdcall OutputDebugStringW(LPCWSTR lpOutputString)", false, false },
    { "kernel32.dll", "OutputDebugStringA", "void __stdcall OutputDebugStringA(LPCSTR lpOutputString)", false, false },
    { "kernel32.dll", "RaiseException", "void __stdcall RaiseException(DWORD dwExceptionCode, DWORD dwExceptionFlags, DWORD nNumberOfArguments, LPVOID lpArguments)", true, false },
    { "kernel32.dll", "SetUnhandledExceptionFilter", "LPVOID __stdcall SetUnhandledExceptionFilter(LPVOID lpTopLevelExceptionFilter)", false, false },
    { "kernel32.dll", "GetStartupInfoW", "void __stdcall GetStartupInfoW(LPVOID lpStartupInfo)", false, false },
    { "kernel32.dll", "GetSystemDirectoryW", "UINT __stdcall GetSystemDirectoryW(LPWSTR lpBuffer, UINT uSize)", false, false },
    { "kernel32.dll", "GetWindowsDirectoryW", "UINT __stdcall GetWindowsDirectoryW(LPWSTR lpBuffer, UINT uSize)", false, false },
    { "kernel32.dll", "GetFileType", "DWORD __stdcall GetFileType(HANDLE hFile)", false, false },
    { "kernel32.dll", "DeviceIoControl", "BOOL __stdcall DeviceIoControl(HANDLE hDevice, DWORD dwIoControlCode, LPVOID lpInBuffer, DWORD nInBufferSize, LPVOID lpOutBuffer, DWORD nOutBufferSize, LPDWORD lpBytesReturned, LPVOID lpOverlapped)", false, false },
    { "kernel32.dll", "CreateIoCompletionPort", "HANDLE __stdcall CreateIoCompletionPort(HANDLE FileHandle, HANDLE ExistingCompletionPort, ULONG_PTR CompletionKey, DWORD NumberOfConcurrentThreads)", false, false },
    { "kernel32.dll", "GetQueuedCompletionStatus", "BOOL __stdcall GetQueuedCompletionStatus(HANDLE CompletionPort, LPDWORD lpNumberOfBytesTransferred, LPVOID lpCompletionKey, LPVOID lpOverlapped, DWORD dwMilliseconds)", false, false },
    { "kernel32.dll", "PostQueuedCompletionStatus", "BOOL __stdcall PostQueuedCompletionStatus(HANDLE CompletionPort, DWORD dwNumberOfBytesTransferred, ULONG_PTR dwCompletionKey, LPVOID lpOverlapped)", false, false },
    { "kernel32.dll", "GetOverlappedResult", "BOOL __stdcall GetOverlappedResult(HANDLE hFile, LPVOID lpOverlapped, LPDWORD lpNumberOfBytesTransferred, BOOL bWait)", false, false },
    { "kernel32.dll", "CreateNamedPipeW", "HANDLE __stdcall CreateNamedPipeW(LPCWSTR lpName, DWORD dwOpenMode, DWORD dwPipeMode, DWORD nMaxInstances, DWORD nOutBufferSize, DWORD nInBufferSize, DWORD nDefaultTimeOut, LPVOID lpSecurityAttributes)", false, false },
    { "kernel32.dll", "ConnectNamedPipe", "BOOL __stdcall ConnectNamedPipe(HANDLE hNamedPipe, LPVOID lpOverlapped)", false, false },
    { "kernel32.dll", "DisconnectNamedPipe", "BOOL __stdcall DisconnectNamedPipe(HANDLE hNamedPipe)", false, false },
    { "kernel32.dll", "CallNamedPipeW", "BOOL __stdcall CallNamedPipeW(LPCWSTR lpNamedPipeName, LPVOID lpInBuffer, DWORD nInBufferSize, LPVOID lpOutBuffer, DWORD nOutBufferSize, LPDWORD lpBytesRead, DWORD nTimeOut)", false, false },
    { "kernel32.dll", "WaitNamedPipeW", "BOOL __stdcall WaitNamedPipeW(LPCWSTR lpNamedPipeName, DWORD nTimeOut)", false, false },
    { "kernel32.dll", "PeekNamedPipe", "BOOL __stdcall PeekNamedPipe(HANDLE hNamedPipe, LPVOID lpBuffer, DWORD nBufferSize, LPDWORD lpBytesRead, LPDWORD lpTotalBytesAvail, LPDWORD lpBytesLeftThisMessage)", false, false },
    { "kernel32.dll", "TransactNamedPipe", "BOOL __stdcall TransactNamedPipe(HANDLE hNamedPipe, LPVOID lpInBuffer, DWORD nInBufferSize, LPVOID lpOutBuffer, DWORD nOutBufferSize, LPDWORD lpBytesRead, LPVOID lpOverlapped)", false, false },
    { "kernel32.dll", "SetNamedPipeHandleState", "BOOL __stdcall SetNamedPipeHandleState(HANDLE hNamedPipe, LPDWORD lpMode, LPDWORD lpMaxCollectionCount, LPDWORD lpCollectDataTimeout)", false, false },
    { "kernel32.dll", "DuplicateHandle", "BOOL __stdcall DuplicateHandle(HANDLE hSourceProcessHandle, HANDLE hSourceHandle, HANDLE hTargetProcessHandle, LPVOID lpTargetHandle, DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwOptions)", false, false },
    { "kernel32.dll", "GetPriorityClass", "DWORD __stdcall GetPriorityClass(HANDLE hProcess)", false, false },
    { "kernel32.dll", "SetPriorityClass", "BOOL __stdcall SetPriorityClass(HANDLE hProcess, DWORD dwPriorityClass)", false, false },
    { "kernel32.dll", "GetThreadPriority", "int __stdcall GetThreadPriority(HANDLE hThread)", false, false },
    { "kernel32.dll", "SetThreadPriority", "BOOL __stdcall SetThreadPriority(HANDLE hThread, int nPriority)", false, false },
    { "kernel32.dll", "GetProcessTimes", "BOOL __stdcall GetProcessTimes(HANDLE hProcess, LPVOID lpCreationTime, LPVOID lpExitTime, LPVOID lpKernelTime, LPVOID lpUserTime)", false, false },
    { "kernel32.dll", "GetSystemTimes", "BOOL __stdcall GetSystemTimes(LPVOID lpIdleTime, LPVOID lpKernelTime, LPVOID lpUserTime)", false, false },
    { "kernel32.dll", "GlobalMemoryStatusEx", "BOOL __stdcall GlobalMemoryStatusEx(LPVOID lpBuffer)", false, false },
    { "kernel32.dll", "GetLogicalProcessorInformation", "BOOL __stdcall GetLogicalProcessorInformation(LPVOID Buffer, LPDWORD ReturnedLength)", false, false },
    { "kernel32.dll", "SetThreadAffinityMask", "ULONG_PTR __stdcall SetThreadAffinityMask(HANDLE hThread, ULONG_PTR dwThreadAffinityMask)", false, false },
    { "kernel32.dll", "CreateToolhelp32Snapshot", "HANDLE __stdcall CreateToolhelp32Snapshot(DWORD dwFlags, DWORD th32ProcessID)", false, false },
    { "kernel32.dll", "Process32FirstW", "BOOL __stdcall Process32FirstW(HANDLE hSnapshot, LPVOID lppe)", false, false },
    { "kernel32.dll", "Process32NextW", "BOOL __stdcall Process32NextW(HANDLE hSnapshot, LPVOID lppe)", false, false },
    { "kernel32.dll", "Module32FirstW", "BOOL __stdcall Module32FirstW(HANDLE hSnapshot, LPVOID lpme)", false, false },
    { "kernel32.dll", "Module32NextW", "BOOL __stdcall Module32NextW(HANDLE hSnapshot, LPVOID lpme)", false, false },
    { "kernel32.dll", "Thread32First", "BOOL __stdcall Thread32First(HANDLE hSnapshot, LPVOID lpte)", false, false },
    { "kernel32.dll", "Thread32Next", "BOOL __stdcall Thread32Next(HANDLE hSnapshot, LPVOID lpte)", false, false },
    { "kernel32.dll", "TlsAlloc", "DWORD __stdcall TlsAlloc(void)", false, false },
    { "kernel32.dll", "TlsGetValue", "LPVOID __stdcall TlsGetValue(DWORD dwTlsIndex)", false, false },
    { "kernel32.dll", "TlsSetValue", "BOOL __stdcall TlsSetValue(DWORD dwTlsIndex, LPVOID lpTlsValue)", false, false },
    { "kernel32.dll", "TlsFree", "BOOL __stdcall TlsFree(DWORD dwTlsIndex)", false, false },
    { "kernel32.dll", "FlsAlloc", "DWORD __stdcall FlsAlloc(LPVOID lpCallback)", false, false },
    { "kernel32.dll", "FlsGetValue", "LPVOID __stdcall FlsGetValue(DWORD dwFlsIndex)", false, false },
    { "kernel32.dll", "FlsSetValue", "BOOL __stdcall FlsSetValue(DWORD dwFlsIndex, LPVOID lpFlsData)", false, false },
    { "kernel32.dll", "FlsFree", "BOOL __stdcall FlsFree(DWORD dwFlsIndex)", false, false },
    { "kernel32.dll", "InitializeSListHead", "void __stdcall InitializeSListHead(LPVOID ListHead)", false, false },
    { "kernel32.dll", "InterlockedPushEntrySList", "LPVOID __stdcall InterlockedPushEntrySList(LPVOID ListHead, LPVOID ListEntry)", false, false },
    { "kernel32.dll", "InterlockedPopEntrySList", "LPVOID __stdcall InterlockedPopEntrySList(LPVOID ListHead)", false, false },
    { "kernel32.dll", "InterlockedFlushSList", "LPVOID __stdcall InterlockedFlushSList(LPVOID ListHead)", false, false },
    { "kernel32.dll", "QueryDepthSList", "USHORT __stdcall QueryDepthSList(LPVOID ListHead)", false, false },
    { "kernel32.dll", "EncodePointer", "LPVOID __stdcall EncodePointer(LPVOID Ptr)", false, false },
    { "kernel32.dll", "DecodePointer", "LPVOID __stdcall DecodePointer(LPVOID Ptr)", false, false },
    { "kernel32.dll", "GetBinaryTypeW", "BOOL __stdcall GetBinaryTypeW(LPCWSTR lpApplicationName, LPDWORD lpBinaryType)", false, false },
    { "kernel32.dll", "GetLogicalDrives", "DWORD __stdcall GetLogicalDrives(void)", false, false },
    { "kernel32.dll", "GetDriveTypeW", "UINT __stdcall GetDriveTypeW(LPCWSTR lpRootPathName)", false, false },
    { "kernel32.dll", "GetDiskFreeSpaceExW", "BOOL __stdcall GetDiskFreeSpaceExW(LPCWSTR lpDirectoryName, LPVOID lpFreeBytesAvailableToCaller, LPVOID lpTotalNumberOfBytes, LPVOID lpTotalNumberOfFreeBytes)", false, false },
    { "kernel32.dll", "GetVolumeInformationW", "BOOL __stdcall GetVolumeInformationW(LPCWSTR lpRootPathName, LPWSTR lpVolumeNameBuffer, DWORD nVolumeNameSize, LPDWORD lpVolumeSerialNumber, LPDWORD lpMaximumComponentLength, LPDWORD lpFileSystemFlags, LPWSTR lpFileSystemNameBuffer, DWORD nFileSystemNameSize)", false, false },
    { "kernel32.dll", "FindFirstFileW", "HANDLE __stdcall FindFirstFileW(LPCWSTR lpFileName, LPVOID lpFindFileData)", false, false },
    { "kernel32.dll", "FindFirstFileExW", "HANDLE __stdcall FindFirstFileExW(LPCWSTR lpFileName, DWORD fInfoLevelId, LPVOID lpFindFileData, DWORD fSearchOp, LPVOID lpSearchFilter, DWORD dwAdditionalFlags)", false, false },
    { "kernel32.dll", "FindNextFileW", "BOOL __stdcall FindNextFileW(HANDLE hFindFile, LPVOID lpFindFileData)", false, false },
    { "kernel32.dll", "FindClose", "BOOL __stdcall FindClose(HANDLE hFindFile)", false, false },
    { "kernel32.dll", "CopyFileW", "BOOL __stdcall CopyFileW(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName, BOOL bFailIfExists)", false, false },
    { "kernel32.dll", "MoveFileW", "BOOL __stdcall MoveFileW(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName)", false, false },
    { "kernel32.dll", "MoveFileExW", "BOOL __stdcall MoveFileExW(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName, DWORD dwFlags)", false, false },
    { "kernel32.dll", "GetFullPathNameW", "DWORD __stdcall GetFullPathNameW(LPCWSTR lpFileName, DWORD nBufferLength, LPWSTR lpBuffer, LPVOID lpFilePart)", false, false },
    { "kernel32.dll", "GetCurrentDirectoryW", "DWORD __stdcall GetCurrentDirectoryW(DWORD nBufferLength, LPWSTR lpBuffer)", false, false },
    { "kernel32.dll", "SetCurrentDirectoryW", "BOOL __stdcall SetCurrentDirectoryW(LPCWSTR lpPathName)", false, false },
    { "kernel32.dll", "CreateJobObjectW", "HANDLE __stdcall CreateJobObjectW(LPVOID lpJobAttributes, LPCWSTR lpName)", false, false },
    { "kernel32.dll", "AssignProcessToJobObject", "BOOL __stdcall AssignProcessToJobObject(HANDLE hJob, HANDLE hProcess)", false, false },
    { "kernel32.dll", "SetInformationJobObject", "BOOL __stdcall SetInformationJobObject(HANDLE hJob, DWORD JobObjectInformationClass, LPVOID lpJobObjectInformation, DWORD cbJobObjectInformationLength)", false, false },
    { "kernel32.dll", "QueryInformationJobObject", "BOOL __stdcall QueryInformationJobObject(HANDLE hJob, DWORD JobObjectInformationClass, LPVOID lpJobObjectInformation, DWORD cbJobObjectInformationLength, LPDWORD lpReturnLength)", false, false },
    { "kernel32.dll", "TerminateJobObject", "BOOL __stdcall TerminateJobObject(HANDLE hJob, UINT uExitCode)", false, false },
    { "kernel32.dll", "IsWow64Process", "BOOL __stdcall IsWow64Process(HANDLE hProcess, LPVOID Wow64Process)", false, false },
    { "kernel32.dll", "GetProcessId", "DWORD __stdcall GetProcessId(HANDLE Process)", false, false },
    { "kernel32.dll", "GetThreadId", "DWORD __stdcall GetThreadId(HANDLE Thread)", false, false },
    { "kernel32.dll", "GetProcessIdOfThread", "DWORD __stdcall GetProcessIdOfThread(HANDLE Thread)", false, false },
    { "kernel32.dll", "K32GetModuleFileNameExW", "DWORD __stdcall K32GetModuleFileNameExW(HANDLE hProcess, HMODULE hModule, LPWSTR lpFilename, DWORD nSize)", false, false },
    { "kernel32.dll", "K32EnumProcesses", "BOOL __stdcall K32EnumProcesses(LPDWORD lpidProcess, DWORD cb, LPDWORD lpcbNeeded)", false, false },
    { "kernel32.dll", "K32GetProcessMemoryInfo", "BOOL __stdcall K32GetProcessMemoryInfo(HANDLE Process, LPVOID ppsmemCounters, DWORD cb)", false, false },
    { "kernel32.dll", "K32EnumProcessModules", "BOOL __stdcall K32EnumProcessModules(HANDLE hProcess, LPVOID lphModule, DWORD cb, LPDWORD lpcbNeeded)", false, false },
    { "advapi32.dll", "RegOpenKeyExW", "LONG __stdcall RegOpenKeyExW(HKEY hKey, LPCWSTR lpSubKey, DWORD ulOptions, DWORD samDesired, LPVOID phkResult)", false, false },
    { "advapi32.dll", "RegOpenKeyExA", "LONG __stdcall RegOpenKeyExA(HKEY hKey, LPCSTR lpSubKey, DWORD ulOptions, DWORD samDesired, LPVOID phkResult)", false, false },
    { "advapi32.dll", "RegCreateKeyExW", "LONG __stdcall RegCreateKeyExW(HKEY hKey, LPCWSTR lpSubKey, DWORD Reserved, LPWSTR lpClass, DWORD dwOptions, DWORD samDesired, LPVOID lpSecurityAttributes, LPVOID phkResult, LPDWORD lpdwDisposition)", false, false },
    { "advapi32.dll", "RegQueryValueExW", "LONG __stdcall RegQueryValueExW(HKEY hKey, LPCWSTR lpValueName, LPDWORD lpReserved, LPDWORD lpType, LPVOID lpData, LPDWORD lpcbData)", false, false },
    { "advapi32.dll", "RegQueryValueExA", "LONG __stdcall RegQueryValueExA(HKEY hKey, LPCSTR lpValueName, LPDWORD lpReserved, LPDWORD lpType, LPVOID lpData, LPDWORD lpcbData)", false, false },
    { "advapi32.dll", "RegSetValueExW", "LONG __stdcall RegSetValueExW(HKEY hKey, LPCWSTR lpValueName, DWORD Reserved, DWORD dwType, LPVOID lpData, DWORD cbData)", false, false },
    { "advapi32.dll", "RegSetValueExA", "LONG __stdcall RegSetValueExA(HKEY hKey, LPCSTR lpValueName, DWORD Reserved, DWORD dwType, LPVOID lpData, DWORD cbData)", false, false },
    { "advapi32.dll", "RegDeleteValueW", "LONG __stdcall RegDeleteValueW(HKEY hKey, LPCWSTR lpValueName)", false, false },
    { "advapi32.dll", "RegDeleteKeyW", "LONG __stdcall RegDeleteKeyW(HKEY hKey, LPCWSTR lpSubKey)", false, false },
    { "advapi32.dll", "RegCloseKey", "LONG __stdcall RegCloseKey(HKEY hKey)", false, false },
    { "advapi32.dll", "RegEnumKeyExW", "LONG __stdcall RegEnumKeyExW(HKEY hKey, DWORD dwIndex, LPWSTR lpName, LPDWORD lpcchName, LPDWORD lpReserved, LPWSTR lpClass, LPDWORD lpcchClass, LPVOID lpftLastWriteTime)", false, false },
    { "advapi32.dll", "RegEnumValueW", "LONG __stdcall RegEnumValueW(HKEY hKey, DWORD dwIndex, LPWSTR lpValueName, LPDWORD lpcchValueName, LPDWORD lpReserved, LPDWORD lpType, LPVOID lpData, LPDWORD lpcbData)", false, false },
    { "advapi32.dll", "RegNotifyChangeKeyValue", "LONG __stdcall RegNotifyChangeKeyValue(HKEY hKey, BOOL bWatchSubtree, DWORD dwNotifyFilter, HANDLE hEvent, BOOL fAsynchronous)", false, false },
    { "advapi32.dll", "OpenProcessToken", "BOOL __stdcall OpenProcessToken(HANDLE ProcessHandle, DWORD DesiredAccess, LPVOID TokenHandle)", false, false },
    { "advapi32.dll", "OpenThreadToken", "BOOL __stdcall OpenThreadToken(HANDLE ThreadHandle, DWORD DesiredAccess, BOOL OpenAsSelf, LPVOID TokenHandle)", false, false },
    { "advapi32.dll", "GetTokenInformation", "BOOL __stdcall GetTokenInformation(HANDLE TokenHandle, DWORD TokenInformationClass, LPVOID TokenInformation, DWORD TokenInformationLength, LPDWORD ReturnLength)", false, false },
    { "advapi32.dll", "LookupPrivilegeValueW", "BOOL __stdcall LookupPrivilegeValueW(LPCWSTR lpSystemName, LPCWSTR lpName, LPVOID lpLuid)", false, false },
    { "advapi32.dll", "AdjustTokenPrivileges", "BOOL __stdcall AdjustTokenPrivileges(HANDLE TokenHandle, BOOL DisableAllPrivileges, LPVOID NewState, DWORD BufferLength, LPVOID PreviousState, LPDWORD ReturnLength)", false, false },
    { "advapi32.dll", "CryptAcquireContextW", "BOOL __stdcall CryptAcquireContextW(LPVOID phProv, LPCWSTR szContainer, LPCWSTR szProvider, DWORD dwProvType, DWORD dwFlags)", false, false },
    { "advapi32.dll", "CryptReleaseContext", "BOOL __stdcall CryptReleaseContext(ULONG_PTR hProv, DWORD dwFlags)", false, false },
    { "advapi32.dll", "CryptGenRandom", "BOOL __stdcall CryptGenRandom(ULONG_PTR hProv, DWORD dwLen, LPVOID pbBuffer)", false, false },
    { "advapi32.dll", "GetUserNameW", "BOOL __stdcall GetUserNameW(LPWSTR lpBuffer, LPDWORD pcbBuffer)", false, false },
    { "advapi32.dll", "GetUserNameA", "BOOL __stdcall GetUserNameA(LPSTR lpBuffer, LPDWORD pcbBuffer)", false, false },
    { "advapi32.dll", "EventRegister", "ULONG __stdcall EventRegister(LPVOID ProviderId, LPVOID EnableCallback, LPVOID CallbackContext, LPVOID RegHandle)", false, false },
    { "advapi32.dll", "EventUnregister", "ULONG __stdcall EventUnregister(ULONGLONG RegHandle)", false, false },
    { "advapi32.dll", "EventWrite", "ULONG __stdcall EventWrite(ULONGLONG RegHandle, LPVOID EventDescriptor, ULONG UserDataCount, LPVOID UserData)", false, false },
    { "advapi32.dll", "EventActivityIdControl", "ULONG __stdcall EventActivityIdControl(ULONG ControlCode, LPVOID ActivityId)", false, false },
    { "ws2_32.dll", "WSAStartup", "int __stdcall WSAStartup(WORD wVersionRequested, LPVOID lpWSAData)", false, false },
    { "ws2_32.dll", "WSACleanup", "int __stdcall WSACleanup(void)", false, false },
    { "ws2_32.dll", "socket", "ULONG_PTR __stdcall socket(int af, int type, int protocol)", false, false },
    { "ws2_32.dll", "closesocket", "int __stdcall closesocket(ULONG_PTR s)", false, false },
    { "ws2_32.dll", "bind", "int __stdcall bind(ULONG_PTR s, LPVOID name, int namelen)", false, false },
    { "ws2_32.dll", "listen", "int __stdcall listen(ULONG_PTR s, int backlog)", false, false },
    { "ws2_32.dll", "accept", "ULONG_PTR __stdcall accept(ULONG_PTR s, LPVOID addr, LPVOID addrlen)", false, false },
    { "ws2_32.dll", "connect", "int __stdcall connect(ULONG_PTR s, LPVOID name, int namelen)", false, false },
    { "ws2_32.dll", "send", "int __stdcall send(ULONG_PTR s, LPCSTR buf, int len, int flags)", false, false },
    { "ws2_32.dll", "recv", "int __stdcall recv(ULONG_PTR s, LPSTR buf, int len, int flags)", false, false },
    { "ws2_32.dll", "sendto", "int __stdcall sendto(ULONG_PTR s, LPCSTR buf, int len, int flags, LPVOID to, int tolen)", false, false },
    { "ws2_32.dll", "recvfrom", "int __stdcall recvfrom(ULONG_PTR s, LPSTR buf, int len, int flags, LPVOID from, LPVOID fromlen)", false, false },
    { "ws2_32.dll", "shutdown", "int __stdcall shutdown(ULONG_PTR s, int how)", false, false },
    { "ws2_32.dll", "setsockopt", "int __stdcall setsockopt(ULONG_PTR s, int level, int optname, LPCSTR optval, int optlen)", false, false },
    { "ws2_32.dll", "getsockopt", "int __stdcall getsockopt(ULONG_PTR s, int level, int optname, LPSTR optval, LPVOID optlen)", false, false },
    { "ws2_32.dll", "getsockname", "int __stdcall getsockname(ULONG_PTR s, LPVOID name, LPVOID namelen)", false, false },
    { "ws2_32.dll", "getpeername", "int __stdcall getpeername(ULONG_PTR s, LPVOID name, LPVOID namelen)", false, false },
    { "ws2_32.dll", "select", "int __stdcall select(int nfds, LPVOID readfds, LPVOID writefds, LPVOID exceptfds, LPVOID timeout)", false, false },
    { "ws2_32.dll", "ioctlsocket", "int __stdcall ioctlsocket(ULONG_PTR s, LONG cmd, LPVOID argp)", false, false },
    { "ws2_32.dll", "gethostbyname", "LPVOID __stdcall gethostbyname(LPCSTR name)", false, false },
    { "ws2_32.dll", "getaddrinfo", "int __stdcall getaddrinfo(LPCSTR pNodeName, LPCSTR pServiceName, LPVOID pHints, LPVOID ppResult)", false, false },
    { "ws2_32.dll", "freeaddrinfo", "void __stdcall freeaddrinfo(LPVOID pAddrInfo)", false, false },
    { "ws2_32.dll", "getnameinfo", "int __stdcall getnameinfo(LPVOID pAddr, DWORD salen, LPSTR pNodeBuffer, DWORD NodeBufferSize, LPSTR pServiceBuffer, DWORD ServiceBufferSize, int Flags)", false, false },
    { "ws2_32.dll", "inet_addr", "ULONG __stdcall inet_addr(LPCSTR cp)", false, false },
    { "ws2_32.dll", "htons", "USHORT __stdcall htons(USHORT hostshort)", false, false },
    { "ws2_32.dll", "ntohs", "USHORT __stdcall ntohs(USHORT netshort)", false, false },
    { "ws2_32.dll", "htonl", "ULONG __stdcall htonl(ULONG hostlong)", false, false },
    { "ws2_32.dll", "ntohl", "ULONG __stdcall ntohl(ULONG netlong)", false, false },
    { "ws2_32.dll", "WSAGetLastError", "int __stdcall WSAGetLastError(void)", false, false },
    { "ws2_32.dll", "WSASetLastError", "void __stdcall WSASetLastError(int iError)", false, false },
    { "ws2_32.dll", "WSASocketW", "ULONG_PTR __stdcall WSASocketW(int af, int type, int protocol, LPVOID lpProtocolInfo, DWORD g, DWORD dwFlags)", false, false },
    { "ws2_32.dll", "WSASend", "int __stdcall WSASend(ULONG_PTR s, LPVOID lpBuffers, DWORD dwBufferCount, LPDWORD lpNumberOfBytesSent, DWORD dwFlags, LPVOID lpOverlapped, LPVOID lpCompletionRoutine)", false, false },
    { "ws2_32.dll", "WSARecv", "int __stdcall WSARecv(ULONG_PTR s, LPVOID lpBuffers, DWORD dwBufferCount, LPDWORD lpNumberOfBytesRecvd, LPDWORD lpFlags, LPVOID lpOverlapped, LPVOID lpCompletionRoutine)", false, false },
    { "ws2_32.dll", "WSAEventSelect", "int __stdcall WSAEventSelect(ULONG_PTR s, HANDLE hEventObject, LONG lNetworkEvents)", false, false },
    { "ws2_32.dll", "WSACreateEvent", "HANDLE __stdcall WSACreateEvent(void)", false, false },
    { "ws2_32.dll", "WSACloseEvent", "BOOL __stdcall WSACloseEvent(HANDLE hEvent)", false, false },
    { "ws2_32.dll", "WSAResetEvent", "BOOL __stdcall WSAResetEvent(HANDLE hEvent)", false, false },
    { "ws2_32.dll", "WSASetEvent", "BOOL __stdcall WSASetEvent(HANDLE hEvent)", false, false },
    { "ws2_32.dll", "WSAWaitForMultipleEvents", "DWORD __stdcall WSAWaitForMultipleEvents(DWORD cEvents, LPVOID lphEvents, BOOL fWaitAll, DWORD dwTimeout, BOOL fAlertable)", false, false },
    { "ws2_32.dll", "WSAGetOverlappedResult", "BOOL __stdcall WSAGetOverlappedResult(ULONG_PTR s, LPVOID lpOverlapped, LPDWORD lpcbTransfer, BOOL fWait, LPDWORD lpdwFlags)", false, false },
    { "crypt32.dll", "CryptProtectData", "BOOL __stdcall CryptProtectData(LPVOID pDataIn, LPCWSTR szDataDescr, LPVOID pOptionalEntropy, LPVOID pvReserved, LPVOID pPromptStruct, DWORD dwFlags, LPVOID pDataOut)", false, false },
    { "crypt32.dll", "CryptUnprotectData", "BOOL __stdcall CryptUnprotectData(LPVOID pDataIn, LPVOID ppszDataDescr, LPVOID pOptionalEntropy, LPVOID pvReserved, LPVOID pPromptStruct, DWORD dwFlags, LPVOID pDataOut)", false, false },
    { "crypt32.dll", "CertOpenStore", "HANDLE __stdcall CertOpenStore(LPCSTR lpszStoreProvider, DWORD dwEncodingType, ULONG_PTR hCryptProv, DWORD dwFlags, LPCVOID pvPara)", false, false },
    { "crypt32.dll", "CertCloseStore", "BOOL __stdcall CertCloseStore(HANDLE hCertStore, DWORD dwFlags)", false, false },
    { "crypt32.dll", "CertFindCertificateInStore", "LPVOID __stdcall CertFindCertificateInStore(HANDLE hCertStore, DWORD dwCertEncodingType, DWORD dwFindFlags, DWORD dwFindType, LPCVOID pvFindPara, LPVOID pPrevCertContext)", false, false },
    { "crypt32.dll", "CryptStringToBinaryW", "BOOL __stdcall CryptStringToBinaryW(LPCWSTR pszString, DWORD cchString, DWORD dwFlags, LPVOID pbBinary, LPDWORD pcbBinary, LPDWORD pdwSkip, LPDWORD pdwFlags)", false, false },
    { "crypt32.dll", "CryptBinaryToStringW", "BOOL __stdcall CryptBinaryToStringW(LPVOID pbBinary, DWORD cbBinary, DWORD dwFlags, LPWSTR pszString, LPDWORD pcchString)", false, false },
    { "winhttp.dll", "WinHttpOpen", "LPVOID __stdcall WinHttpOpen(LPCWSTR pszAgentW, DWORD dwAccessType, LPCWSTR pszProxyW, LPCWSTR pszProxyBypassW, DWORD dwFlags)", false, false },
    { "winhttp.dll", "WinHttpCloseHandle", "BOOL __stdcall WinHttpCloseHandle(LPVOID hInternet)", false, false },
    { "winhttp.dll", "WinHttpConnect", "LPVOID __stdcall WinHttpConnect(LPVOID hSession, LPCWSTR pswzServerName, WORD nServerPort, DWORD dwReserved)", false, false },
    { "winhttp.dll", "WinHttpOpenRequest", "LPVOID __stdcall WinHttpOpenRequest(LPVOID hConnect, LPCWSTR pwszVerb, LPCWSTR pwszObjectName, LPCWSTR pwszVersion, LPCWSTR pwszReferrer, LPVOID ppwszAcceptTypes, DWORD dwFlags)", false, false },
    { "winhttp.dll", "WinHttpSendRequest", "BOOL __stdcall WinHttpSendRequest(LPVOID hRequest, LPVOID pwszHeaders, DWORD dwHeadersLength, LPVOID lpOptional, DWORD dwOptionalLength, DWORD dwTotalLength, ULONG_PTR dwContext)", false, false },
    { "winhttp.dll", "WinHttpReceiveResponse", "BOOL __stdcall WinHttpReceiveResponse(LPVOID hRequest, LPVOID lpReserved)", false, false },
    { "winhttp.dll", "WinHttpQueryDataAvailable", "BOOL __stdcall WinHttpQueryDataAvailable(LPVOID hRequest, LPDWORD lpdwNumberOfBytesAvailable)", false, false },
    { "winhttp.dll", "WinHttpReadData", "BOOL __stdcall WinHttpReadData(LPVOID hRequest, LPVOID lpBuffer, DWORD dwNumberOfBytesToRead, LPDWORD lpdwNumberOfBytesRead)", false, false },
    { "winhttp.dll", "WinHttpWriteData", "BOOL __stdcall WinHttpWriteData(LPVOID hRequest, LPCVOID lpBuffer, DWORD dwNumberOfBytesToWrite, LPDWORD lpdwNumberOfBytesWritten)", false, false },
    { "winhttp.dll", "WinHttpSetOption", "BOOL __stdcall WinHttpSetOption(LPVOID hInternet, DWORD dwOption, LPVOID lpBuffer, DWORD dwBufferLength)", false, false },
    { "winhttp.dll", "WinHttpQueryOption", "BOOL __stdcall WinHttpQueryOption(LPVOID hInternet, DWORD dwOption, LPVOID lpBuffer, LPDWORD lpdwBufferLength)", false, false },
    { "winhttp.dll", "WinHttpQueryHeaders", "BOOL __stdcall WinHttpQueryHeaders(LPVOID hRequest, DWORD dwInfoLevel, LPCWSTR pwszName, LPVOID lpBuffer, LPDWORD lpdwBufferLength, LPDWORD lpdwIndex)", false, false },
    { "winhttp.dll", "WinHttpAddRequestHeaders", "BOOL __stdcall WinHttpAddRequestHeaders(LPVOID hRequest, LPCWSTR pwszHeaders, DWORD dwHeadersLength, DWORD dwModifiers)", false, false },
    { "winhttp.dll", "WinHttpSetStatusCallback", "LPVOID __stdcall WinHttpSetStatusCallback(LPVOID hInternet, LPVOID lpfnInternetCallback, DWORD dwNotificationFlags, ULONG_PTR dwReserved)", false, false },
    { "winhttp.dll", "WinHttpSetTimeouts", "BOOL __stdcall WinHttpSetTimeouts(LPVOID hInternet, int nResolveTimeout, int nConnectTimeout, int nSendTimeout, int nReceiveTimeout)", false, false },
    { "wininet.dll", "InternetOpenW", "LPVOID __stdcall InternetOpenW(LPCWSTR lpszAgent, DWORD dwAccessType, LPCWSTR lpszProxy, LPCWSTR lpszProxyBypass, DWORD dwFlags)", false, false },
    { "wininet.dll", "InternetConnectW", "LPVOID __stdcall InternetConnectW(LPVOID hInternet, LPCWSTR lpszServerName, WORD nServerPort, LPCWSTR lpszUserName, LPCWSTR lpszPassword, DWORD dwService, DWORD dwFlags, ULONG_PTR dwContext)", false, false },
    { "wininet.dll", "InternetOpenUrlW", "LPVOID __stdcall InternetOpenUrlW(LPVOID hInternet, LPCWSTR lpszUrl, LPCWSTR lpszHeaders, DWORD dwHeadersLength, DWORD dwFlags, ULONG_PTR dwContext)", false, false },
    { "wininet.dll", "InternetReadFile", "BOOL __stdcall InternetReadFile(LPVOID hFile, LPVOID lpBuffer, DWORD dwNumberOfBytesToRead, LPDWORD lpdwNumberOfBytesRead)", false, false },
    { "wininet.dll", "InternetWriteFile", "BOOL __stdcall InternetWriteFile(LPVOID hFile, LPCVOID lpBuffer, DWORD dwNumberOfBytesToWrite, LPDWORD lpdwNumberOfBytesWritten)", false, false },
    { "wininet.dll", "InternetCloseHandle", "BOOL __stdcall InternetCloseHandle(LPVOID hInternet)", false, false },
    { "wininet.dll", "InternetSetOptionW", "BOOL __stdcall InternetSetOptionW(LPVOID hInternet, DWORD dwOption, LPVOID lpBuffer, DWORD dwBufferLength)", false, false },
    { "wininet.dll", "InternetQueryOptionW", "BOOL __stdcall InternetQueryOptionW(LPVOID hInternet, DWORD dwOption, LPVOID lpBuffer, LPDWORD lpdwBufferLength)", false, false },
    { "wininet.dll", "HttpOpenRequestW", "LPVOID __stdcall HttpOpenRequestW(LPVOID hConnect, LPCWSTR lpszVerb, LPCWSTR lpszObjectName, LPCWSTR lpszVersion, LPCWSTR lpszReferrer, LPVOID lplpszAcceptTypes, DWORD dwFlags, ULONG_PTR dwContext)", false, false },
    { "wininet.dll", "HttpSendRequestW", "BOOL __stdcall HttpSendRequestW(LPVOID hRequest, LPCWSTR lpszHeaders, DWORD dwHeadersLength, LPVOID lpOptional, DWORD dwOptionalLength)", false, false },
    { "wininet.dll", "HttpQueryInfoW", "BOOL __stdcall HttpQueryInfoW(LPVOID hRequest, DWORD dwInfoLevel, LPVOID lpBuffer, LPDWORD lpdwBufferLength, LPDWORD lpdwIndex)", false, false },
    { "wininet.dll", "HttpAddRequestHeadersW", "BOOL __stdcall HttpAddRequestHeadersW(LPVOID hRequest, LPCWSTR lpszHeaders, DWORD dwHeadersLength, DWORD dwModifiers)", false, false },
    { "wininet.dll", "InternetSetStatusCallbackW", "LPVOID __stdcall InternetSetStatusCallbackW(LPVOID hInternet, LPVOID lpfnInternetCallback)", false, false },
    { "wininet.dll", "InternetGetLastResponseInfoW", "BOOL __stdcall InternetGetLastResponseInfoW(LPDWORD lpdwError, LPWSTR lpszBuffer, LPDWORD lpdwBufferLength)", false, false },
    { "wininet.dll", "InternetCrackUrlW", "BOOL __stdcall InternetCrackUrlW(LPCWSTR lpszUrl, DWORD dwUrlLength, DWORD dwFlags, LPVOID lpUrlComponents)", false, false },
    { "ole32.dll", "CoInitializeEx", "HRESULT __stdcall CoInitializeEx(LPVOID pvReserved, DWORD dwCoInit)", false, false },
    { "ole32.dll", "CoUninitialize", "void __stdcall CoUninitialize(void)", false, false },
    { "ole32.dll", "CoCreateInstance", "HRESULT __stdcall CoCreateInstance(LPVOID rclsid, LPVOID pUnkOuter, DWORD dwClsContext, LPVOID riid, LPVOID ppv)", false, false },
    { "ole32.dll", "CoTaskMemAlloc", "LPVOID __stdcall CoTaskMemAlloc(SIZE_T cb)", false, false },
    { "ole32.dll", "CoTaskMemFree", "void __stdcall CoTaskMemFree(LPVOID pv)", false, false },
    { "ole32.dll", "CLSIDFromString", "HRESULT __stdcall CLSIDFromString(LPCWSTR lpsz, LPVOID pclsid)", false, false },
    { "shell32.dll", "ShellExecuteW", "HANDLE __stdcall ShellExecuteW(HWND hwnd, LPCWSTR lpOperation, LPCWSTR lpFile, LPCWSTR lpParameters, LPCWSTR lpDirectory, int nShowCmd)", false, false },
    { "shell32.dll", "ShellExecuteExW", "BOOL __stdcall ShellExecuteExW(LPVOID lpExecInfo)", false, false },
    { "shell32.dll", "SHGetFolderPathW", "HRESULT __stdcall SHGetFolderPathW(HWND hwnd, int csidl, HANDLE hToken, DWORD dwFlags, LPWSTR pszPath)", false, false },
    { "shell32.dll", "SHGetKnownFolderPath", "HRESULT __stdcall SHGetKnownFolderPath(LPVOID rfid, DWORD dwFlags, HANDLE hToken, LPVOID ppszPath)", false, false },
    { "user32.dll", "MessageBoxW", "int __stdcall MessageBoxW(HWND hWnd, LPCWSTR lpText, LPCWSTR lpCaption, UINT uType)", false, false },
    { "user32.dll", "MessageBoxA", "int __stdcall MessageBoxA(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType)", false, false },
    { "user32.dll", "GetForegroundWindow", "HWND __stdcall GetForegroundWindow(void)", false, false },
    { "user32.dll", "SetForegroundWindow", "BOOL __stdcall SetForegroundWindow(HWND hWnd)", false, false },
    { "user32.dll", "FindWindowW", "HWND __stdcall FindWindowW(LPCWSTR lpClassName, LPCWSTR lpWindowName)", false, false },
    { "user32.dll", "FindWindowExW", "HWND __stdcall FindWindowExW(HWND hWndParent, HWND hWndChildAfter, LPCWSTR lpszClass, LPCWSTR lpszWindow)", false, false },
    { "user32.dll", "SendMessageW", "LONG_PTR __stdcall SendMessageW(HWND hWnd, UINT Msg, ULONG_PTR wParam, LONG_PTR lParam)", false, false },
    { "user32.dll", "SendMessageA", "LONG_PTR __stdcall SendMessageA(HWND hWnd, UINT Msg, ULONG_PTR wParam, LONG_PTR lParam)", false, false },
    { "user32.dll", "SendMessageTimeoutW", "LONG_PTR __stdcall SendMessageTimeoutW(HWND hWnd, UINT Msg, ULONG_PTR wParam, LONG_PTR lParam, UINT fuFlags, UINT uTimeout, LPVOID lpdwResult)", false, false },
    { "user32.dll", "PostMessageW", "BOOL __stdcall PostMessageW(HWND hWnd, UINT Msg, ULONG_PTR wParam, LONG_PTR lParam)", false, false },
    { "user32.dll", "PostThreadMessageW", "BOOL __stdcall PostThreadMessageW(DWORD idThread, UINT Msg, ULONG_PTR wParam, LONG_PTR lParam)", false, false },
    { "user32.dll", "GetMessageW", "BOOL __stdcall GetMessageW(LPVOID lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax)", false, false },
    { "user32.dll", "PeekMessageW", "BOOL __stdcall PeekMessageW(LPVOID lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax, UINT wRemoveMsg)", false, false },
    { "user32.dll", "WaitMessage", "BOOL __stdcall WaitMessage(void)", false, false },
    { "user32.dll", "TranslateMessage", "BOOL __stdcall TranslateMessage(LPVOID lpMsg)", false, false },
    { "user32.dll", "DispatchMessageW", "LONG_PTR __stdcall DispatchMessageW(LPVOID lpMsg)", false, false },
    { "user32.dll", "CreateWindowExW", "HWND __stdcall CreateWindowExW(DWORD dwExStyle, LPCWSTR lpClassName, LPCWSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu, HINSTANCE hInstance, LPVOID lpParam)", false, false },
    { "user32.dll", "DestroyWindow", "BOOL __stdcall DestroyWindow(HWND hWnd)", false, false },
    { "user32.dll", "ShowWindow", "BOOL __stdcall ShowWindow(HWND hWnd, int nCmdShow)", false, false },
    { "user32.dll", "UpdateWindow", "BOOL __stdcall UpdateWindow(HWND hWnd)", false, false },
    { "user32.dll", "RegisterClassExW", "USHORT __stdcall RegisterClassExW(LPVOID unnamedParam1)", false, false },
    { "user32.dll", "RegisterClassW", "USHORT __stdcall RegisterClassW(LPVOID lpWndClass)", false, false },
    { "user32.dll", "DefWindowProcW", "LONG_PTR __stdcall DefWindowProcW(HWND hWnd, UINT Msg, ULONG_PTR wParam, LONG_PTR lParam)", false, false },
    { "user32.dll", "GetDC", "HDC __stdcall GetDC(HWND hWnd)", false, false },
    { "user32.dll", "ReleaseDC", "int __stdcall ReleaseDC(HWND hWnd, HDC hDC)", false, false },
    { "user32.dll", "GetWindowDC", "HDC __stdcall GetWindowDC(HWND hWnd)", false, false },
    { "user32.dll", "InvalidateRect", "BOOL __stdcall InvalidateRect(HWND hWnd, LPVOID lpRect, BOOL bErase)", false, false },
    { "user32.dll", "GetClientRect", "BOOL __stdcall GetClientRect(HWND hWnd, LPVOID lpRect)", false, false },
    { "user32.dll", "GetWindowRect", "BOOL __stdcall GetWindowRect(HWND hWnd, LPVOID lpRect)", false, false },
    { "user32.dll", "SetWindowPos", "BOOL __stdcall SetWindowPos(HWND hWnd, HWND hWndInsertAfter, int X, int Y, int cx, int cy, UINT uFlags)", false, false },
    { "user32.dll", "GetSystemMetrics", "int __stdcall GetSystemMetrics(int nIndex)", false, false },
    { "user32.dll", "SetTimer", "ULONG_PTR __stdcall SetTimer(HWND hWnd, ULONG_PTR nIDEvent, UINT uElapse, LPVOID lpTimerFunc)", false, false },
    { "user32.dll", "KillTimer", "BOOL __stdcall KillTimer(HWND hWnd, ULONG_PTR uIDEvent)", false, false },
    { "user32.dll", "GetCursorPos", "BOOL __stdcall GetCursorPos(LPVOID lpPoint)", false, false },
    { "user32.dll", "SetCursorPos", "BOOL __stdcall SetCursorPos(int X, int Y)", false, false },
    { "user32.dll", "GetKeyState", "SHORT __stdcall GetKeyState(int nVirtKey)", false, false },
    { "user32.dll", "GetAsyncKeyState", "SHORT __stdcall GetAsyncKeyState(int vKey)", false, false },
    { "user32.dll", "GetKeyboardState", "BOOL __stdcall GetKeyboardState(LPVOID lpKeyState)", false, false },
    { "user32.dll", "MapVirtualKeyW", "UINT __stdcall MapVirtualKeyW(UINT uCode, UINT uMapType)", false, false },
    { "user32.dll", "ToUnicode", "int __stdcall ToUnicode(UINT wVirtKey, UINT wScanCode, LPVOID lpKeyState, LPWSTR pwszBuff, int cchBuff, UINT wFlags)", false, false },
    { "user32.dll", "BeginPaint", "HDC __stdcall BeginPaint(HWND hWnd, LPVOID lpPaint)", false, false },
    { "user32.dll", "EndPaint", "BOOL __stdcall EndPaint(HWND hWnd, LPVOID lpPaint)", false, false },
    { "user32.dll", "SetWindowTextW", "BOOL __stdcall SetWindowTextW(HWND hWnd, LPCWSTR lpString)", false, false },
    { "user32.dll", "GetWindowTextW", "int __stdcall GetWindowTextW(HWND hWnd, LPWSTR lpString, int nMaxCount)", false, false },
    { "user32.dll", "GetWindowTextLengthW", "int __stdcall GetWindowTextLengthW(HWND hWnd)", false, false },
    { "user32.dll", "IsWindow", "BOOL __stdcall IsWindow(HWND hWnd)", false, false },
    { "user32.dll", "IsWindowVisible", "BOOL __stdcall IsWindowVisible(HWND hWnd)", false, false },
    { "user32.dll", "EnableWindow", "BOOL __stdcall EnableWindow(HWND hWnd, BOOL bEnable)", false, false },
    { "user32.dll", "MoveWindow", "BOOL __stdcall MoveWindow(HWND hWnd, int X, int Y, int nWidth, int nHeight, BOOL bRepaint)", false, false },
    { "user32.dll", "ScreenToClient", "BOOL __stdcall ScreenToClient(HWND hWnd, LPVOID lpPoint)", false, false },
    { "user32.dll", "ClientToScreen", "BOOL __stdcall ClientToScreen(HWND hWnd, LPVOID lpPoint)", false, false },
    { "user32.dll", "GetDlgItem", "HWND __stdcall GetDlgItem(HWND hDlg, int nIDDlgItem)", false, false },
    { "user32.dll", "SetDlgItemTextW", "BOOL __stdcall SetDlgItemTextW(HWND hDlg, int nIDDlgItem, LPCWSTR lpString)", false, false },
    { "user32.dll", "GetDlgItemTextW", "UINT __stdcall GetDlgItemTextW(HWND hDlg, int nIDDlgItem, LPWSTR lpString, int cchMax)", false, false },
    { "user32.dll", "SetFocus", "HWND __stdcall SetFocus(HWND hWnd)", false, false },
    { "user32.dll", "GetFocus", "HWND __stdcall GetFocus(void)", false, false },
    { "user32.dll", "SetCapture", "HWND __stdcall SetCapture(HWND hWnd)", false, false },
    { "user32.dll", "ReleaseCapture", "BOOL __stdcall ReleaseCapture(void)", false, false },
    { "user32.dll", "TrackMouseEvent", "BOOL __stdcall TrackMouseEvent(LPVOID lpEventTrack)", false, false },
    { "user32.dll", "ClipCursor", "BOOL __stdcall ClipCursor(LPVOID lpRect)", false, false },
    { "user32.dll", "GetLastInputInfo", "BOOL __stdcall GetLastInputInfo(LPVOID plii)", false, false },
    { "user32.dll", "MsgWaitForMultipleObjectsEx", "DWORD __stdcall MsgWaitForMultipleObjectsEx(DWORD nCount, LPVOID pHandles, DWORD dwMilliseconds, DWORD dwWakeMask, DWORD dwFlags)", false, false },
    { "user32.dll", "MsgWaitForMultipleObjects", "DWORD __stdcall MsgWaitForMultipleObjects(DWORD nCount, LPVOID pHandles, BOOL fWaitAll, DWORD dwMilliseconds, DWORD dwWakeMask)", false, false },
    { "user32.dll", "SetProcessDPIAware", "BOOL __stdcall SetProcessDPIAware(void)", false, false },
    { "user32.dll", "GetDpiForWindow", "UINT __stdcall GetDpiForWindow(HWND hwnd)", false, false },
    { "user32.dll", "GetDpiForSystem", "UINT __stdcall GetDpiForSystem(void)", false, false },
    { "user32.dll", "SystemParametersInfoW", "BOOL __stdcall SystemParametersInfoW(UINT uiAction, UINT uiParam, LPVOID pvParam, UINT fWinIni)", false, false },
    { "user32.dll", "EnumWindows", "BOOL __stdcall EnumWindows(LPVOID lpEnumFunc, LONG_PTR lParam)", false, false },
    { "user32.dll", "EnumChildWindows", "BOOL __stdcall EnumChildWindows(HWND hWndParent, LPVOID lpEnumFunc, LONG_PTR lParam)", false, false },
    { "user32.dll", "GetWindowThreadProcessId", "DWORD __stdcall GetWindowThreadProcessId(HWND hWnd, LPDWORD lpdwProcessId)", false, false },
    { "user32.dll", "AttachThreadInput", "BOOL __stdcall AttachThreadInput(DWORD idAttach, DWORD idAttachTo, BOOL fAttach)", false, false },
    { "user32.dll", "GetClassNameW", "int __stdcall GetClassNameW(HWND hWnd, LPWSTR lpClassName, int nMaxCount)", false, false },
    { "user32.dll", "GetParent", "HWND __stdcall GetParent(HWND hWnd)", false, false },
    { "user32.dll", "SetParent", "HWND __stdcall SetParent(HWND hWndChild, HWND hWndNewParent)", false, false },
    { "user32.dll", "GetWindow", "HWND __stdcall GetWindow(HWND hWnd, UINT uCmd)", false, false },
    { "user32.dll", "GetWindowLongW", "LONG __stdcall GetWindowLongW(HWND hWnd, int nIndex)", false, false },
    { "user32.dll", "SetWindowLongW", "LONG __stdcall SetWindowLongW(HWND hWnd, int nIndex, LONG dwNewLong)", false, false },
    { "user32.dll", "GetWindowLongPtrW", "LONG_PTR __stdcall GetWindowLongPtrW(HWND hWnd, int nIndex)", false, false },
    { "user32.dll", "SetWindowLongPtrW", "LONG_PTR __stdcall SetWindowLongPtrW(HWND hWnd, int nIndex, LONG_PTR dwNewLong)", false, false },
    { "user32.dll", "AdjustWindowRect", "BOOL __stdcall AdjustWindowRect(LPVOID lpRect, DWORD dwStyle, BOOL bMenu)", false, false },
    { "user32.dll", "AdjustWindowRectEx", "BOOL __stdcall AdjustWindowRectEx(LPVOID lpRect, DWORD dwStyle, BOOL bMenu, DWORD dwExStyle)", false, false },
    { "user32.dll", "RedrawWindow", "BOOL __stdcall RedrawWindow(HWND hWnd, LPVOID lprcUpdate, LPVOID hrgnUpdate, UINT flags)", false, false },
    { "user32.dll", "SetLayeredWindowAttributes", "BOOL __stdcall SetLayeredWindowAttributes(HWND hwnd, DWORD crKey, BYTE bAlpha, DWORD dwFlags)", false, false },
    { "user32.dll", "LoadIconW", "LPVOID __stdcall LoadIconW(HINSTANCE hInstance, LPCWSTR lpIconName)", false, false },
    { "user32.dll", "LoadCursorW", "LPVOID __stdcall LoadCursorW(HINSTANCE hInstance, LPCWSTR lpCursorName)", false, false },
    { "user32.dll", "LoadImageW", "LPVOID __stdcall LoadImageW(HINSTANCE hInst, LPCWSTR name, UINT type, int cx, int cy, UINT fuLoad)", false, false },
    { "user32.dll", "LoadStringW", "int __stdcall LoadStringW(HINSTANCE hInstance, UINT uID, LPWSTR lpBuffer, int cchBufferMax)", false, false },
    { "user32.dll", "CreateMenu", "HMENU __stdcall CreateMenu(void)", false, false },
    { "user32.dll", "CreatePopupMenu", "HMENU __stdcall CreatePopupMenu(void)", false, false },
    { "user32.dll", "DestroyMenu", "BOOL __stdcall DestroyMenu(HMENU hMenu)", false, false },
    { "user32.dll", "AppendMenuW", "BOOL __stdcall AppendMenuW(HMENU hMenu, UINT uFlags, ULONG_PTR uIDNewItem, LPCWSTR lpNewItem)", false, false },
    { "user32.dll", "TrackPopupMenu", "BOOL __stdcall TrackPopupMenu(HMENU hMenu, UINT uFlags, int x, int y, int nReserved, HWND hWnd, LPVOID prcRect)", false, false },
    { "user32.dll", "RegisterHotKey", "BOOL __stdcall RegisterHotKey(HWND hWnd, int id, UINT fsModifiers, UINT vk)", false, false },
    { "user32.dll", "UnregisterHotKey", "BOOL __stdcall UnregisterHotKey(HWND hWnd, int id)", false, false },
    { "user32.dll", "OpenClipboard", "BOOL __stdcall OpenClipboard(HWND hWndNewOwner)", false, false },
    { "user32.dll", "CloseClipboard", "BOOL __stdcall CloseClipboard(void)", false, false },
    { "user32.dll", "GetClipboardData", "HANDLE __stdcall GetClipboardData(UINT uFormat)", false, false },
    { "user32.dll", "SetClipboardData", "HANDLE __stdcall SetClipboardData(UINT uFormat, HANDLE hMem)", false, false },
    { "user32.dll", "EmptyClipboard", "BOOL __stdcall EmptyClipboard(void)", false, false },
    { "dwmapi.dll", "DwmExtendFrameIntoClientArea", "HRESULT __stdcall DwmExtendFrameIntoClientArea(HWND hWnd, LPVOID pMarInset)", false, false },
    { "dwmapi.dll", "DwmSetWindowAttribute", "HRESULT __stdcall DwmSetWindowAttribute(HWND hwnd, DWORD dwAttribute, LPCVOID pvAttribute, DWORD cbAttribute)", false, false },
    { "dwmapi.dll", "DwmGetWindowAttribute", "HRESULT __stdcall DwmGetWindowAttribute(HWND hwnd, DWORD dwAttribute, LPVOID pvAttribute, DWORD cbAttribute)", false, false },
    { "dwmapi.dll", "DwmIsCompositionEnabled", "HRESULT __stdcall DwmIsCompositionEnabled(LPVOID pfEnabled)", false, false },
    { "dwmapi.dll", "DwmFlush", "HRESULT __stdcall DwmFlush(void)", false, false },
    { "gdi32.dll", "CreateCompatibleDC", "HDC __stdcall CreateCompatibleDC(HDC hdc)", false, false },
    { "gdi32.dll", "DeleteDC", "BOOL __stdcall DeleteDC(HDC hdc)", false, false },
    { "gdi32.dll", "DeleteObject", "BOOL __stdcall DeleteObject(HGDIOBJ ho)", false, false },
    { "gdi32.dll", "GetDeviceCaps", "int __stdcall GetDeviceCaps(HDC hdc, int index)", false, false },
    { "gdi32.dll", "BitBlt", "BOOL __stdcall BitBlt(HDC hdc, int x, int y, int cx, int cy, HDC hdcSrc, int x1, int y1, DWORD rop)", false, false },
    { "gdi32.dll", "StretchBlt", "BOOL __stdcall StretchBlt(HDC hdcDest, int xDest, int yDest, int wDest, int hDest, HDC hdcSrc, int xSrc, int ySrc, int wSrc, int hSrc, DWORD rop)", false, false },
    { "gdi32.dll", "SetBkMode", "int __stdcall SetBkMode(HDC hdc, int mode)", false, false },
    { "gdi32.dll", "SetTextColor", "DWORD __stdcall SetTextColor(HDC hdc, DWORD color)", false, false },
    { "gdi32.dll", "SetBkColor", "DWORD __stdcall SetBkColor(HDC hdc, DWORD color)", false, false },
    { "gdi32.dll", "CreateSolidBrush", "HBRUSH __stdcall CreateSolidBrush(DWORD color)", false, false },
    { "gdi32.dll", "SelectObject", "HGDIOBJ __stdcall SelectObject(HDC hdc, HGDIOBJ h)", false, false },
    { "gdi32.dll", "GetStockObject", "HGDIOBJ __stdcall GetStockObject(int i)", false, false },
    { "gdi32.dll", "Rectangle", "BOOL __stdcall Rectangle(HDC hdc, int left, int top, int right, int bottom)", false, false },
    { "gdi32.dll", "Ellipse", "BOOL __stdcall Ellipse(HDC hdc, int left, int top, int right, int bottom)", false, false },
    { "gdi32.dll", "TextOutW", "BOOL __stdcall TextOutW(HDC hdc, int x, int y, LPCWSTR lpString, int c)", false, false },
    { "gdi32.dll", "DrawTextW", "int __stdcall DrawTextW(HDC hdc, LPCWSTR lpchText, int cchText, LPVOID lprc, UINT format)", false, false },
    { "gdi32.dll", "GetTextExtentPoint32W", "BOOL __stdcall GetTextExtentPoint32W(HDC hdc, LPCWSTR lpString, int c, LPVOID psizl)", false, false },
    { "gdi32.dll", "CreateDIBSection", "HBITMAP __stdcall CreateDIBSection(HDC hdc, LPVOID lpbmi, UINT usage, LPVOID ppvBits, HANDLE hSection, DWORD offset)", false, false },
    { "gdi32.dll", "SetDIBits", "int __stdcall SetDIBits(HDC hdc, HBITMAP hbm, UINT start, UINT cLines, LPCVOID lpvBits, LPVOID lpbmi, UINT ColorUse)", false, false },
    { "gdi32.dll", "GdiFlush", "BOOL __stdcall GdiFlush(void)", false, false },
    { "gdi32.dll", "CreateFontIndirectW", "LPVOID __stdcall CreateFontIndirectW(LPVOID lplf)", false, false },
    { "gdi32.dll", "CreateCompatibleBitmap", "HBITMAP __stdcall CreateCompatibleBitmap(HDC hdc, int cx, int cy)", false, false },
    { "gdi32.dll", "GetObjectW", "int __stdcall GetObjectW(HGDIOBJ h, int c, LPVOID pv)", false, false },
    { "gdi32.dll", "GetTextMetricsW", "BOOL __stdcall GetTextMetricsW(HDC hdc, LPVOID lptm)", false, false },
    { "gdi32.dll", "SetStretchBltMode", "int __stdcall SetStretchBltMode(HDC hdc, int mode)", false, false },
    { "ntdll.dll", "NtClose", "LONG __stdcall NtClose(HANDLE Handle)", false, false },
    { "ntdll.dll", "NtQuerySystemInformation", "LONG __stdcall NtQuerySystemInformation(ULONG SystemInformationClass, LPVOID SystemInformation, ULONG SystemInformationLength, LPVOID ReturnLength)", false, false },
    { "ntdll.dll", "NtQueryInformationProcess", "LONG __stdcall NtQueryInformationProcess(HANDLE ProcessHandle, DWORD ProcessInformationClass, LPVOID ProcessInformation, ULONG ProcessInformationLength, LPVOID ReturnLength)", false, false },
    { "ntdll.dll", "NtSetInformationThread", "LONG __stdcall NtSetInformationThread(HANDLE ThreadHandle, ULONG ThreadInformationClass, LPVOID ThreadInformation, ULONG ThreadInformationLength)", false, false },
    { "ntdll.dll", "NtQueryInformationThread", "LONG __stdcall NtQueryInformationThread(HANDLE ThreadHandle, ULONG ThreadInformationClass, LPVOID ThreadInformation, ULONG ThreadInformationLength, LPVOID ReturnLength)", false, false },
    { "ntdll.dll", "RtlInitUnicodeString", "void __stdcall RtlInitUnicodeString(LPVOID DestinationString, LPCWSTR SourceString)", false, false },
    { "ntdll.dll", "RtlAllocateHeap", "LPVOID __stdcall RtlAllocateHeap(HANDLE HeapHandle, DWORD Flags, SIZE_T Size)", false, false },
    { "ntdll.dll", "RtlFreeHeap", "BOOL __stdcall RtlFreeHeap(HANDLE HeapHandle, DWORD Flags, LPVOID HeapBase)", false, false },
    { "ntdll.dll", "LdrGetDllHandle", "LONG __stdcall LdrGetDllHandle(LPVOID DllPath, LPVOID DllCharacteristics, LPVOID DllName, LPVOID DllHandle)", false, false },
    { "ntdll.dll", "LdrLoadDll", "LONG __stdcall LdrLoadDll(LPVOID DllPath, LPVOID DllCharacteristics, LPVOID DllName, LPVOID DllHandle)", false, false },
    { "ntdll.dll", "LdrGetProcedureAddress", "LONG __stdcall LdrGetProcedureAddress(LPVOID DllHandle, LPVOID ProcedureName, ULONG ProcedureNumber, LPVOID ProcedureAddress)", false, false },
    { "ntdll.dll", "NtCreateFile", "LONG __stdcall NtCreateFile(LPVOID FileHandle, ULONG DesiredAccess, LPVOID ObjectAttributes, LPVOID IoStatusBlock, LPVOID AllocationSize, ULONG FileAttributes, ULONG ShareAccess, ULONG CreateDisposition, ULONG CreateOptions, LPVOID EaBuffer, ULONG EaLength)", false, false },
    { "ntdll.dll", "NtReadFile", "LONG __stdcall NtReadFile(HANDLE FileHandle, HANDLE Event, LPVOID ApcRoutine, LPVOID ApcContext, LPVOID IoStatusBlock, LPVOID Buffer, ULONG Length, LPVOID ByteOffset, LPVOID Key)", false, false },
    { "ntdll.dll", "NtWriteFile", "LONG __stdcall NtWriteFile(HANDLE FileHandle, HANDLE Event, LPVOID ApcRoutine, LPVOID ApcContext, LPVOID IoStatusBlock, LPVOID Buffer, ULONG Length, LPVOID ByteOffset, LPVOID Key)", false, false },
    { "version.dll", "GetFileVersionInfoSizeW", "DWORD __stdcall GetFileVersionInfoSizeW(LPCWSTR lptstrFilename, LPDWORD lpdwHandle)", false, false },
    { "version.dll", "GetFileVersionInfoW", "BOOL __stdcall GetFileVersionInfoW(LPCWSTR lptstrFilename, DWORD dwHandle, DWORD dwLen, LPVOID lpData)", false, false },
    { "version.dll", "VerQueryValueW", "BOOL __stdcall VerQueryValueW(LPCVOID pBlock, LPCWSTR lpSubBlock, LPVOID lplpBuffer, LPVOID puLen)", false, false },
    { "dbghelp.dll", "SymInitialize", "BOOL __stdcall SymInitialize(HANDLE hProcess, LPCSTR UserSearchPath, BOOL fInvadeProcess)", false, false },
    { "dbghelp.dll", "SymFromAddr", "BOOL __stdcall SymFromAddr(HANDLE hProcess, ULONGLONG Address, LPVOID Displacement, LPVOID Symbol)", false, false },
    { "dbghelp.dll", "SymCleanup", "BOOL __stdcall SymCleanup(HANDLE hProcess)", false, false },
    { "crt", "malloc", "LPVOID __cdecl malloc(SIZE_T size)", false, true },
    { "crt", "calloc", "LPVOID __cdecl calloc(SIZE_T num, SIZE_T size)", false, true },
    { "crt", "realloc", "LPVOID __cdecl realloc(LPVOID ptr, SIZE_T size)", false, true },
    { "crt", "free", "void __cdecl free(LPVOID ptr)", false, true },
    { "crt", "_aligned_malloc", "LPVOID __cdecl _aligned_malloc(SIZE_T size, SIZE_T alignment)", false, true },
    { "crt", "_aligned_realloc", "LPVOID __cdecl _aligned_realloc(LPVOID ptr, SIZE_T size, SIZE_T alignment)", false, true },
    { "crt", "_aligned_free", "void __cdecl _aligned_free(LPVOID ptr)", false, true },
    { "crt", "_msize", "SIZE_T __cdecl _msize(LPVOID ptr)", false, true },
    { "crt", "memcpy", "LPVOID __cdecl memcpy(LPVOID dest, LPCVOID src, SIZE_T count)", false, true },
    { "crt", "memmove", "LPVOID __cdecl memmove(LPVOID dest, LPCVOID src, SIZE_T count)", false, true },
    { "crt", "memset", "LPVOID __cdecl memset(LPVOID dest, int c, SIZE_T count)", false, true },
    { "crt", "memcmp", "int __cdecl memcmp(LPCVOID lhs, LPCVOID rhs, SIZE_T count)", false, true },
    { "crt", "memchr", "LPVOID __cdecl memchr(LPCVOID ptr, int ch, SIZE_T count)", false, true },
    { "crt", "strcpy", "LPSTR __cdecl strcpy(LPSTR dest, LPCSTR src)", false, true },
    { "crt", "strncpy", "LPSTR __cdecl strncpy(LPSTR dest, LPCSTR src, SIZE_T count)", false, true },
    { "crt", "strcat", "LPSTR __cdecl strcat(LPSTR dest, LPCSTR src)", false, true },
    { "crt", "strncat", "LPSTR __cdecl strncat(LPSTR dest, LPCSTR src, SIZE_T count)", false, true },
    { "crt", "strcmp", "int __cdecl strcmp(LPCSTR lhs, LPCSTR rhs)", false, true },
    { "crt", "strncmp", "int __cdecl strncmp(LPCSTR lhs, LPCSTR rhs, SIZE_T count)", false, true },
    { "crt", "strlen", "SIZE_T __cdecl strlen(LPCSTR str)", false, true },
    { "crt", "strnlen", "SIZE_T __cdecl strnlen(LPCSTR str, SIZE_T count)", false, true },
    { "crt", "strchr", "LPSTR __cdecl strchr(LPCSTR str, int ch)", false, true },
    { "crt", "strrchr", "LPSTR __cdecl strrchr(LPCSTR str, int ch)", false, true },
    { "crt", "strstr", "LPSTR __cdecl strstr(LPCSTR str, LPCSTR substr)", false, true },
    { "crt", "_stricmp", "int __cdecl _stricmp(LPCSTR lhs, LPCSTR rhs)", false, true },
    { "crt", "_strnicmp", "int __cdecl _strnicmp(LPCSTR lhs, LPCSTR rhs, SIZE_T count)", false, true },
    { "crt", "_strdup", "LPSTR __cdecl _strdup(LPCSTR src)", false, true },
    { "crt", "strcpy_s", "int __cdecl strcpy_s(LPSTR dest, SIZE_T destsz, LPCSTR src)", false, true },
    { "crt", "strncpy_s", "int __cdecl strncpy_s(LPSTR dest, SIZE_T destsz, LPCSTR src, SIZE_T count)", false, true },
    { "crt", "strcat_s", "int __cdecl strcat_s(LPSTR dest, SIZE_T destsz, LPCSTR src)", false, true },
    { "crt", "sprintf_s", "int __cdecl sprintf_s(LPSTR buffer, SIZE_T sizeOfBuffer, LPCSTR format, ...)", false, true },
    { "crt", "snprintf", "int __cdecl snprintf(LPSTR buffer, SIZE_T sizeOfBuffer, LPCSTR format, ...)", false, true },
    { "crt", "_snprintf_s", "int __cdecl _snprintf_s(LPSTR buffer, SIZE_T sizeOfBuffer, SIZE_T count, LPCSTR format, ...)", false, true },
    { "crt", "vsnprintf", "int __cdecl vsnprintf(LPSTR buffer, SIZE_T sizeOfBuffer, LPCSTR format, ULONG_PTR va)", false, true },
    { "crt", "printf", "int __cdecl printf(LPCSTR format, ...)", false, true },
    { "crt", "fprintf", "int __cdecl fprintf(LPVOID stream, LPCSTR format, ...)", false, true },
    { "crt", "sprintf", "int __cdecl sprintf(LPSTR buffer, LPCSTR format, ...)", false, true },
    { "crt", "sscanf", "int __cdecl sscanf(LPCSTR buffer, LPCSTR format, ...)", false, true },
    { "crt", "puts", "int __cdecl puts(LPCSTR str)", false, true },
    { "crt", "putchar", "int __cdecl putchar(int ch)", false, true },
    { "crt", "wcscpy", "LPWSTR __cdecl wcscpy(LPWSTR dest, LPCWSTR src)", false, true },
    { "crt", "wcsncpy", "LPWSTR __cdecl wcsncpy(LPWSTR dest, LPCWSTR src, SIZE_T count)", false, true },
    { "crt", "wcscat", "LPWSTR __cdecl wcscat(LPWSTR dest, LPCWSTR src)", false, true },
    { "crt", "wcsncat", "LPWSTR __cdecl wcsncat(LPWSTR dest, LPCWSTR src, SIZE_T count)", false, true },
    { "crt", "wcscmp", "int __cdecl wcscmp(LPCWSTR lhs, LPCWSTR rhs)", false, true },
    { "crt", "wcsncmp", "int __cdecl wcsncmp(LPCWSTR lhs, LPCWSTR rhs, SIZE_T count)", false, true },
    { "crt", "wcslen", "SIZE_T __cdecl wcslen(LPCWSTR str)", false, true },
    { "crt", "wcsnlen", "SIZE_T __cdecl wcsnlen(LPCWSTR str, SIZE_T count)", false, true },
    { "crt", "wcschr", "LPWSTR __cdecl wcschr(LPCWSTR str, unsigned short ch)", false, true },
    { "crt", "wcsrchr", "LPWSTR __cdecl wcsrchr(LPCWSTR str, unsigned short ch)", false, true },
    { "crt", "wcsstr", "LPWSTR __cdecl wcsstr(LPCWSTR str, LPCWSTR substr)", false, true },
    { "crt", "_wcsicmp", "int __cdecl _wcsicmp(LPCWSTR lhs, LPCWSTR rhs)", false, true },
    { "crt", "_wcsnicmp", "int __cdecl _wcsnicmp(LPCWSTR lhs, LPCWSTR rhs, SIZE_T count)", false, true },
    { "crt", "_wcsdup", "LPWSTR __cdecl _wcsdup(LPCWSTR src)", false, true },
    { "crt", "wcscpy_s", "int __cdecl wcscpy_s(LPWSTR dest, SIZE_T destsz, LPCWSTR src)", false, true },
    { "crt", "wcsncpy_s", "int __cdecl wcsncpy_s(LPWSTR dest, SIZE_T destsz, LPCWSTR src, SIZE_T count)", false, true },
    { "crt", "wcscat_s", "int __cdecl wcscat_s(LPWSTR dest, SIZE_T destsz, LPCWSTR src)", false, true },
    { "crt", "swprintf_s", "int __cdecl swprintf_s(LPWSTR buffer, SIZE_T sizeOfBuffer, LPCWSTR format, ...)", false, true },
    { "crt", "_snwprintf_s", "int __cdecl _snwprintf_s(LPWSTR buffer, SIZE_T sizeOfBuffer, SIZE_T count, LPCWSTR format, ...)", false, true },
    { "crt", "wprintf", "int __cdecl wprintf(LPCWSTR format, ...)", false, true },
    { "crt", "fwprintf", "int __cdecl fwprintf(LPVOID stream, LPCWSTR format, ...)", false, true },
    { "crt", "fopen", "LPVOID __cdecl fopen(LPCSTR filename, LPCSTR mode)", false, true },
    { "crt", "_wfopen", "LPVOID __cdecl _wfopen(LPCWSTR filename, LPCWSTR mode)", false, true },
    { "crt", "fopen_s", "int __cdecl fopen_s(LPVOID pFile, LPCSTR filename, LPCSTR mode)", false, true },
    { "crt", "_wfopen_s", "int __cdecl _wfopen_s(LPVOID pFile, LPCWSTR filename, LPCWSTR mode)", false, true },
    { "crt", "fclose", "int __cdecl fclose(LPVOID stream)", false, true },
    { "crt", "fread", "SIZE_T __cdecl fread(LPVOID buffer, SIZE_T size, SIZE_T count, LPVOID stream)", false, true },
    { "crt", "fwrite", "SIZE_T __cdecl fwrite(LPCVOID buffer, SIZE_T size, SIZE_T count, LPVOID stream)", false, true },
    { "crt", "fseek", "int __cdecl fseek(LPVOID stream, LONG offset, int origin)", false, true },
    { "crt", "_fseeki64", "int __cdecl _fseeki64(LPVOID stream, __int64 offset, int origin)", false, true },
    { "crt", "ftell", "LONG __cdecl ftell(LPVOID stream)", false, true },
    { "crt", "_ftelli64", "__int64 __cdecl _ftelli64(LPVOID stream)", false, true },
    { "crt", "fflush", "int __cdecl fflush(LPVOID stream)", false, true },
    { "crt", "fgets", "LPSTR __cdecl fgets(LPSTR buffer, int count, LPVOID stream)", false, true },
    { "crt", "fputs", "int __cdecl fputs(LPCSTR str, LPVOID stream)", false, true },
    { "crt", "fgetc", "int __cdecl fgetc(LPVOID stream)", false, true },
    { "crt", "fputc", "int __cdecl fputc(int ch, LPVOID stream)", false, true },
    { "crt", "remove", "int __cdecl remove(LPCSTR filename)", false, true },
    { "crt", "_wremove", "int __cdecl _wremove(LPCWSTR filename)", false, true },
    { "crt", "rename", "int __cdecl rename(LPCSTR oldname, LPCSTR newname)", false, true },
    { "crt", "atoi", "int __cdecl atoi(LPCSTR str)", false, true },
    { "crt", "atol", "LONG __cdecl atol(LPCSTR str)", false, true },
    { "crt", "atoll", "LONGLONG __cdecl atoll(LPCSTR str)", false, true },
    { "crt", "atof", "double __cdecl atof(LPCSTR str)", false, true },
    { "crt", "strtol", "LONG __cdecl strtol(LPCSTR str, LPVOID endptr, int base)", false, true },
    { "crt", "strtoul", "ULONG __cdecl strtoul(LPCSTR str, LPVOID endptr, int base)", false, true },
    { "crt", "strtoll", "LONGLONG __cdecl strtoll(LPCSTR str, LPVOID endptr, int base)", false, true },
    { "crt", "strtoull", "ULONGLONG __cdecl strtoull(LPCSTR str, LPVOID endptr, int base)", false, true },
    { "crt", "strtod", "double __cdecl strtod(LPCSTR str, LPVOID endptr)", false, true },
    { "crt", "wcstol", "LONG __cdecl wcstol(LPCWSTR str, LPVOID endptr, int base)", false, true },
    { "crt", "rand", "int __cdecl rand(void)", false, true },
    { "crt", "srand", "void __cdecl srand(UINT seed)", false, true },
    { "crt", "qsort", "void __cdecl qsort(LPVOID base, SIZE_T num, SIZE_T size, LPVOID compar)", false, true },
    { "crt", "bsearch", "LPVOID __cdecl bsearch(LPCVOID key, LPCVOID base, SIZE_T num, SIZE_T size, LPVOID compar)", false, true },
    { "crt", "exit", "void __cdecl exit(int status)", true, true },
    { "crt", "_exit", "void __cdecl _exit(int status)", true, true },
    { "crt", "quick_exit", "void __cdecl quick_exit(int status)", true, true },
    { "crt", "abort", "void __cdecl abort(void)", true, true },
    { "crt", "_cexit", "void __cdecl _cexit(void)", true, true },
    { "crt", "_c_exit", "void __cdecl _c_exit(void)", true, true },
    { "crt", "_wassert", "void __cdecl _wassert(LPCWSTR expr, LPCWSTR filename, UINT lineno)", true, true },
    { "crt", "_purecall", "int __cdecl _purecall(void)", true, true },
    { "crt", "_beginthread", "ULONG_PTR __cdecl _beginthread(LPVOID start_address, UINT stack_size, LPVOID arglist)", false, true },
    { "crt", "_beginthreadex", "ULONG_PTR __cdecl _beginthreadex(LPVOID security, UINT stack_size, LPVOID start_address, LPVOID arglist, UINT initflag, LPVOID thrdaddr)", false, true },
    { "crt", "_endthread", "void __cdecl _endthread(void)", true, true },
    { "crt", "_endthreadex", "void __cdecl _endthreadex(UINT retval)", true, true },
    { "crt", "_errno", "LPVOID __cdecl _errno(void)", false, true },
    { "crt", "__errno", "LPVOID __cdecl __errno(void)", false, true },
    { "crt", "isalpha", "int __cdecl isalpha(int c)", false, true },
    { "crt", "isdigit", "int __cdecl isdigit(int c)", false, true },
    { "crt", "isspace", "int __cdecl isspace(int c)", false, true },
    { "crt", "isupper", "int __cdecl isupper(int c)", false, true },
    { "crt", "islower", "int __cdecl islower(int c)", false, true },
    { "crt", "isalnum", "int __cdecl isalnum(int c)", false, true },
    { "crt", "isxdigit", "int __cdecl isxdigit(int c)", false, true },
    { "crt", "isprint", "int __cdecl isprint(int c)", false, true },
    { "crt", "iscntrl", "int __cdecl iscntrl(int c)", false, true },
    { "crt", "toupper", "int __cdecl toupper(int c)", false, true },
    { "crt", "tolower", "int __cdecl tolower(int c)", false, true },
    { "crt", "iswalpha", "int __cdecl iswalpha(unsigned short c)", false, true },
    { "crt", "iswdigit", "int __cdecl iswdigit(unsigned short c)", false, true },
    { "crt", "iswspace", "int __cdecl iswspace(unsigned short c)", false, true },
    { "crt", "towupper", "unsigned short __cdecl towupper(unsigned short c)", false, true },
    { "crt", "towlower", "unsigned short __cdecl towlower(unsigned short c)", false, true },
    { "crt", "floor", "double __cdecl floor(double x)", false, true },
    { "crt", "ceil", "double __cdecl ceil(double x)", false, true },
    { "crt", "sqrt", "double __cdecl sqrt(double x)", false, true },
    { "crt", "pow", "double __cdecl pow(double x, double y)", false, true },
    { "crt", "exp", "double __cdecl exp(double x)", false, true },
    { "crt", "log", "double __cdecl log(double x)", false, true },
    { "crt", "log2", "double __cdecl log2(double x)", false, true },
    { "crt", "log10", "double __cdecl log10(double x)", false, true },
    { "crt", "fabs", "double __cdecl fabs(double x)", false, true },
    { "crt", "fmod", "double __cdecl fmod(double x, double y)", false, true },
    { "crt", "sin", "double __cdecl sin(double x)", false, true },
    { "crt", "cos", "double __cdecl cos(double x)", false, true },
    { "crt", "tan", "double __cdecl tan(double x)", false, true },
    { "crt", "atan2", "double __cdecl atan2(double y, double x)", false, true },
    { "crt", "round", "double __cdecl round(double x)", false, true },
    { "crt", "time", "__int64 __cdecl time(LPVOID timer)", false, true },
    { "crt", "clock", "LONG __cdecl clock(void)", false, true },
    { "crt", "localtime", "LPVOID __cdecl localtime(LPVOID timer)", false, true },
    { "crt", "gmtime", "LPVOID __cdecl gmtime(LPVOID timer)", false, true },
    { "crt", "mktime", "__int64 __cdecl mktime(LPVOID timeptr)", false, true },
    { "crt", "difftime", "double __cdecl difftime(__int64 time1, __int64 time2)", false, true },
    { "crt", "strftime", "SIZE_T __cdecl strftime(LPSTR str, SIZE_T maxsize, LPCSTR format, LPVOID timeptr)", false, true },
    { "crt", "strerror", "LPSTR __cdecl strerror(int errnum)", false, true },
    { "crt", "_strerror", "LPSTR __cdecl _strerror(LPCSTR strErrMsg)", false, true },
    { "crt", "_wcserror", "LPWSTR __cdecl _wcserror(int errnum)", false, true },
    { "crt", "perror", "void __cdecl perror(LPCSTR str)", false, true },
    { "crt", "abs", "int __cdecl abs(int n)", false, true },
    { "crt", "labs", "LONG __cdecl labs(LONG n)", false, true },
    { "crt", "llabs", "LONGLONG __cdecl llabs(LONGLONG n)", false, true },
    { "crt", "_byteswap64", "ULONGLONG __cdecl _byteswap64(ULONGLONG value)", false, true },
    { "crt", "_byteswap_ulong", "ULONG __cdecl _byteswap_ulong(ULONG value)", false, true },
    { "crt", "_byteswap_ushort", "USHORT __cdecl _byteswap_ushort(USHORT value)", false, true },
};

struct api_prototype_t {
    std::string_view signature;
    bool is_noreturn = false;
};

inline bool iequals(std::string_view left, std::string_view right) noexcept
{
    if (left.size() != right.size())
        return false;
    for (std::size_t index = 0; index < left.size(); ++index) {
        const auto fold = [](char c) {
            return (c >= 'A' && c <= 'Z') ? static_cast<char>(c - 'A' + 'a') : c;
        };
        if (fold(left[index]) != fold(right[index]))
            return false;
    }
    return true;
}

inline std::string_view normalized_module(std::string_view module) noexcept
{
    if (module.size() > 4 && iequals(module.substr(module.size() - 4), ".dll"))
        module = module.substr(0, module.size() - 4);
    return module;
}

inline bool module_is_crt(std::string_view module) noexcept
{
    module = normalized_module(module);
    if (iequals(module, "msvcrt") || iequals(module, "ucrtbase") ||
        iequals(module, "msvcr100") || iequals(module, "msvcr110") ||
        iequals(module, "msvcr120") || iequals(module, "msvcr90") ||
        iequals(module, "msvcp140") || iequals(module, "vcruntime140") ||
        iequals(module, "vcruntime140_1"))
        return true;
    return module.size() > 12 && iequals(module.substr(0, 12), "api-ms-win-crt");
}

inline std::optional<api_prototype_t> find(std::string_view module, std::string_view name) noexcept
{
    if (name.empty() || name.size() > 256 || module.empty() || module.size() > 260)
        return std::nullopt;
    const std::string_view base = normalized_module(module);
    for (const auto& entry : k_entries) {
        if (entry.is_crt || !entry.signature || entry.signature[0] == '\0')
            continue;
        if (name != entry.name)
            continue;
        std::string_view entry_module = normalized_module(entry.module);
        if (iequals(base, entry_module))
            return api_prototype_t{entry.signature, entry.is_noreturn};
    }
    if (!module_is_crt(module))
        return std::nullopt;
    for (const auto& entry : k_entries) {
        if (!entry.is_crt || !entry.signature || entry.signature[0] == '\0')
            continue;
        if (name == entry.name)
            return api_prototype_t{entry.signature, entry.is_noreturn};
    }
    return std::nullopt;
}

}
