BEGIN;

ALTER TABLE builds ADD COLUMN IF NOT EXISTS expected_wbaes_table_hash VARCHAR(64) NOT NULL DEFAULT '';

ALTER TABLE sessions ADD COLUMN IF NOT EXISTS wbaes_table_hash VARCHAR(64);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS fallback_mode INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS fallback_count INTEGER NOT NULL DEFAULT 0;

COMMIT;
