#include "../settings/standalone_compat.hpp"
#include "../re/dx_hook.hpp"
#include "../re/vmt.hpp"
#include "../re/rtti.hpp"
#include "../re/encptr.hpp"
#include "../re/offsets.hpp"
#include "../re/heap_track.hpp"
#include "../re/sigs.hpp"
#include "../re/struct_adv.hpp"

namespace re_tools
{
void register_re_tools(mcp_standalone::server_t& srv)
{
    register_compat(srv, {"dx_find_device_vtable", "re.dx_hook",
        "Report D3D/DXGI COM hook targets and Vulkan loader/export evidence; Vulkan rows stay unvalidated without live dispatch-pointer proof.",
        {{"api", "string", "auto|d3d11|d3d12|dxgi|vulkan", false},
         {"process_id", "number", "Target process id", false},
         {"fixture_vtable_va", "string", "Static fixture vtable address", false},
         {"fixture_slot_names_va", "string", "Static fixture slot-name array address", false},
         {"fixture_slot_addresses_va", "string", "Static fixture slot-address array address", false},
         {"fixture_slot_count", "number", "Static fixture slot count", false}},
        re::dx_hook::find_device_vtable, true});

    register_compat(srv, {"dx_hook_manage", "re.dx_hook",
        "Manage DirectX/DXGI hooks and only validated Vulkan dispatch targets. HWBP uses kernel thread-context evidence; VMT patch requires a proven COM vtable and callback. Action 'full_capture' arms Present+Draw+CBufferBind HWBPs simultaneously.",
        {{"action", "string", "draw|present|full_capture|remove", true},
         {"process_id", "number", "Target process id", true},
         {"api", "string", "auto|d3d11|d3d12|dxgi|vulkan", false},
         {"capture_cbuffers", "boolean", "Capture constant-buffer metadata when bind-call context or explicit fallback evidence is available", false},
         {"capture_vertex_buffers", "boolean", "Capture vertex-buffer metadata from live IASetVertexBuffers context; no snapshot fallback", false},
         {"max_captures", "number", "Maximum captures to retain", false},
         {"hw_slot", "number", "Hardware breakpoint register slot", false},
         {"callback_mode", "string", "hw_bp|hwbp|hardware_breakpoint|kernel_context|vmt_patch", false},
         {"callback_va", "string", "Executable target-process callback for vmt_patch", false},
         {"vtable_va", "string", "Target COM vtable for vmt_patch", false},
         {"object_va", "string", "Optional object address for VMT patch-object mode", false},
         {"vmt_method", "string", "patch_vtable|patch_object", false},
         {"confirm_unsafe", "boolean", "Required for hook installation/removal", false},
         {"allow_unsafe", "boolean", "Alias of confirm_unsafe", false}},
        re::dx_hook::hook_manage, false});

    register_compat(srv, {"dx_list_bound_cbuffers", "re.dx_hook",
        "List constant buffers captured by active kernel-backed DX hook bind contexts. Snapshot/explicit candidates are opt-in diagnostic evidence only.",
        {{"process_id", "number", "Target process id", true},
         {"api", "string", "Optional API filter", false},
         {"include_snapshot_fallback", "boolean", "Opt in to bounded diagnostic candidates; false keeps output kernel live-bind only", false},
         {"matrix_buffer_va", "string", "Explicit matrix/cbuffer candidate VA", false},
         {"cbuffer_va", "string", "Explicit cbuffer candidate VA", false},
         {"candidates", "array", "Explicit candidate objects", false}},
        re::dx_hook::list_bound_cbuffers, true});

    register_compat(srv, {"dx_identify_bone_buffer", "re.dx_hook",
        "Report bone-palette buffer candidates across multiple formats: 4x4/3x4 matrices, quaternion+position, dual quaternion, SRT (scale-rotation-translation), padded 3x4, and interleaved structures; this does not prove skeleton hierarchy or model ownership.",
        {{"process_id", "number", "Target process id", true},
         {"world_unit_max", "number", "Maximum plausible translation component", false},
         {"min_bones", "number", "Minimum matrix count", false},
         {"max_bones", "number", "Maximum matrix count", false},
         {"allow_memory_fallback", "boolean", "Opt in to bounded readable-memory fallback; false uses captured or explicit candidates only", false},
         {"matrix_buffer_va", "string", "Explicit matrix buffer VA", false},
         {"candidate_va", "string", "Explicit candidate VA", false},
         {"candidates", "array", "Explicit candidate objects", false}},
        re::dx_hook::identify_bone_buffer, true});

    register_compat(srv, {"dx_map_resource_to_va", "re.dx_hook",
        "Walk a D3D resource object or CBV descriptor for CPU-readable backing pointers, COM vtable evidence, and unproven GPU VA candidates.",
        {{"resource_handle", "string", "Resource object or descriptor address", true},
         {"descriptor_handle", "string", "Alias for descriptor address", false},
         {"cbv_descriptor_va", "string", "Alias for CBV descriptor address", false},
         {"resource_va", "string", "Alias for resource object address", false},
         {"process_id", "number", "Target process id", true},
         {"max_candidates", "number", "Maximum pointer candidates", false}},
        re::dx_hook::map_resource_to_va, true});

    register_compat(srv, {"dx_dump_render_targets", "re.dx_hook",
        "Attempt kernel-backed GPU render-target readback and fail closed when no kernel/in-process GPU readback backend is available.",
        {{"process_id", "number", "Target process id", true},
         {"format", "string", "rgba|png", false},
         {"output_path", "string", "Optional output path", false},
         {"allow_window_fallback", "boolean", "When true, captures the target window via PrintWindow/BitBlt as a GDI screenshot fallback", false},
         {"confirm_unsafe", "boolean", "Required when writing files or installing capture callbacks", false},
         {"allow_unsafe", "boolean", "Alias of confirm_unsafe", false}},
        re::dx_hook::dump_render_targets, false});

    register_compat(srv, {"dx_find_view_matrix", "re.dx_hook",
        "Report plausible view/projection/view-projection matrix candidates with determinant, inverse, row-column, and identity-null rejection evidence.",
        {{"process_id", "number", "Target process id", true},
         {"scan_cbuffers_only", "boolean", "Restrict to captured constant buffers", false},
         {"allow_memory_fallback", "boolean", "Opt in to bounded readable-memory fallback; false uses captured or explicit candidates only", false},
         {"world_unit_max", "number", "Maximum plausible translation component", false},
         {"matrix_buffer_va", "string", "Explicit matrix buffer VA", false},
         {"candidate_va", "string", "Explicit candidate VA", false},
         {"candidates", "array", "Explicit candidate objects", false}},
        re::dx_hook::find_view_matrix, true});

    register_compat(srv, {"dx_verify_view_matrix", "re.dx_hook",
        "Verify a view/projection/viewproj matrix candidate by projecting test points or unit-cube corners to screen coordinates. Chain after dx_find_view_matrix.",
        {{"process_id", "number", "Target process id", true},
         {"matrix_va", "string", "Candidate matrix VA from find_view_matrix results", true},
         {"view_matrix_va", "string", "Alias for matrix_va", false},
         {"candidate_va", "string", "Alias for matrix_va", false},
         {"screen_width", "number", "Screen width override (auto-detected from window if omitted)", false},
         {"screen_height", "number", "Screen height override (auto-detected from window if omitted)", false},
         {"world_unit_max", "number", "Maximum plausible translation component", false},
         {"test_world_points", "array", "Optional array of {x,y,z} or [x,y,z] world points to project"}},
        re::dx_hook::verify_view_matrix, true});

    register_compat(srv, {"dx_project_bones", "re.dx_hook",
        "Project bone world positions from a bone buffer to screen coordinates using a view matrix. Chain after dx_identify_bone_buffer and dx_verify_view_matrix. If the projected points form a human silhouette on screen, both the view matrix and bone buffer are confirmed correct.",
        {{"process_id", "number", "Target process id", true},
         {"bone_buffer_va", "string", "Bone buffer VA from identify_bone_buffer results", true},
         {"view_matrix_va", "string", "Verified view matrix VA from verify_view_matrix or find_view_matrix results", true},
         {"screen_width", "number", "Screen width override (auto-detected from window if omitted)", false},
         {"screen_height", "number", "Screen height override (auto-detected from window if omitted)", false},
         {"world_unit_max", "number", "Maximum plausible translation component", false},
         {"max_bones", "number", "Maximum bones to read and project", false},
         {"bone_indices", "array", "Optional array of bone indices to project (default: all)"}},
         re::dx_hook::project_bones, true});

    register_compat(srv, {"dx_trace_decryption", "re.dx_hook",
        "Trace the decryption pipeline for a staging/cbuffer VA by setting a write hardware breakpoint, capturing the caller context, reading encrypted source vs decrypted staging, and deriving the encryption algorithm + key. Actions: trace, list, detail, stop, remove.",
         {{"action", "string", "trace|list|detail|stop|remove", true},
         {"staging_va", "string", "Staging/cbuffer VA to watch (from identify_bone_buffer or list_bound_cbuffers)", false},
         {"cbuffer_va", "string", "Alias for staging_va", false},
         {"staging_size", "number", "Size of staging buffer to watch", false},
         {"hw_slot", "number", "Hardware breakpoint register slot 0-3", false},
         {"max_frames", "number", "Maximum frames to capture (default 3)", false},
         {"timeout_ms", "number", "Wait timeout in milliseconds (default 30000)", false},
         {"pointer_location_va", "string", "VA of a pointer that tracks the staging buffer for reallocation detection", false},
         {"trace_id", "string", "Trace id for detail/remove", false},
         {"process_id", "number", "Target process id", true},
         {"confirm_unsafe", "boolean", "Required for trace/stop/remove", false},
         {"allow_unsafe", "boolean", "Alias of confirm_unsafe", false}},
         re::dx_hook::trace_decryption, false});

    register_compat(srv, {"dx_read_gpu_buffer", "re.dx_hook",
        "Read a D3D11 GPU-only constant buffer via remote COM method invocation. Requires a captured ID3D11Buffer* address (from dx_hook_manage cbuffer_bind capture) and the target's ID3D11DeviceContext* address.",
        {{"process_id", "number", "Target process id", true},
         {"buffer_va", "string", "ID3D11Buffer* address from cbuffer capture", true},
         {"device_context_va", "string", "ID3D11DeviceContext* address (from capture registers rcx); auto-detected from stored captures if absent", false},
         {"max_size", "number", "Maximum bytes to read (default 65536, max 1048576)", false},
         {"detect_matrices", "boolean", "Run matrix pattern detection on readback data", false},
         {"confirm_unsafe", "boolean", "Required - calls D3D11 methods in target process via kernel driver", false},
         {"allow_unsafe", "boolean", "Alias of confirm_unsafe", false}},
         re::dx_hook::read_gpu_buffer, false});

    register_compat(srv, {"dx_auto_narrow", "re.dx_hook",
        "One-shot pipeline: arms parallel Present+Draw+CBufferBind HWBPs, captures N frames, classifies cbuffers, evaluates persistent cbuffers as view matrix candidates and per-draw cbuffers as bone buffer candidates, returns a single ranked report.",
        {{"process_id", "number", "Target process id", true},
         {"capture_frames", "number", "Number of frames to capture (default 3)", false},
         {"api", "string", "auto|d3d11|d3d12|dxgi|vulkan", false},
         {"world_unit_max", "number", "Maximum plausible translation component", false},
         {"min_bones", "number", "Minimum matrix count for bone buffers", false},
         {"max_bones", "number", "Maximum matrix count for bone buffers", false},
         {"confirm_unsafe", "boolean", "Required for HWBP arming", false},
         {"allow_unsafe", "boolean", "Alias of confirm_unsafe", false}},
        re::dx_hook::auto_narrow, false});

    register_compat(srv, {"dx_correlate_results", "re.dx_hook",
        "Cross-correlate a view matrix VA and bone buffer VA by checking if they appear in the same frame batches and draw call sequences.",
        {{"process_id", "number", "Target process id", true},
         {"view_matrix_va", "string", "View matrix candidate VA", false},
         {"bone_buffer_va", "string", "Bone buffer candidate VA", false}},
        re::dx_hook::correlate_results, true});

    register_compat(srv, {"dx_get_frame_summary", "re.dx_hook",
        "Return the latest (or specified) captured frame batch with all cbuffers, draw calls, cbuffer classifications, and hot VA table.",
        {{"process_id", "number", "Target process id", true},
         {"frame_index", "number", "Specific frame index (default latest)", false},
         {"latest", "boolean", "Return latest frame (default true)", false}},
        re::dx_hook::get_frame_summary, true});

    register_compat(srv, {"vmt_read", "re.vmt",
        "Read and classify virtual method table slots from an object or vtable-pointer address.",
        {{"address", "string", "Address containing a vtable pointer", true},
         {"max_slots", "number", "Maximum slots to read", false},
         {"process_id", "number", "Target process id", false}},
        re::vmt::read, true});

    register_compat(srv, {"vmt_hook_manage", "re.vmt",
        "Install, remove, or list VMT slot hooks. Actions: install, remove, list.",
        {{"action", "string", "install|remove|list", true},
         {"hook_id", "string", "Hook id for remove", false},
         {"vtable_va", "string", "Vtable base for install", false},
         {"object_va", "string", "Object address for patch_object mode", false},
         {"slot", "number", "Vtable slot index", false},
         {"callback_va", "string", "Replacement callback address", false},
         {"method", "string", "patch_vtable|patch_object", false},
         {"process_id", "number", "Target process id", false},
         {"confirm_unsafe", "boolean", "Required for install/remove", false},
         {"allow_unsafe", "boolean", "Alias of confirm_unsafe", false}},
        re::vmt::hook_manage, false});

    register_compat(srv, {"vmt_copy", "re.vmt",
        "Copy an object's VMT into remote memory and patch only that object to the copy.",
        {{"object_va", "string", "Object address", true},
         {"process_id", "number", "Target process id", false},
         {"max_slots", "number", "Maximum slots to copy", false},
         {"confirm_unsafe", "boolean", "Required", false},
         {"allow_unsafe", "boolean", "Alias of confirm_unsafe", false}},
        re::vmt::copy, false});

    register_compat(srv, {"vmt_find_slot_by_signature", "re.vmt",
        "Find a VMT slot whose function prologue matches a hex pattern or disassembly mnemonic/text pattern.",
        {{"vtable_va", "string", "Vtable base", true},
         {"pattern", "string", "Hex pattern with ?? wildcards, or semicolon/newline separated disassembly patterns", true},
         {"pattern_kind", "string", "auto|bytes|disasm", false},
         {"max_slots", "number", "Maximum slots to scan", false},
         {"process_id", "number", "Target process id", false}},
        re::vmt::find_slot_by_signature, true});

    register_compat(srv, {"vmt_scan_objects", "re.vmt",
        "Scan readable writable memory for objects whose first pointer equals the given vtable.",
        {{"vtable_va", "string", "Vtable address", true},
         {"process_id", "number", "Target process id", false},
         {"max_results", "number", "Maximum objects to return", false}},
        re::vmt::scan_objects, true});

    register_compat(srv, {"rtti_scan", "re.rtti",
        "Scan live module RTTI TypeDescriptor and CompleteObjectLocator records.",
        {{"module_name", "string", "Optional module name", false},
         {"module_base_va", "string", "Optional module base address", false},
         {"rtti_module_base_va", "string", "Optional module base address alias", false},
         {"vtable_va", "string", "Optional vtable hint address", false},
         {"rtti_vtable_va", "string", "Optional vtable hint address alias", false},
         {"type_descriptor_va", "string", "Optional exact TypeDescriptor address", false},
         {"rtti_type_descriptor_va", "string", "Optional exact TypeDescriptor address alias", false},
         {"complete_object_locator_va", "string", "Optional exact CompleteObjectLocator address", false},
         {"rtti_complete_object_locator_va", "string", "Optional exact CompleteObjectLocator address alias", false},
         {"filter", "string", "Optional regex filter", false},
         {"module_filter", "string", "Optional module name/path substring filter", false},
         {"include_system_modules", "boolean", "Include Windows system modules", false},
         {"module_limit", "number", "Maximum modules to scan after ordering/filtering", false},
         {"scan_mode", "string", "fast|deep", false},
         {"include_diagnostics", "boolean", "Include per-module RTTI scan diagnostics", false},
         {"process_id", "number", "Target process id", false},
         {"max_results", "number", "Maximum types to return", false},
         {"max_vtables_per_type", "number", "Maximum vtable records emitted per type", false},
         {"timeout_ms", "number", "Maximum scan time", false}},
        re::rtti::scan, true});

    register_compat(srv, {"rtti_find_type", "re.rtti",
        "Find RTTI types matching a regex pattern.",
        {{"pattern", "string", "Name regex; optional when exact RTTI selectors are supplied", true},
         {"module_name", "string", "Optional module name", false},
         {"module_base_va", "string", "Optional module base address", false},
         {"rtti_module_base_va", "string", "Optional module base address alias", false},
         {"vtable_va", "string", "Optional vtable hint address", false},
         {"rtti_vtable_va", "string", "Optional vtable hint address alias", false},
         {"type_descriptor_va", "string", "Optional exact TypeDescriptor address", false},
         {"rtti_type_descriptor_va", "string", "Optional exact TypeDescriptor address alias", false},
         {"complete_object_locator_va", "string", "Optional exact CompleteObjectLocator address", false},
         {"rtti_complete_object_locator_va", "string", "Optional exact CompleteObjectLocator address alias", false},
         {"module_filter", "string", "Optional module name/path substring filter", false},
         {"include_system_modules", "boolean", "Include Windows system modules", false},
         {"module_limit", "number", "Maximum modules to scan after ordering/filtering", false},
         {"scan_mode", "string", "fast|deep", false},
         {"include_diagnostics", "boolean", "Include per-module RTTI scan diagnostics", false},
         {"process_id", "number", "Target process id", false},
         {"max_results", "number", "Maximum matches to return", false},
         {"max_vtables_per_type", "number", "Maximum vtable records emitted per type", false},
         {"timeout_ms", "number", "Maximum scan time", false}},
        re::rtti::find_type, true});

    register_compat(srv, {"rtti_list_hierarchy", "re.rtti",
        "List inheritance hierarchy for an RTTI type name or vtable/type descriptor VA.",
        {{"type_name_or_va", "string", "Type substring or address; optional when exact RTTI selectors are supplied", true},
         {"vtable_va", "string", "Optional vtable hint address", false},
         {"rtti_vtable_va", "string", "Optional vtable hint address alias", false},
         {"type_descriptor_va", "string", "Optional exact TypeDescriptor address", false},
         {"rtti_type_descriptor_va", "string", "Optional exact TypeDescriptor address alias", false},
         {"complete_object_locator_va", "string", "Optional exact CompleteObjectLocator address", false},
         {"rtti_complete_object_locator_va", "string", "Optional exact CompleteObjectLocator address alias", false},
         {"module_name", "string", "Optional module name", false},
         {"module_base_va", "string", "Optional module base address", false},
         {"rtti_module_base_va", "string", "Optional module base address alias", false},
         {"module_filter", "string", "Optional module name/path substring filter", false},
         {"include_system_modules", "boolean", "Include Windows system modules", false},
         {"module_limit", "number", "Maximum modules to scan after ordering/filtering", false},
         {"scan_mode", "string", "fast|deep", false},
         {"include_diagnostics", "boolean", "Include per-module RTTI scan diagnostics", false},
         {"process_id", "number", "Target process id", false},
         {"max_vtables_per_type", "number", "Maximum vtable records emitted per type", false},
         {"timeout_ms", "number", "Maximum scan time", false}},
        re::rtti::list_hierarchy, true});

    register_compat(srv, {"rtti_find_constructor", "re.rtti",
        "Find constructor candidates that reference a given vtable.",
        {{"vtable_va", "string", "Vtable address", true},
         {"rtti_vtable_va", "string", "Vtable address alias", false},
         {"constructor_fn_va", "string", "Optional exact constructor function selector", false},
         {"rtti_constructor_fn_va", "string", "Optional exact constructor function selector alias", false},
         {"scan_start_va", "string", "Optional bounded constructor scan start", false},
         {"scan_end_va", "string", "Optional bounded constructor scan end", false},
         {"scan_size", "number", "Optional bounded constructor scan size", false},
         {"process_id", "number", "Target process id", false},
         {"timeout_ms", "number", "Maximum scan time", false},
         {"max_candidates", "number", "Maximum constructor candidates to return", false},
         {"max_scan_bytes", "number", "Maximum executable section bytes to scan", false}},
        re::rtti::find_constructor, true});

    register_compat(srv, {"encptr_scan_chain", "re.encptr",
        "Scan for raw and transformed pointer chains connecting source_va to target_va.",
        {{"source_va", "string", "Source pointer slot or base address", true},
         {"target_va", "string", "Expected target address", true},
         {"max_hops", "number", "Maximum chain depth", false},
          {"max_offset", "number", "Maximum signed field offset per hop", false},
          {"max_results", "number", "Maximum paths to return", false},
          {"test_xor", "boolean", "Test XOR transforms", false},
          {"test_rol", "boolean", "Test rotate transforms", false},
          {"test_add", "boolean", "Test add/sub transforms", false},
          {"auto_derive", "boolean", "Automatically derive exact-target XOR/XOR-address/add/sub candidates and common add/sub constants", false},
          {"max_candidates_per_slot", "number", "Maximum transform candidates retained per slot", false},
          {"xor_key", "string", "Optional known XOR key", false},
          {"xor_keys", "array", "Optional known XOR keys", false},
          {"add_keys", "array", "Optional known add constants", false},
          {"sub_keys", "array", "Optional known sub constants", false},
          {"process_id", "number", "Target process id", false}},
        re::encptr::scan_chain, true});

    register_compat(srv, {"encptr_detect_transform", "re.encptr",
        "Detect a single-hop transform between raw_value and expected_next.",
        {{"raw_value", "string", "Raw value", true},
          {"expected_next", "string", "Expected transformed value", true},
          {"address_va", "string", "Optional source slot address for XOR-with-address detection", false},
          {"test_xor", "boolean", "Test XOR transform family", false},
          {"test_add", "boolean", "Test add/sub transform family", false},
          {"test_rol", "boolean", "Test rotate transform family", false},
          {"allow_derived_keys", "boolean", "Allow exact-target derived transform keys", false},
          {"auto_derive", "boolean", "Alias for allow_derived_keys", false}},
        re::encptr::detect_transform, true});

    register_compat(srv, {"encptr_emit_resolver", "re.encptr",
        "Emit C++ resolver code for an encoded pointer chain.",
        {{"chain", "object", "Chain object, single path, or full encptr_scan_chain result with paths", true},
         {"path_index", "number", "Path index when chain contains paths", false},
         {"function_name", "string", "Generated function name", false},
         {"base_symbol", "string", "Generated base symbol parameter", false}},
        re::encptr::emit_resolver, true});

    register_compat(srv, {"encptr_verify_stable", "re.encptr",
        "Sample a resolved encoded pointer chain repeatedly and classify stability.",
        {{"chain", "object", "Chain object", true},
         {"samples", "number", "Sample count", false},
         {"interval_ms", "number", "Interval between samples", false},
         {"timeout_ms", "number", "Local bounded sampling deadline", false},
         {"process_id", "number", "Target process id", false}},
        re::encptr::verify_stable, true});

    register_compat(srv, {"offsets_manage", "re.offsets",
        "Manage persisted offsets. Actions: record, list, reverify, rebase, export.",
        {{"action", "string", "record|list|reverify|rebase|export", true},
          {"payload", "object", "Action-specific payload", false},
          {"name", "string", "Offset name for record/export identifier", false},
          {"va", "string", "Live offset VA for record", false},
          {"category", "string", "Category filter or record category", false},
          {"notes", "string", "Record notes", false},
          {"aob_pattern", "string", "AoB fingerprint for record/reverify", false},
          {"rtti_path", "string", "RTTI path evidence for record", false},
          {"xref_context", "string", "Xref context evidence for record", false},
          {"verified_only", "boolean", "List only valid offsets", false},
          {"offset_id", "string", "Single offset id for reverify/rebase", false},
          {"offset_ids", "array", "Offset ids for reverify/rebase", false},
          {"module_name", "string", "Module filter for reverify/rebase", false},
          {"max_aob_matches", "number", "Maximum saved AoB matches considered during reverify/rebase", false},
          {"output_path", "string", "Export output path", false},
          {"namespace_name", "string", "C++ namespace for export", false},
          {"use_rva", "boolean", "Export RVAs instead of VAs", false},
          {"process_id", "number", "Target process id", false},
          {"confirm_unsafe", "boolean", "Required for actions that write persistence or files", false},
          {"allow_unsafe", "boolean", "Alias of confirm_unsafe", false}},
        re::offsets::manage, false});

    register_compat(srv, {"heap_track_manage", "re.heap_track",
        "Manage heap allocation tracking sessions. Actions: start, results, stop. Backend auto is kernel-context HWBP return polling and fails closed when unavailable.",
        {{"action", "string", "start|results|stop", true},
         {"payload", "object", "Action-specific payload", false},
         {"session_id", "string", "Heap tracking session id for results/stop", false},
         {"process_id", "number", "Target process id for start", false},
         {"backend", "string", "auto|event|hwbp|hardware_breakpoint|debug_events", false},
         {"min_size", "number", "Minimum allocation size filter", false},
         {"max_size", "number", "Maximum allocation size filter", false},
         {"alignment", "number", "Required allocation-base alignment filter, 0 disables", false},
         {"capture_callstack", "boolean", "Capture bounded return-address callstack evidence for kernel-context event captures", false},
         {"max_captures", "number", "Maximum captures to retain", false},
         {"hw_slot", "number", "Hardware breakpoint register slot for event backends", false},
         {"skip_initial_snapshot", "boolean", "Skip initial snapshot for start", false},
         {"empty_baseline", "boolean", "Alias for skip_initial_snapshot", false},
         {"limit", "number", "Maximum result rows", false},
         {"focus_only", "boolean", "Return only focused fixture allocations", false},
         {"focus_va", "string", "Focused allocation base address", false},
         {"capture_va", "string", "Alias for focused allocation base address", false},
         {"allocation_va", "string", "Alias for focused allocation base address", false},
         {"focus_count", "number", "Focused allocation count", false},
         {"focus_stride", "number", "Focused allocation stride", false},
         {"focus_size", "number", "Focused allocation size", false},
         {"allocation_size", "number", "Alias for focused allocation size", false},
         {"confirm_unsafe", "boolean", "Required for start and stop", false},
         {"allow_unsafe", "boolean", "Alias of confirm_unsafe", false}},
        re::heap_track::manage, false});

    register_compat(srv, {"sigs_manage", "re.sigs",
        "Manage persisted pattern signatures. Actions: save, list, scan_all, import, export.",
        {{"action", "string", "save|list|scan_all|import|export", true},
          {"payload", "object", "Action-specific payload", false},
          {"name", "string", "Signature name for save", false},
          {"pattern", "string", "AoB pattern for save", false},
          {"module_hint", "string", "Module scope hint or filter", false},
          {"category", "string", "Category filter or record category", false},
          {"notes", "string", "Record notes", false},
          {"offset_from_match", "number", "VA adjustment from pattern match", false},
          {"source", "string", "Import file path or inline content", false},
          {"format", "string", "json|ida|x64dbg|ce", false},
          {"output_path", "string", "Export output path", false},
          {"process_id", "number", "Target process id for scan_all", false},
          {"confirm_unsafe", "boolean", "Required for actions that write persistence or files", false},
          {"allow_unsafe", "boolean", "Alias of confirm_unsafe", false}},
        re::sigs::manage, false});

    register_compat(srv, {"struct_observe", "re.struct_adv",
        "Observe a struct region and infer fields using the existing struct reconstruction engine.",
        {{"base_va", "string", "Struct base address", true},
         {"size", "number", "Struct size", false},
         {"duration_sec", "number", "Observation duration", false},
         {"timeout_ms", "number", "Maximum observation wait time", false},
         {"process_id", "number", "Target process id", false},
         {"confirm_unsafe", "boolean", "Required to arm observation breakpoints", false},
         {"allow_unsafe", "boolean", "Alias of confirm_unsafe", false}},
        re::struct_adv::observe, false});

    register_compat(srv, {"struct_correlate", "re.struct_adv",
        "Correlate separately found field addresses into a probable struct base and offsets.",
        {{"field_addresses", "array", "Array of {name, va}", true},
         {"max_span", "number", "Maximum candidate struct span", false},
         {"process_id", "number", "Target process id for type previews", false}},
        re::struct_adv::correlate, true});

    register_compat(srv, {"struct_array_detect", "re.struct_adv",
        "Check whether base_va is the start of repeated struct-like elements.",
        {{"base_va", "string", "Array base address", true},
          {"suspected_size", "number", "Suspected element size", true},
          {"max_elements", "number", "Maximum elements to inspect", false},
          {"process_id", "number", "Target process id", false}},
        re::struct_adv::array_detect, true});

    register_compat(srv, {"struct_compare_snapshots", "re.struct_adv",
        "Compare two RE or scanner snapshots for a struct region.",
        {{"snapshot_a_id", "string", "First snapshot id or name", true},
         {"snapshot_b_id", "string", "Second snapshot id or name", true},
         {"base_va", "string", "Struct base address", true},
         {"struct_size", "number", "Struct size", false}},
        re::struct_adv::compare_snapshots, true});
}
}
