#pragma once

#include "network_preview_adapter.hpp"

#include "../core/network/burp/active_scanner.hpp"
#include "../core/network/burp/api_definition.hpp"
#include "../core/network/burp/audit_http.hpp"
#include "../core/network/burp/content_discovery.hpp"
#include "../core/network/burp/crawler.hpp"
#include "../core/network/burp/h2_editor.hpp"
#include "../core/network/burp/intruder_engine.hpp"
#include "../core/network/burp/issue.hpp"
#include "../core/network/burp/passive_scanner.hpp"
#include "../core/network/burp/payload_library.hpp"
#include "../core/network/burp/report_generator.hpp"
#include "../core/network/burp/scanner_module.hpp"
#include "../core/network/burp/subdomain_enum.hpp"
#include "../core/network/burp/ws_editor.hpp"

#include <algorithm>
#include <cctype>
#include <map>
#include <optional>

namespace aida::burp {

inline const char* severity_label(severity_t severity) {
    switch (severity) {
    case severity_t::info: return "Info";
    case severity_t::low: return "Low";
    case severity_t::medium: return "Medium";
    case severity_t::high: return "High";
    case severity_t::critical: return "Critical";
    }
    return "Info";
}

inline const char* confidence_label(confidence_t confidence) {
    switch (confidence) {
    case confidence_t::tentative: return "Tentative";
    case confidence_t::firm: return "Firm";
    case confidence_t::certain: return "Certain";
    }
    return "Tentative";
}

inline bool parse_severity(const std::string& value, severity_t& output) {
    for (int i = 0; i <= static_cast<int>(severity_t::critical); ++i) {
        const auto candidate = static_cast<severity_t>(i);
        std::string label = severity_label(candidate);
        std::transform(label.begin(), label.end(), label.begin(), [](unsigned char c){ return static_cast<char>(std::tolower(c)); });
        std::string input = value;
        std::transform(input.begin(), input.end(), input.begin(), [](unsigned char c){ return static_cast<char>(std::tolower(c)); });
        if (input == label) { output = candidate; return true; }
    }
    return false;
}

inline bool parse_confidence(const std::string& value, confidence_t& output) {
    for (int i = 0; i <= static_cast<int>(confidence_t::certain); ++i) {
        const auto candidate = static_cast<confidence_t>(i);
        std::string label = confidence_label(candidate);
        std::transform(label.begin(), label.end(), label.begin(), [](unsigned char c){ return static_cast<char>(std::tolower(c)); });
        std::string input = value;
        std::transform(input.begin(), input.end(), input.begin(), [](unsigned char c){ return static_cast<char>(std::tolower(c)); });
        if (input == label) { output = candidate; return true; }
    }
    return false;
}

namespace issue_store {
inline std::vector<issue_t> s_preview_issues;
inline uint64_t s_preview_next_issue = 4;
inline bool s_preview_issues_seeded = false;

inline void ensure_preview_issues() {
    if (s_preview_issues_seeded) return;
    s_preview_issues_seeded = true;
    issue_t sqli;
    sqli.id=1; sqli.session_id="reverse-lab"; sqli.scan_id=701; sqli.audit_id=501; sqli.type_key="sqli.error"; sqli.name="SQL injection in artifact query";
    sqli.description="The artifact query parameter changes database error behavior."; sqli.remediation="Use parameterized queries and strict input schemas."; sqli.cwe={"CWE-89"}; sqli.cvss_score=9.1; sqli.cvss_vector="CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"; sqli.cvss_severity="Critical"; sqli.owasp_category="A03:2021 Injection"; sqli.severity=severity_t::critical; sqli.confidence=confidence_t::certain; sqli.scheme="https"; sqli.host="sandbox.aidapro.net"; sqli.port=443; sqli.path="/api/v2/artifacts"; sqli.parameter="id"; sqli.insertion_point="query:id"; sqli.seen_ms=aida::preview::network::monotonic_ms()-180000; sqli.evidence.push_back({"GET /api/v2/artifacts?id=1%27 HTTP/1.1", "HTTP/1.1 500 Internal Server Error\r\n\r\nsyntax error near quote", "syntax error", 0, 46});
    issue_t cors;
    cors.id=2; cors.session_id="reverse-lab"; cors.scan_id=701; cors.audit_id=501; cors.type_key="cors.origin"; cors.name="Arbitrary origin trusted with credentials"; cors.description="The API reflects untrusted origins while allowing credentials."; cors.remediation="Allow only explicit trusted origins."; cors.cwe={"CWE-942"}; cors.cvss_score=7.5; cors.cvss_severity="High"; cors.owasp_category="A05:2021 Security Misconfiguration"; cors.severity=severity_t::high; cors.confidence=confidence_t::firm; cors.scheme="https"; cors.host="portal.aidapro.net"; cors.port=443; cors.path="/api/v2/session"; cors.parameter="Origin"; cors.insertion_point="header:Origin"; cors.seen_ms=aida::preview::network::monotonic_ms()-122000;
    issue_t disclosure;
    disclosure.id=3; disclosure.session_id="reverse-lab"; disclosure.scan_id=702; disclosure.audit_id=502; disclosure.type_key="info.stacktrace"; disclosure.name="Verbose stack trace disclosure"; disclosure.description="Unhandled failures disclose internal module and source paths."; disclosure.remediation="Return canonical errors and retain details in server logs."; disclosure.cwe={"CWE-209"}; disclosure.cvss_score=5.3; disclosure.cvss_severity="Medium"; disclosure.owasp_category="A05:2021 Security Misconfiguration"; disclosure.severity=severity_t::medium; disclosure.confidence=confidence_t::certain; disclosure.scheme="https"; disclosure.host="sandbox.aidapro.net"; disclosure.port=443; disclosure.path="/v1/analyze"; disclosure.parameter="module"; disclosure.insertion_point="json:module"; disclosure.seen_ms=aida::preview::network::monotonic_ms()-64000;
    s_preview_issues={std::move(sqli),std::move(cors),std::move(disclosure)};
}

inline bool initialize() { ensure_preview_issues(); return true; }
inline void shutdown() {}
inline uint64_t add(issue_t issue) { ensure_preview_issues(); issue.id=s_preview_next_issue++; if(issue.seen_ms==0) issue.seen_ms=aida::preview::network::monotonic_ms(); s_preview_issues.push_back(std::move(issue)); return s_preview_issues.back().id; }
inline bool remove(uint64_t id) { const auto n=s_preview_issues.size(); s_preview_issues.erase(std::remove_if(s_preview_issues.begin(),s_preview_issues.end(),[id](const auto& issue){return issue.id==id;}),s_preview_issues.end()); return n!=s_preview_issues.size(); }
inline void clear() { s_preview_issues.clear(); aida::preview::network::record_receipt("Scanner issues", "cleared"); }
inline std::vector<issue_t> list(const issue_filter_t& filter) { ensure_preview_issues(); std::vector<issue_t> result; for(const auto& issue:s_preview_issues){if(!filter.include_suppressed&&issue.suppressed)continue;if(filter.has_severity_min&&issue.severity<filter.severity_min)continue;if(filter.has_confidence_min&&issue.confidence<filter.confidence_min)continue;if(filter.has_audit_id&&issue.audit_id!=filter.audit_id)continue;if(!filter.host_substring.empty()&&issue.host.find(filter.host_substring)==std::string::npos)continue;if(!filter.type_key_substring.empty()&&issue.type_key.find(filter.type_key_substring)==std::string::npos)continue;result.push_back(issue);if(filter.limit&&result.size()>=filter.limit)break;} return result; }
inline size_t count() { ensure_preview_issues(); return s_preview_issues.size(); }
inline bool get(uint64_t id, issue_t& output) { ensure_preview_issues(); for(const auto& issue:s_preview_issues)if(issue.id==id){output=issue;return true;}return false; }
inline size_t count_by_severity(severity_t severity) { ensure_preview_issues(); return static_cast<size_t>(std::count_if(s_preview_issues.begin(),s_preview_issues.end(),[severity](const auto& issue){return issue.severity==severity;})); }
inline nlohmann::json issue_to_json(const issue_t& issue) { return {{"id",issue.id},{"name",issue.name},{"type",issue.type_key},{"severity",severity_label(issue.severity)},{"confidence",confidence_label(issue.confidence)},{"host",issue.host},{"path",issue.path},{"parameter",issue.parameter},{"description",issue.description},{"remediation",issue.remediation},{"cvss_score",issue.cvss_score},{"audit_id",issue.audit_id}}; }
inline nlohmann::json export_json(const issue_filter_t& filter) { auto issues=list(filter); nlohmann::json document={{"count",issues.size()},{"issues",nlohmann::json::array()}}; for(const auto& issue:issues)document["issues"].push_back(issue_to_json(issue)); return document; }
inline bool import_json(const nlohmann::json& document, bool replace_existing) { if(!document.is_object()||!document.contains("issues")||!document["issues"].is_array())return false;if(replace_existing)s_preview_issues.clear();for(const auto& item:document["issues"]){issue_t issue;issue.name=item.value("name","Imported issue");issue.type_key=item.value("type","imported");issue.host=item.value("host","");issue.path=item.value("path","");issue.description=item.value("description","");parse_severity(item.value("severity","Info"),issue.severity);add(std::move(issue));}return true; }
inline std::string last_error() { return {}; }
inline std::string storage_path() { return "/aida-preview/state/scanner-issues.json"; }
inline bool save_to_disk() { aida::preview::network::record_receipt("Scanner issues", "saved to preview state"); return true; }
inline bool load_from_disk() { return initialize(); }
}

namespace scanner {
inline std::vector<module_t>& preview_modules() { static std::vector<module_t> modules={{"sqli","SQL Injection","Injection",8,{},{},{}},{"xss","Cross-site Scripting","Client",6,{},{},{}},{"ssrf","Server-side Request Forgery","Server",5,{},{},{}},{"authz","Authorization Matrix","Access Control",10,{},{},{}},{"smuggling","HTTP Request Smuggling","Protocol",6,{},{},{}},{"jwt","JWT Validation","Authentication",6,{},{},{}}}; return modules; }
inline bool register_module(module_t module) { auto& modules=preview_modules(); if(std::any_of(modules.begin(),modules.end(),[&](const auto& item){return item.id==module.id;}))return false;modules.push_back(std::move(module));return true; }
inline std::vector<module_t> all_modules() { return preview_modules(); }
inline const module_t* find(const std::string& id) { for(const auto& module:preview_modules())if(module.id==id)return &module;return nullptr; }
inline size_t count() { return preview_modules().size(); }
inline std::string random_marker(const std::string& prefix) { return prefix+"-preview-7f32"; }
inline bool body_contains(const exchange_observed_t& response,const std::string& needle){return std::search(response.resp_body.begin(),response.resp_body.end(),needle.begin(),needle.end())!=response.resp_body.end();}
inline bool body_contains_ci(const exchange_observed_t& response,const std::string& needle){std::string body(response.resp_body.begin(),response.resp_body.end()),query=needle;std::transform(body.begin(),body.end(),body.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});std::transform(query.begin(),query.end(),query.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});return body.find(query)!=std::string::npos;}
inline double body_length_ratio(const exchange_observed_t& a,const exchange_observed_t& b){return a.resp_body.empty()?(b.resp_body.empty()?1.0:0.0):static_cast<double>(b.resp_body.size())/static_cast<double>(a.resp_body.size());}
inline response_diff_t compare_response_to_baseline(const exchange_observed_t& response,const module_context_t& context,const std::vector<response_marker_t>&,const std::vector<response_marker_t>&){response_diff_t diff;diff.baseline_known=true;diff.baseline_status=context.baseline_status_code;diff.response_status=response.status_code;diff.status_changed=diff.baseline_status!=diff.response_status;diff.same_status=!diff.status_changed;diff.baseline_body_length=context.baseline_response_body.size();diff.response_body_length=response.resp_body.size();diff.body_length_delta=diff.baseline_body_length>diff.response_body_length?diff.baseline_body_length-diff.response_body_length:diff.response_body_length-diff.baseline_body_length;diff.body_length_ratio=diff.baseline_body_length?static_cast<double>(diff.response_body_length)/diff.baseline_body_length:1.0;diff.meaningful_body_delta=diff.body_length_delta>32;diff.evidence=diff.status_changed?"Response status changed from baseline":"Response body differs from baseline";return diff;}
inline response_diff_t compare_responses(const exchange_observed_t& baseline,const exchange_observed_t& response,const std::vector<response_marker_t>& removed,const std::vector<response_marker_t>& added){module_context_t context;context.baseline_status_code=baseline.status_code;context.baseline_response_body=baseline.resp_body;context.baseline_response_headers=baseline.resp_headers;return compare_response_to_baseline(response,context,removed,added);}
inline issue_t make_issue(const std::string& type_key,const std::string& name,severity_t severity,confidence_t confidence,const insertion_point_t&,const probe_t& probe,const exchange_observed_t& response,const module_context_t& context,const std::string& evidence){issue_t issue;issue.type_key=type_key;issue.name=name;issue.severity=severity;issue.confidence=confidence;issue.scheme=response.scheme;issue.host=response.host;issue.port=response.port;issue.path=response.path;issue.audit_id=context.audit_id;issue.evidence.push_back({probe.payload,std::string(response.resp_body.begin(),response.resp_body.end()),evidence});return issue;}
}

namespace active_scanner {
inline uint64_t s_preview_next_audit=503;
inline std::vector<audit_status_t> s_preview_audits;
inline void ensure_preview_audits(){if(!s_preview_audits.empty())return;audit_status_t first;first.id=501;first.session_id="reverse-lab";first.scan_id=701;first.url="https://portal.aidapro.net/api/v2/session";first.host="portal.aidapro.net";first.port=443;first.tls=true;first.total_points=12;first.total_probes=72;first.completed_probes=72;first.issues_found=2;first.running=false;first.drained=true;first.responses_received=72;first.started_ms=aida::preview::network::monotonic_ms()-240000;first.ended_ms=first.started_ms+94000;first.effective_max_concurrent=8;audit_status_t second=first;second.id=502;second.scan_id=702;second.url="https://sandbox.aidapro.net/v1/analyze";second.host="sandbox.aidapro.net";second.total_points=9;second.total_probes=54;second.completed_probes=41;second.issues_found=1;second.running=true;second.drained=false;second.queued_workers=5;second.active_workers=4;second.in_flight_requests=4;second.responses_received=41;second.started_ms=aida::preview::network::monotonic_ms()-56000;second.ended_ms=0;s_preview_audits={first,second};}
inline bool initialize(){ensure_preview_audits();return true;} inline void shutdown(){}
inline uint64_t enqueue_target(const std::vector<uint8_t>& request,const std::string& url,const audit_config_t& config){audit_status_t audit;audit.id=s_preview_next_audit++;audit.session_id=config.session_id;audit.scan_id=config.scan_id;audit.url=url;audit.host=url.find("sandbox")!=std::string::npos?"sandbox.aidapro.net":"portal.aidapro.net";audit.port=443;audit.tls=url.rfind("https://",0)==0;audit.total_points=8;audit.total_probes=48;audit.completed_probes=48;audit.issues_found=1;audit.running=false;audit.drained=true;audit.responses_received=48;audit.request_length=request.size();audit.started_ms=aida::preview::network::monotonic_ms()-2400;audit.ended_ms=aida::preview::network::monotonic_ms();audit.effective_max_concurrent=config.max_concurrent_requests;audit.effective_throttle_ms=config.request_throttle_ms;s_preview_audits.push_back(audit);aida::preview::network::record_receipt("Scanner audit",url);return audit.id;}
inline bool cancel_audit(uint64_t id){ensure_preview_audits();for(auto& audit:s_preview_audits)if(audit.id==id){audit.running=false;audit.cancelled=true;audit.cancel_requested=true;audit.drained=true;audit.ended_ms=aida::preview::network::monotonic_ms();return true;}return false;}
inline bool wait_for_audit_idle(uint64_t id,uint32_t){audit_status_t status;return get_status(id,status)&&!status.running;}
inline std::vector<audit_status_t> list_audits(){ensure_preview_audits();return s_preview_audits;}
inline bool get_status(uint64_t id,audit_status_t& output){ensure_preview_audits();for(const auto& audit:s_preview_audits)if(audit.id==id){output=audit;return true;}return false;}
inline scanner_load_t load_snapshot(){ensure_preview_audits();scanner_load_t load;load.active_audits=s_preview_audits.size();load.running_audits=static_cast<size_t>(std::count_if(s_preview_audits.begin(),s_preview_audits.end(),[](const auto& audit){return audit.running;}));load.active_workers=4;load.in_flight_requests=4;load.max_active_audits=4;return load;}
inline std::string last_error(){return{};} inline std::string last_error_code(){return{};}
}

namespace passive_scanner {
inline bool s_preview_enabled=true;
inline bool initialize(){return true;} inline void shutdown(){} inline bool is_enabled(){return s_preview_enabled;} inline void set_enabled(bool enabled){s_preview_enabled=enabled;aida::preview::network::record_receipt("Passive scanner",enabled?"enabled":"disabled");} inline stats_t get_stats(){return{184,3,aida::preview::network::monotonic_ms()-8000};} inline std::string last_error(){return{};}
}

namespace audit_http {
inline std::string s_preview_error;
inline bool parse_url(const std::string& url,std::string& scheme,std::string& host,uint16_t& port,std::string& path){const auto sep=url.find("://");if(sep==std::string::npos)return false;scheme=url.substr(0,sep);const auto start=sep+3;const auto slash=url.find('/',start);std::string authority=url.substr(start,slash==std::string::npos?std::string::npos:slash-start);const auto colon=authority.rfind(':');host=colon==std::string::npos?authority:authority.substr(0,colon);port=colon==std::string::npos?(scheme=="https"?443:80):static_cast<uint16_t>(std::stoi(authority.substr(colon+1)));path=slash==std::string::npos?"/":url.substr(slash);return!host.empty();}
inline std::optional<exchange_observed_t> send(const std::vector<uint8_t>& request,const std::string& host,uint16_t port,bool tls,const send_options_t& options){exchange_observed_t exchange;exchange.id=aida::preview::network::monotonic_ms();exchange.timestamp_ms=exchange.id;exchange.method=request.size()>=4?std::string(request.begin(),request.begin()+static_cast<std::vector<uint8_t>::difference_type>(std::min<size_t>(4,request.size()))):"GET";exchange.scheme=tls?"https":"http";exchange.host=host;exchange.port=port;exchange.path="/api/v2/preview";exchange.status_code=200;exchange.reason_phrase="OK";exchange.resp_headers={{"content-type","application/json"},{"x-aida-preview","deterministic"}};const std::string body="{\"status\":\"ok\",\"source\":\"network-preview\",\"request_bytes\":"+std::to_string(request.size())+"}";exchange.resp_body.assign(body.begin(),body.end());exchange.latency_ms=47;exchange.is_h2=tls;exchange.tls_version=tls?"TLS 1.3":"";exchange.alpn=tls?"h2":"http/1.1";exchange.source=options.exchange_source.empty()?"api-preview":options.exchange_source;s_preview_error.clear();aida::preview::network::record_receipt("HTTP request",host);return exchange;}
inline std::string last_error(){return s_preview_error;}
}

namespace payloads {
inline std::vector<payload_set_t> s_preview_sets;
inline void ensure_preview_sets(){if(!s_preview_sets.empty())return;s_preview_sets={{"sqli/core","SQL injection core","High-signal SQL syntax and boolean probes",{"'","' OR '1'='1","1 AND SLEEP(2)","1 UNION SELECT NULL"},true},{"xss/context","Cross-site scripting contexts","HTML, attribute, and JavaScript context probes",{"<svg/onload=confirm(1)>","\"><img src=x onerror=confirm(1)>","javascript:confirm(1)"},true},{"paths/reverse-engineering","Artifact and symbol paths","Reverse-engineering service discovery candidates",{"/api/v2/symbols","/api/v2/artifacts","/debug/modules","/.well-known/aida"},true}};}
inline bool initialize(){ensure_preview_sets();return true;}inline void shutdown(){}inline const payload_set_t* get(const std::string& id){ensure_preview_sets();for(const auto& set:s_preview_sets)if(set.id==id)return &set;return nullptr;}inline std::vector<std::string> list_ids(){ensure_preview_sets();std::vector<std::string> ids;for(const auto& set:s_preview_sets)ids.push_back(set.id);return ids;}inline std::vector<payload_set_t> list_summaries(){ensure_preview_sets();return s_preview_sets;}inline std::vector<std::string> entries(const std::string& id,size_t max_count){const auto* set=get(id);if(!set)return{};auto result=set->entries;if(max_count&&result.size()>max_count)result.resize(max_count);return result;}inline std::vector<std::string> search(const std::string& query,const std::string& set_id){ensure_preview_sets();std::vector<std::string> result;for(const auto& set:s_preview_sets){if(!set_id.empty()&&set.id!=set_id)continue;for(const auto& entry:set.entries)if(entry.find(query)!=std::string::npos)result.push_back(entry);}return result;}inline bool add_custom_set(const std::string& id,const std::string& label,const std::string& description,const std::vector<std::string>& entries){ensure_preview_sets();if(id.empty()||entries.empty()||get(id))return false;s_preview_sets.push_back({id,label,description,entries,false});aida::preview::network::record_receipt("Payload set",id);return true;}inline bool remove_custom_set(const std::string& id){ensure_preview_sets();const auto n=s_preview_sets.size();s_preview_sets.erase(std::remove_if(s_preview_sets.begin(),s_preview_sets.end(),[&](const auto& set){return set.id==id&&!set.builtin;}),s_preview_sets.end());return n!=s_preview_sets.size();}inline bool load_from_file(const std::string& path,const std::string& id){return add_custom_set(id,id,"Preview import from "+path,{"preview-one","preview-two"});}inline bool export_to_file(const std::string& path,const std::string& id){if(!get(id))return false;aida::preview::network::record_receipt("Payload export",path);return true;}inline bool set_exists(const std::string& id){return get(id)!=nullptr;}inline std::string storage_dir(){return"/aida-preview/state/payloads";}inline std::string last_error(){return{};}
}

namespace crawler {
inline uint64_t s_preview_next_crawl=3; inline std::vector<crawl_status_t> s_preview_crawls;
inline void ensure_preview_crawls(){if(!s_preview_crawls.empty())return;crawl_status_t crawl;crawl.id=1;crawl.phase=crawl_status_phase_t::complete;crawl.pages_visited=18;crawl.urls_found=31;crawl.started_unix_ms=aida::preview::network::monotonic_ms()-190000;crawl.finished_unix_ms=crawl.started_unix_ms+82000;crawl.last_progress_unix_ms=crawl.finished_unix_ms;crawl.pages_per_sec=4.2;crawl.last_url="https://portal.aidapro.net/api/v2/symbols";crawl.config.start_urls={"https://portal.aidapro.net"};crawl.discovered={{"https://portal.aidapro.net/",200,18422,"text/html",0,"",crawl.started_unix_ms},{"https://portal.aidapro.net/api/v2/session",200,941,"application/json",1,"https://portal.aidapro.net/",crawl.started_unix_ms+1200},{"https://portal.aidapro.net/api/v2/symbols",200,12784,"application/json",2,"https://portal.aidapro.net/app.js",crawl.started_unix_ms+3400}};crawl.log={"Seed queued: portal.aidapro.net","Discovered API route /api/v2/session","Parsed 14 endpoints from app.js","Crawl completed"};s_preview_crawls={crawl};}
inline bool initialize(){ensure_preview_crawls();return true;}inline void shutdown(){}inline uint64_t start(const crawl_config_t& config){crawl_status_t crawl;crawl.id=s_preview_next_crawl++;crawl.phase=crawl_status_phase_t::complete;crawl.pages_visited=12;crawl.urls_found=19;crawl.started_unix_ms=aida::preview::network::monotonic_ms()-3200;crawl.finished_unix_ms=aida::preview::network::monotonic_ms();crawl.last_progress_unix_ms=crawl.finished_unix_ms;crawl.pages_per_sec=3.8;crawl.config=config;crawl.last_url=config.start_urls.empty()?"":config.start_urls.front();crawl.discovered={{crawl.last_url,200,16384,"text/html",0,"",crawl.started_unix_ms}};crawl.log={"Preview crawl completed without network access"};s_preview_crawls.push_back(crawl);aida::preview::network::record_receipt("Crawler",crawl.last_url);return crawl.id;}inline bool stop(uint64_t id){for(auto& crawl:s_preview_crawls)if(crawl.id==id){crawl.phase=crawl_status_phase_t::stopping;return true;}return false;}inline crawl_status_t status(uint64_t id){ensure_preview_crawls();for(const auto& crawl:s_preview_crawls)if(crawl.id==id)return crawl;return{};}inline std::vector<crawl_status_t> list(){ensure_preview_crawls();return s_preview_crawls;}inline bool remove(uint64_t id){const auto n=s_preview_crawls.size();s_preview_crawls.erase(std::remove_if(s_preview_crawls.begin(),s_preview_crawls.end(),[id](const auto& crawl){return crawl.id==id;}),s_preview_crawls.end());return n!=s_preview_crawls.size();}inline std::string last_error(){return{};}
}

namespace content_discovery {
inline uint64_t s_preview_next_discovery=3;inline std::vector<disc_status_t> s_preview_discoveries;
inline void ensure_preview_discoveries(){if(!s_preview_discoveries.empty())return;disc_status_t run;run.id=1;run.phase=disc_phase_t::complete;run.attempts=420;run.total=420;run.hits=5;run.filtered=391;run.started_unix_ms=aida::preview::network::monotonic_ms()-130000;run.finished_unix_ms=run.started_unix_ms+74000;run.calibrated_size_lo=118;run.calibrated_size_hi=136;run.last_url="https://sandbox.aidapro.net/debug/modules";run.config.target_url="https://sandbox.aidapro.net";run.config.wordlist_id="paths/reverse-engineering";run.hits_list={{"https://sandbox.aidapro.net/api", "api",301,0,38,"text/html","/api/",0},{"https://sandbox.aidapro.net/api/v2/symbols","api/v2/symbols",200,12784,64,"application/json","",0},{"https://sandbox.aidapro.net/debug/modules","debug/modules",403,312,41,"application/json","",0}};s_preview_discoveries={run};}
inline bool initialize(){ensure_preview_discoveries();return true;}inline void shutdown(){}inline uint64_t start(const config_t& config){disc_status_t run;run.id=s_preview_next_discovery++;run.phase=disc_phase_t::complete;run.attempts=120;run.total=120;run.hits=3;run.filtered=110;run.started_unix_ms=aida::preview::network::monotonic_ms()-4800;run.finished_unix_ms=aida::preview::network::monotonic_ms();run.config=config;run.last_url=config.target_url+"/api/v2/artifacts";run.hits_list={{run.last_url,"api/v2/artifacts",200,8042,52,"application/json","",0}};s_preview_discoveries.push_back(run);aida::preview::network::record_receipt("Content discovery",config.target_url);return run.id;}inline bool stop(uint64_t id){for(auto& run:s_preview_discoveries)if(run.id==id){run.phase=disc_phase_t::stopping;return true;}return false;}inline disc_status_t status(uint64_t id){ensure_preview_discoveries();for(const auto& run:s_preview_discoveries)if(run.id==id)return run;return{};}inline std::vector<disc_status_t> list(){ensure_preview_discoveries();return s_preview_discoveries;}inline std::vector<hit_t> results(uint64_t id){return status(id).hits_list;}inline bool remove(uint64_t id){const auto n=s_preview_discoveries.size();s_preview_discoveries.erase(std::remove_if(s_preview_discoveries.begin(),s_preview_discoveries.end(),[id](const auto& run){return run.id==id;}),s_preview_discoveries.end());return n!=s_preview_discoveries.size();}inline std::string last_error(){return{};}
}

namespace subdomain_enum {
inline uint64_t s_preview_next_enum=3;inline std::vector<enum_status_t> s_preview_enums;
inline void ensure_preview_enums(){if(!s_preview_enums.empty())return;enum_status_t run;run.id=1;run.phase=enum_phase_t::complete;run.passive_count=6;run.brute_attempts=1000;run.brute_resolved=4;run.started_unix_ms=aida::preview::network::monotonic_ms()-210000;run.finished_unix_ms=run.started_unix_ms+97000;run.config.domain="aidapro.net";run.results={{"api.aidapro.net",{"23.88.62.199"},{"certificate transparency","dns"},true,run.started_unix_ms+800},{"portal.aidapro.net",{"23.88.62.199"},{"certificate transparency","bruteforce"},true,run.started_unix_ms+1400},{"sandbox.aidapro.net",{"23.88.62.199"},{"bruteforce"},true,run.started_unix_ms+2200},{"telemetry.aidapro.net",{"23.88.62.199"},{"certificate transparency"},true,run.started_unix_ms+3100}};s_preview_enums={run};}
inline bool initialize(){ensure_preview_enums();return true;}inline void shutdown(){}inline uint64_t start(const config_t& config){enum_status_t run;run.id=s_preview_next_enum++;run.phase=enum_phase_t::complete;run.passive_count=4;run.brute_attempts=1000;run.brute_resolved=3;run.started_unix_ms=aida::preview::network::monotonic_ms()-4200;run.finished_unix_ms=aida::preview::network::monotonic_ms();run.config=config;run.results={{"api."+config.domain,{"23.88.62.199"},{"preview passive"},true,run.started_unix_ms+200},{"sandbox."+config.domain,{"23.88.62.199"},{"preview brute"},true,run.started_unix_ms+400}};s_preview_enums.push_back(run);aida::preview::network::record_receipt("Subdomain enumeration",config.domain);return run.id;}inline bool stop(uint64_t id){for(auto& run:s_preview_enums)if(run.id==id){run.phase=enum_phase_t::stopping;return true;}return false;}inline enum_status_t status(uint64_t id){ensure_preview_enums();for(const auto& run:s_preview_enums)if(run.id==id)return run;return{};}inline std::vector<enum_status_t> list(){ensure_preview_enums();return s_preview_enums;}inline std::vector<subdomain_t> results(uint64_t id){return status(id).results;}inline bool remove(uint64_t id){const auto n=s_preview_enums.size();s_preview_enums.erase(std::remove_if(s_preview_enums.begin(),s_preview_enums.end(),[id](const auto& run){return run.id==id;}),s_preview_enums.end());return n!=s_preview_enums.size();}inline std::string export_csv(uint64_t id){std::string csv="fqdn,ips,sources,resolves\n";for(const auto& item:status(id).results){csv+=item.fqdn+","+(item.ips.empty()?"":item.ips.front())+","+(item.sources.empty()?"":item.sources.front())+","+(item.resolves?"true":"false")+"\n";}return csv;}inline std::string last_error(){return{};}
}

namespace intruder {
inline uint64_t s_preview_next_job=3;inline std::vector<status_t> s_preview_jobs;inline std::map<uint64_t,std::vector<result_t>> s_preview_results;
inline void ensure_preview_jobs(){if(!s_preview_jobs.empty())return;s_preview_jobs={{1,5,5,0,false,18.4,aida::preview::network::monotonic_ms()-98000,aida::preview::network::monotonic_ms()-94000},{2,4,4,0,false,12.7,aida::preview::network::monotonic_ms()-44000,aida::preview::network::monotonic_ms()-41000}};s_preview_results[1]={{1,0,{"1"},200,941,43,"{\"role\":\"analyst\"}",{},false,{}},{1,1,{"1'"},500,1382,69,"database syntax error near quote",{},false,{}},{1,2,{"1 OR 1=1"},200,18421,51,"{\"artifacts\":[...]}",{},false,{}},{1,3,{"1 AND 1=2"},200,24,48,"{\"artifacts\":[]}",{},false,{}},{1,4,{"1 UNION SELECT NULL"},403,312,46,"Access denied",{},false,{}}};s_preview_results[2]={{2,0,{"user"},403,312,41,"Forbidden",{},false,{}},{2,1,{"admin"},200,884,47,"{\"permissions\":[\"symbols:write\"]}",{},false,{}},{2,2,{"debug"},404,129,39,"Not found",{},false,{}},{2,3,{"system"},403,312,42,"Forbidden",{},false,{}}};}
inline uint64_t start(config_t config){ensure_preview_jobs();status_t job;job.job_id=s_preview_next_job++;const size_t total=config.payload_sets.empty()?1:std::max<size_t>(1,config.payload_sets.front().size());job.total=total;job.sent=total;job.running=false;job.current_rps=static_cast<double>(total)*4.2;job.started_unix_ms=aida::preview::network::monotonic_ms()-900;job.finished_unix_ms=aida::preview::network::monotonic_ms();std::vector<result_t> rows;for(size_t i=0;i<total;++i){result_t result;result.job_id=job.job_id;result.index=i;result.payloads={config.payload_sets.empty()?"preview":config.payload_sets.front()[i]};result.status_code=i%3==1?403:200;result.response_size=i%3==1?312:941+i*73;result.latency_ms=41+i*5;result.response_preview=result.status_code==200?"{\"preview\":\"accepted\"}":"Forbidden";rows.push_back(std::move(result));}s_preview_jobs.push_back(job);s_preview_results[job.job_id]=std::move(rows);aida::preview::network::record_receipt("Intruder job",config.host);return job.job_id;}inline bool stop(uint64_t id){for(auto& job:s_preview_jobs)if(job.job_id==id){job.running=false;job.finished_unix_ms=aida::preview::network::monotonic_ms();return true;}return false;}inline status_t status(uint64_t id){ensure_preview_jobs();for(const auto& job:s_preview_jobs)if(job.job_id==id)return job;return{};}inline std::vector<result_t> results(uint64_t id,size_t start,size_t max){ensure_preview_jobs();auto it=s_preview_results.find(id);if(it==s_preview_results.end()||start>=it->second.size())return{};const size_t end=max?std::min(it->second.size(),start+max):it->second.size();return std::vector<result_t>(it->second.begin()+static_cast<ptrdiff_t>(start),it->second.begin()+static_cast<ptrdiff_t>(end));}inline bool clear(uint64_t id){s_preview_results.erase(id);const auto n=s_preview_jobs.size();s_preview_jobs.erase(std::remove_if(s_preview_jobs.begin(),s_preview_jobs.end(),[id](const auto& job){return job.job_id==id;}),s_preview_jobs.end());return n!=s_preview_jobs.size();}inline std::vector<status_t> list_jobs(){ensure_preview_jobs();return s_preview_jobs;}inline std::string last_error(){return{};}
inline const char* attack_mode_name(attack_mode_t mode){static const char* labels[]={"sniper","battering_ram","pitchfork","clusterbomb","turbo","race"};const int i=static_cast<int>(mode);return i>=0&&i<6?labels[i]:"sniper";}inline const char* engine_mode_name(engine_mode_t mode){static const char* labels[]={"http1_serial","http1_pipelined","http1_pooled","http2_multiplexed","http2_single_packet"};const int i=static_cast<int>(mode);return i>=0&&i<5?labels[i]:"http1_pooled";}inline bool parse_attack_mode(const std::string& value,attack_mode_t& output){for(int i=0;i<6;++i)if(value==attack_mode_name(static_cast<attack_mode_t>(i))){output=static_cast<attack_mode_t>(i);return true;}return false;}inline bool parse_engine_mode(const std::string& value,engine_mode_t& output){for(int i=0;i<5;++i)if(value==engine_mode_name(static_cast<engine_mode_t>(i))){output=static_cast<engine_mode_t>(i);return true;}return false;}
}

namespace api_definition {
inline uint64_t s_preview_next_collection=3;inline std::vector<api_collection_t> s_preview_collections;
inline void ensure_preview_collections(){if(!s_preview_collections.empty())return;api_collection_t portal;portal.id=1;portal.name="AiDA Portal API";portal.format=api_format_t::openapi_json;portal.source_path="/aida-preview/contracts/portal-openapi.json";portal.base_url="https://portal.aidapro.net";portal.imported_ms=aida::preview::network::monotonic_ms()-320000;portal.requests={{"session.get","GET",portal.base_url,"/api/v2/session",{{"Accept","application/json"}},{},{},{},"","bearer","Returns the current analyst session","Get current session",{"Session"}},{"symbols.list","GET",portal.base_url,"/api/v2/symbols",{{"Accept","application/json"}},{},{{"module","suspect.dll"}},{},"","bearer","Lists reconstructed symbols","List symbols",{"Analysis"}},{"artifact.submit","POST",portal.base_url,"/api/v2/artifacts",{{"Content-Type","application/json"}},{},{},{{"sha256",""}},"{\"sha256\":\"{{sha256}}\",\"mode\":\"deep\"}","bearer","Submits an artifact for analysis","Submit artifact",{"Artifacts"}}};api_collection_t sandbox=portal;sandbox.id=2;sandbox.name="Reverse Engineering Sandbox";sandbox.format=api_format_t::postman_v2_1;sandbox.source_path="/aida-preview/contracts/sandbox.postman.json";sandbox.base_url="https://sandbox.aidapro.net";for(auto& request:sandbox.requests)request.base_url=sandbox.base_url;s_preview_collections={portal,sandbox};}
inline bool initialize(){ensure_preview_collections();return true;}inline void shutdown(){}inline uint64_t import_from_text(const std::string&,api_format_t format){ensure_preview_collections();api_collection_t collection;collection.id=s_preview_next_collection++;collection.name="Imported API Collection";collection.format=format;collection.base_url="https://sandbox.aidapro.net";collection.imported_ms=aida::preview::network::monotonic_ms();collection.requests={{"imported.health","GET",collection.base_url,"/health",{{"Accept","application/json"}},{},{},{},"","none","Imported preview endpoint","Health check",{"Imported"}}};s_preview_collections.push_back(collection);aida::preview::network::record_receipt("API definition","imported text");return collection.id;}inline uint64_t import_from_file(const std::string& path,api_format_t hint){const auto id=import_from_text("{}",hint==api_format_t::auto_detect?detect_format_from_path(path):hint);s_preview_collections.back().source_path=path;return id;}inline uint64_t import_from_url(const std::string& url){const auto id=import_from_text("{}",api_format_t::openapi_json);s_preview_collections.back().source_path=url;return id;}inline std::vector<api_collection_t> list_collections(){ensure_preview_collections();return s_preview_collections;}inline bool get_collection(uint64_t id,api_collection_t& output){ensure_preview_collections();for(const auto& collection:s_preview_collections)if(collection.id==id){output=collection;return true;}return false;}inline bool remove_collection(uint64_t id){const auto n=s_preview_collections.size();s_preview_collections.erase(std::remove_if(s_preview_collections.begin(),s_preview_collections.end(),[id](const auto& collection){return collection.id==id;}),s_preview_collections.end());return n!=s_preview_collections.size();}inline size_t collection_count(){ensure_preview_collections();return s_preview_collections.size();}inline void clear_all(){s_preview_collections.clear();}
inline std::string substitute(std::string value,const std::map<std::string,std::string>& replacements){for(const auto& [key,replacement]:replacements){for(const std::string& marker:{"{{"+key+"}",":"+key}){size_t position=0;while((position=value.find(marker,position))!=std::string::npos){value.replace(position,marker.size(),replacement);position+=replacement.size();}}}return value;}
inline std::vector<uint8_t> render_to_raw_request(const api_request_template_t& request,const std::map<std::string,std::string>& path_values,const std::map<std::string,std::string>& query_values,const std::map<std::string,std::string>& header_values,const std::string& body_override){std::string path=substitute(request.path,path_values);bool first=path.find('?')==std::string::npos;for(const auto& [key,value]:query_values){path+=first?'?':'&';first=false;path+=key+"="+value;}std::string host;std::string scheme;uint16_t port=0;std::string ignored;audit_http::parse_url(request.base_url,scheme,host,port,ignored);std::string raw=request.method+" "+path+" HTTP/1.1\r\nHost: "+host+"\r\n";for(const auto& [key,value]:request.headers)raw+=key+": "+value+"\r\n";for(const auto& [key,value]:header_values)raw+=key+": "+value+"\r\n";const std::string body=body_override.empty()?substitute(request.body_template,request.body_params.empty()?std::map<std::string,std::string>{}:std::map<std::string,std::string>(request.body_params.begin(),request.body_params.end())):body_override;if(!body.empty())raw+="Content-Length: "+std::to_string(body.size())+"\r\n";raw+="\r\n"+body;return std::vector<uint8_t>(raw.begin(),raw.end());}
inline bool audit_entire_collection(uint64_t id,const std::map<std::string,std::string>&,audit_result_t& output){api_collection_t collection;if(!get_collection(id,collection))return false;output.audit_id=9000+id;output.requests_sent=collection.requests.size();output.requests_failed=0;output.issues_raised=id==1?2:1;output.status="Complete";aida::preview::network::record_receipt("API collection audit",collection.name);return true;}
inline api_format_t detect_format_from_path(const std::string& path){const auto ends=[&](const char* suffix){const size_t n=std::char_traits<char>::length(suffix);return path.size()>=n&&path.compare(path.size()-n,n,suffix)==0;};if(path.find("postman")!=std::string::npos)return api_format_t::postman_v2_1;if(ends(".yaml")||ends(".yml"))return api_format_t::openapi_yaml;if(ends(".har"))return api_format_t::har;if(ends(".graphql")||ends(".gql"))return api_format_t::graphql_sdl;return api_format_t::openapi_json;}inline api_format_t detect_format_from_text(const std::string& text){if(text.find("openapi")!=std::string::npos)return api_format_t::openapi_json;if(text.find("swagger")!=std::string::npos)return api_format_t::swagger_v2;if(text.find("_postman_id")!=std::string::npos)return api_format_t::postman_v2_1;return api_format_t::auto_detect;}inline const char* format_label(api_format_t format){static const char* labels[]={"Auto","OpenAPI JSON","OpenAPI YAML","Swagger 2.0","Postman 2.1","HAR","GraphQL SDL"};const int i=static_cast<int>(format);return i>=0&&i<7?labels[i]:"Auto";}inline bool parse_format(const std::string& value,api_format_t& output){for(int i=0;i<7;++i)if(value==format_label(static_cast<api_format_t>(i))){output=static_cast<api_format_t>(i);return true;}return false;}inline nlohmann::json template_to_json(const api_request_template_t& request){return{{"id",request.id},{"method",request.method},{"base_url",request.base_url},{"path",request.path},{"summary",request.summary},{"description",request.description},{"auth_kind",request.auth_kind},{"tags",request.tags}};}inline nlohmann::json collection_to_json(const api_collection_t& collection){nlohmann::json document={{"id",collection.id},{"name",collection.name},{"format",format_label(collection.format)},{"base_url",collection.base_url},{"requests",nlohmann::json::array()}};for(const auto& request:collection.requests)document["requests"].push_back(template_to_json(request));return document;}inline std::string last_error(){return{};}
}

namespace ws_editor {
inline uint64_t s_preview_next_connection=3;inline std::vector<ws_status_t> s_preview_connections;inline std::map<uint64_t,std::vector<ws_frame_log_t>> s_preview_frames;
inline void append_frame(uint64_t id,bool outbound,uint8_t opcode,const std::vector<uint8_t>& payload){ws_frame_log_t frame;frame.ts_ms=aida::preview::network::monotonic_ms();frame.outbound=outbound;frame.opcode=opcode;frame.payload=payload;frame.preview.assign(payload.begin(),payload.end());s_preview_frames[id].push_back(std::move(frame));for(auto& connection:s_preview_connections)if(connection.id==id){if(outbound)++connection.frames_sent;else++connection.frames_received;}}
inline void ensure_preview_connections(){if(!s_preview_connections.empty())return;s_preview_connections={{1,"wss://portal.aidapro.net/ws/analysis",true,2,2,aida::preview::network::monotonic_ms()-160000,{}},{2,"wss://sandbox.aidapro.net/ws/debug",true,1,2,aida::preview::network::monotonic_ms()-82000,{}}};const std::string one="{\"type\":\"analysis.subscribe\",\"module\":\"suspect.dll\"}";const std::string two="{\"type\":\"analysis.progress\",\"phase\":\"symbols\",\"value\":0.72}";const std::string three="{\"type\":\"analysis.symbols\",\"count\":1842,\"status\":\"ready\"}";append_frame(1,true,1,std::vector<uint8_t>(one.begin(),one.end()));append_frame(1,false,1,std::vector<uint8_t>(two.begin(),two.end()));append_frame(1,false,1,std::vector<uint8_t>(three.begin(),three.end()));}
inline bool initialize(){ensure_preview_connections();return true;}inline void shutdown(){}inline uint64_t connect(const ws_connection_config_t& config){ensure_preview_connections();ws_status_t status;status.id=s_preview_next_connection++;status.url=config.scheme+"://"+config.host+":"+std::to_string(config.port)+config.path;status.connected=true;status.opened_ms=aida::preview::network::monotonic_ms();s_preview_connections.push_back(status);aida::preview::network::record_receipt("WebSocket connected",status.url);return status.id;}inline bool disconnect(uint64_t id){for(auto& connection:s_preview_connections)if(connection.id==id){connection.connected=false;return true;}return false;}inline bool disconnect_all(){for(auto& connection:s_preview_connections)connection.connected=false;return true;}inline std::vector<ws_status_t> list_connections(){ensure_preview_connections();return s_preview_connections;}inline bool get_status(uint64_t id,ws_status_t& output){ensure_preview_connections();for(const auto& connection:s_preview_connections)if(connection.id==id){output=connection;return true;}return false;}inline bool send_text(uint64_t id,const std::string& message){append_frame(id,true,1,std::vector<uint8_t>(message.begin(),message.end()));const std::string response="{\"type\":\"preview.ack\",\"bytes\":"+std::to_string(message.size())+"}";append_frame(id,false,1,std::vector<uint8_t>(response.begin(),response.end()));return true;}inline bool send_binary(uint64_t id,const std::vector<uint8_t>& data){append_frame(id,true,2,data);return true;}inline bool send_raw_frame(uint64_t id,uint8_t opcode,bool,bool,const std::vector<uint8_t>& payload){append_frame(id,true,opcode,payload);return true;}inline bool send_ping(uint64_t id,const std::vector<uint8_t>& payload){append_frame(id,true,9,payload);append_frame(id,false,10,payload);return true;}inline bool send_pong(uint64_t id,const std::vector<uint8_t>& payload){append_frame(id,true,10,payload);return true;}inline bool send_close(uint64_t id,uint16_t,const std::string&){append_frame(id,true,8,{});return disconnect(id);}inline std::vector<ws_frame_log_t> frames(uint64_t id,size_t start,size_t max){ensure_preview_connections();auto it=s_preview_frames.find(id);if(it==s_preview_frames.end()||start>=it->second.size())return{};const size_t end=max?std::min(it->second.size(),start+max):it->second.size();return std::vector<ws_frame_log_t>(it->second.begin()+static_cast<ptrdiff_t>(start),it->second.begin()+static_cast<ptrdiff_t>(end));}inline size_t frame_count(uint64_t id){ensure_preview_connections();return s_preview_frames[id].size();}inline void clear_frames(uint64_t id){s_preview_frames[id].clear();}inline std::string last_error(){return{};}
}

namespace h2_editor {
inline std::string s_preview_h2_error;
inline std::vector<uint8_t> encode_frame(const frame_t& frame){std::vector<uint8_t> output(9);const uint32_t length=static_cast<uint32_t>(frame.payload.size());output[0]=static_cast<uint8_t>((length>>16)&0xff);output[1]=static_cast<uint8_t>((length>>8)&0xff);output[2]=static_cast<uint8_t>(length&0xff);output[3]=frame.type;output[4]=frame.flags;uint32_t stream=frame.stream_id&0x7fffffff;if(frame.r_bit)stream|=0x80000000;output[5]=static_cast<uint8_t>((stream>>24)&0xff);output[6]=static_cast<uint8_t>((stream>>16)&0xff);output[7]=static_cast<uint8_t>((stream>>8)&0xff);output[8]=static_cast<uint8_t>(stream&0xff);output.insert(output.end(),frame.payload.begin(),frame.payload.end());return output;}
inline bool decode_frames(const std::vector<uint8_t>& data,std::vector<frame_t>& output){output.clear();size_t offset=0;while(offset+9<=data.size()){frame_t frame;frame.length=(static_cast<uint32_t>(data[offset])<<16)|(static_cast<uint32_t>(data[offset+1])<<8)|data[offset+2];frame.type=data[offset+3];frame.flags=data[offset+4];const uint32_t stream=(static_cast<uint32_t>(data[offset+5])<<24)|(static_cast<uint32_t>(data[offset+6])<<16)|(static_cast<uint32_t>(data[offset+7])<<8)|data[offset+8];frame.r_bit=(stream&0x80000000)!=0;frame.stream_id=stream&0x7fffffff;offset+=9;if(offset+frame.length>data.size()){s_preview_h2_error="Truncated HTTP/2 frame";output.clear();return false;}frame.payload.assign(data.begin()+static_cast<ptrdiff_t>(offset),data.begin()+static_cast<ptrdiff_t>(offset+frame.length));offset+=frame.length;output.push_back(std::move(frame));}if(offset!=data.size()){s_preview_h2_error="Trailing bytes after HTTP/2 frames";return false;}s_preview_h2_error.clear();return true;}
inline response_t send(const request_t& request){response_t response;response.ok=true;response.status_code=200;response.headers={{":status","200"},{"content-type","application/json"},{"server","aida-preview-h2"},{"x-analysis-module",request.pseudo.authority.empty()?request.host:request.pseudo.authority}};const std::string body="{\"protocol\":\"h2\",\"stream\":1,\"path\":\""+request.pseudo.path+"\",\"status\":\"ready\"}";response.body.assign(body.begin(),body.end());response.latency_ms=38;frame_t headers;headers.type=1;headers.flags=5;headers.stream_id=1;headers.payload={'p','r','e','v','i','e','w','-','h','p','a','c','k'};frame_t data;data.type=0;data.flags=1;data.stream_id=1;data.payload=response.body;response.raw_wire_in=encode_frame(headers);auto encoded=encode_frame(data);response.raw_wire_in.insert(response.raw_wire_in.end(),encoded.begin(),encoded.end());if(request.use_raw_frames){for(const auto& frame:request.raw_frames){auto bytes=encode_frame(frame);response.raw_wire_out.insert(response.raw_wire_out.end(),bytes.begin(),bytes.end());}}else{frame_t outbound;outbound.type=1;outbound.flags=static_cast<uint8_t>(request.flags);outbound.stream_id=1;outbound.payload={'p','r','e','v','i','e','w'};response.raw_wire_out=encode_frame(outbound);}s_preview_h2_error.clear();aida::preview::network::record_receipt("HTTP/2 request",request.host+request.pseudo.path);return response;}inline std::string last_error(){return s_preview_h2_error;}
}

namespace report {
inline uint64_t s_preview_next_report=3;inline std::vector<generated_report_t> s_preview_reports={{1,aida::preview::network::monotonic_ms()-210000,"Reverse Engineering Security Assessment","/aida-preview/reports/reverse-engineering-assessment.html",report_format_t::html,3,false},{2,aida::preview::network::monotonic_ms()-72000,"Sandbox API Findings","/aida-preview/reports/sandbox-api.sarif",report_format_t::sarif_2_1,2,false}};
inline bool generate(const report_config_t& config,std::string& output){generated_report_t report;report.id=s_preview_next_report++;report.ts_ms=aida::preview::network::monotonic_ms();report.title=config.title.empty()?"AiDA Security Assessment":config.title;report.format=config.format;report.issue_count=config.include_issue_ids.empty()?issue_store::count():config.include_issue_ids.size();report.output_path=config.output_path.empty()?"/aida-preview/reports/report-"+std::to_string(report.id)+"."+default_extension(config.format):config.output_path;report.inline_output=false;s_preview_reports.push_back(report);output=report.output_path;aida::preview::network::record_receipt("Security report",report.output_path);return true;}inline bool parse_format(const std::string& value,report_format_t& output){for(int i=0;i<=static_cast<int>(report_format_t::csv);++i){const auto format=static_cast<report_format_t>(i);if(value==format_label(format)){output=format;return true;}}return false;}inline const char* format_label(report_format_t format){static const char* labels[]={"HTML","Markdown","JSON","SARIF 2.1","CSV"};const int i=static_cast<int>(format);return i>=0&&i<5?labels[i]:"HTML";}inline const char* default_extension(report_format_t format){static const char* extensions[]={"html","md","json","sarif","csv"};const int i=static_cast<int>(format);return i>=0&&i<5?extensions[i]:"html";}inline std::vector<generated_report_t> list_reports(){return s_preview_reports;}inline size_t reports_count(){return s_preview_reports.size();}inline void clear_history(){s_preview_reports.clear();aida::preview::network::record_receipt("Report history","cleared");}inline std::string last_error(){return{};}
}

}
