"""
XOR-encrypt the built Sentinel.sys binary into src/sentinel_encrypted.h
for embedding in AiDAStandalone.

Usage:
    python src/encrypt_sentinel.py

The script reads build/Release/Sentinel.sys and writes the
encrypted header to src/sentinel_encrypted.h.
"""
import os, sys

SENTINEL_XOR_KEY = bytes([
    0xD7, 0x2B, 0x83, 0x4E, 0xF1, 0x69, 0xA5, 0x1C,
    0x38, 0xE0, 0x54, 0x9F, 0x7A, 0xC6, 0x0D, 0xB2
])

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
INPUT_PATH = os.path.join(PROJECT_ROOT, "build", "Release", "Sentinel.sys")
OUTPUT_PATH = os.path.join(SCRIPT_DIR, "sentinel_encrypted.h")

def main():
    if not os.path.isfile(INPUT_PATH):
        print(f"[!] Input file not found: {INPUT_PATH}")
        sys.exit(1)

    with open(INPUT_PATH, "rb") as f:
        raw_bytes = f.read()

    total = len(raw_bytes)
    print(f"[*] Read {total} bytes from {INPUT_PATH}")
    print(f"[*] First 2 bytes: 0x{raw_bytes[0]:02X} 0x{raw_bytes[1]:02X}")

    if raw_bytes[0] != 0x4D or raw_bytes[1] != 0x5A:
        print("[!] Data does NOT start with MZ -- not a valid PE.")
        sys.exit(1)

    encrypted = bytes([b ^ SENTINEL_XOR_KEY[i % len(SENTINEL_XOR_KEY)]
                       for i, b in enumerate(raw_bytes)])

    dec0 = encrypted[0] ^ SENTINEL_XOR_KEY[0]
    dec1 = encrypted[1] ^ SENTINEL_XOR_KEY[1]
    assert dec0 == 0x4D and dec1 == 0x5A, "Round-trip verification failed!"
    print("[+] Encryption verified (decrypts back to MZ)")

    lines = []
    lines.append("#pragma once\n")
    lines.append("\n")
    lines.append("/* XOR-encrypted Sentinel.sys driver bytes.\n")
    lines.append("   Generated by encrypt_sentinel.py -- DO NOT EDIT.\n")
    lines.append("   Key is in driver_loader.cpp. */\n")
    lines.append("\n")
    lines.append(f"static const unsigned char g_sentinel_encrypted[{total}] = {{\n")

    BYTES_PER_LINE = 12
    for i in range(0, total, BYTES_PER_LINE):
        chunk = encrypted[i:i + BYTES_PER_LINE]
        hex_strs = [f"0x{b:02X}" for b in chunk]
        line = "\t" + ", ".join(hex_strs)
        if i + BYTES_PER_LINE < total:
            line += ","
        lines.append(line + "\n")

    lines.append("};\n")
    lines.append("\n")
    lines.append(f"static const unsigned long g_sentinel_encrypted_size = sizeof(g_sentinel_encrypted);\n")

    with open(OUTPUT_PATH, "w") as f:
        f.writelines(lines)

    print(f"[+] Wrote encrypted header to {OUTPUT_PATH}")
    print(f"[+] {total} bytes encrypted with 16-byte XOR key")

if __name__ == "__main__":
    main()
