"""
XOR-encrypt the raw WhosWho.sys bytes exported by HxD (WhosWho.c)
into src/whoswho_encrypted.h for embedding in AiDA.dll.

Usage:
    python src/encrypt_whoswho.py

The script reads WhosWho.c from the project root and writes the
encrypted header to src/whoswho_encrypted.h.
"""
import re, os, sys

WHOSWHO_XOR_KEY = bytes([
    0xA3, 0x5F, 0x17, 0xD2, 0x8B, 0x64, 0xE9, 0x31,
    0xCC, 0x4A, 0x76, 0xF0, 0x0E, 0x93, 0xB8, 0x2D
])

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
INPUT_PATH = os.path.join(PROJECT_ROOT, "WhosWho.c")
OUTPUT_PATH = os.path.join(SCRIPT_DIR, "whoswho_encrypted.h")

def main():
    if not os.path.isfile(INPUT_PATH):
        print(f"[!] Input file not found: {INPUT_PATH}")
        sys.exit(1)

    with open(INPUT_PATH, "r") as f:
        content = f.read()

    hex_pattern = re.compile(r"0x([0-9A-Fa-f]{2})")
    matches = hex_pattern.findall(content)
    raw_bytes = bytes([int(m, 16) for m in matches])
    total = len(raw_bytes)

    print(f"[*] Parsed {total} bytes from {INPUT_PATH}")
    print(f"[*] First 2 bytes: 0x{raw_bytes[0]:02X} 0x{raw_bytes[1]:02X}")

    if raw_bytes[0] != 0x4D or raw_bytes[1] != 0x5A:
        print("[!] Data does NOT start with MZ -- not a valid PE.")
        sys.exit(1)

    encrypted = bytes([b ^ WHOSWHO_XOR_KEY[i % len(WHOSWHO_XOR_KEY)]
                        for i, b in enumerate(raw_bytes)])

    dec0 = encrypted[0] ^ WHOSWHO_XOR_KEY[0]
    dec1 = encrypted[1] ^ WHOSWHO_XOR_KEY[1]
    assert dec0 == 0x4D and dec1 == 0x5A, "Round-trip verification failed!"
    print("[+] Encryption verified (decrypts back to MZ)")

    lines = []
    lines.append("#pragma once\n")
    lines.append("\n")
    lines.append("/* XOR-encrypted WhosWho.sys driver bytes.\n")
    lines.append("   Generated by encrypt_whoswho.py -- DO NOT EDIT.\n")
    lines.append("   Key is in driver_loader.cpp. */\n")
    lines.append("\n")
    lines.append(f"static const unsigned char g_whoswho_encrypted[{total}] = {{\n")

    BYTES_PER_LINE = 12
    for i in range(0, total, BYTES_PER_LINE):
        chunk = encrypted[i:i + BYTES_PER_LINE]
        hex_strs = [f"0x{b:02X}" for b in chunk]
        line = "\t" + ", ".join(hex_strs)
        if i + BYTES_PER_LINE < total:
            line += ","
        lines.append(line + "\n")

    lines.append("};\n")
    lines.append("\n")
    lines.append(f"static const unsigned long g_whoswho_encrypted_size = sizeof(g_whoswho_encrypted);\n")

    with open(OUTPUT_PATH, "w") as f:
        f.writelines(lines)

    print(f"[+] Wrote encrypted header to {OUTPUT_PATH}")
    print(f"[+] {total} bytes encrypted with 16-byte XOR key")

if __name__ == "__main__":
    main()
